### ISSUE TITLE
MySQL 5.6 versus 5.7

### ISSUE THREAD

**Issue by aaiezza** [specify/specify6#1]
Hello,
Just curious: The [MySQL setup guide](http://specifyx.specifysoftware.org/wp-content/static/Installing%20MySQL%20on%20Windows%20for%20Specify.pdf) instructs you to use version 5.6 of MySQL Server. Could you use the latest with no issues?
Best,
Alex

**Comment by benanhalt** [comment]
Yes, it should work. I'm using 5.7.20 on my development machine, but I'm not sure if we have officially tested it or not. @tlammer?

**Comment by aaiezza** [comment]
@benanhalt Awesome. Ok. That's what I thought.
It just seems strange to me that it takes so long for the SpWizard to work… It runs for hours during the final installation process only to stop at "92%" with an error message that there was an unknown error.

**Comment by benanhalt** [comment]
Hmm. I don't have occasion to use SpWizard very often, so it is possible that it has problems with MySQL 5.7 that I haven't encountered.

@garrettgirard @yvonneekanim @tlammer, have any of you seen this problem with the wizard?

**Comment by aaiezza** [comment]
Ah! Sorry for the false information. Specify initialized the database and fired up with no problem! I guess it just took longer than I expected.
Thank you.
