### ISSUE TITLE
Can't modify Geography in Collecting Event based batch editing but you can in Collection Object batch editing

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#100]
Not sure which way this is supposed to go, but in a fish database, when I do a CO query, include CE, Loc, and Geo fields, I can change the Geography info in batch editing.
When I do a CE query and include all the same fields (except CO), geography is grayed out.

**Comment by timo11** [comment]
Geography should be available for co, ce and locality batch editing.

**Comment by tlammer** [comment]
was able to modify using CO, CE, and Loc queries
