### ISSUE TITLE
Update Specify Network Preference screen

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#1010]
Can we move the 'About' button to the bottom and still allow it to link to the web page?

<img width="1185" alt="SpNetworkPrefScreen" src="https://user-images.githubusercontent.com/61208178/127506835-2b47217c-67d6-46af-bfc8-9d5c6b13f8ee.png">

**Comment by timo11** [comment]
No, not really, the button bar at the bottom applies to the entire dialog not individual pref pages.

**Comment by tlammer** [comment]
about is now first
