### ISSUE TITLE
Adjust default deaccession form

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#1025]
Timestamp Modified and Type fields are getting cut off a little bit

![Screenshot_2021-08-06_20-45-12](https://user-images.githubusercontent.com/40512816/128551216-26161c92-cbf0-4016-8943-013275d03d72.png)

**Comment by maxxxxxdlp** [comment]
Besides #1018, found just two more minor form issues:

![Screenshot_2021-08-06_21-33-29](https://user-images.githubusercontent.com/40512816/128556676-6c7d53f7-5aee-4e2b-8f21-c8d07c56889d.png)

![Screenshot_2021-08-06_21-34-38](https://user-images.githubusercontent.com/40512816/128556675-ddb30b85-4f6f-4608-b748-e9154401b11b.png)

All other forms look fine

**Comment by maxxxxxdlp** [comment]
This one is fixed - https://github.com/specify/specify6/issues/1025#issue-962930701
These two are not - https://github.com/specify/specify6/issues/1025#issuecomment-894446750

**Comment by tlammer** [comment]
@maxxxxxdlp can you take a screen shot of what the forms look like now, please

**Comment by maxxxxxdlp** [comment]
![Screenshot_2021-08-06_23-11-08](https://user-images.githubusercontent.com/40512816/128566141-c662f07a-982f-428e-83d6-a2873e85d618.png)
![Screenshot_2021-08-06_23-11-16](https://user-images.githubusercontent.com/40512816/128566143-afcdc90e-eab8-4eb9-b564-a1330b056a2c.png)

**Comment by tlammer** [comment]
waiting on Max to confirm the file I sent worked before adding it to the code

**Comment by maxxxxxdlp** [comment]
DNA Sequence is fixed
Disposal still has "Timestamp Modified" label cut off:
![Screenshot_2021-08-07_11-50-30](https://user-images.githubusercontent.com/40512816/128594770-3931a560-a5ce-449b-bcaf-b0e4ccec49ea.png)

Also, I started getting this error when I open the Collection Object form:
![Screenshot_2021-08-07_11-51-50](https://user-images.githubusercontent.com/40512816/128594791-19ffb8e1-5058-4a22-8236-ae70efebff3b.png)
Did I import the views incorrectly?

**Comment by tlammer** [comment]
@timo11 can you change the caption for disposal.timestampModified to Date Modified, please?
@maxxxxxdlp the CO error indicates you have modified CO forms that have issues.  The default Botany forms do not have the issue reported.

**Comment by benanhalt** [comment]
The "Timestamp Modified" label on the disposal form is still truncated in the latest build. The other problems seem to be resolved.

**Comment by benanhalt** [comment]
The Deaccession form now has the new caption for the timestampmodified field, but the Disposal form doesn't.

![image](https://user-images.githubusercontent.com/287254/128926530-98434243-7a9a-4f24-ac1a-a62d3abd3a13.png)
![image](https://user-images.githubusercontent.com/287254/128926627-5ae671dd-20c1-48fc-adb5-fb6590895833.png)

**Comment by benanhalt** [comment]
Disposal form now has the new caption as well when a new database is created.
