### ISSUE TITLE
Restrict java version between 1.8 and 11.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#1028]
see #1027.

instal4j should be configured to require the minimum version to be 1.8,  and maximum to be 11.

**Comment by benanhalt** [comment]
On a linux system, attempting to run the installer with openjdk-16 installed results in the following error:
```console
$ sh Specify_unix_64.sh 
No suitable Java Virtual Machine could be found on your system.
The version of the JVM must be at least 1.8 and at most 11.
Please define INSTALL4J_JAVA_HOME to point to a suitable JVM.
```
