### ISSUE TITLE
Loan Preparation allows more items to be loaned than the prep count has

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#1031]
loan prep quantity can be raised higher than the prep count says there are.

**Comment by timo11** [comment]
The quantity field, if it is a spinner, will have min allowable value of the quantity resolved for the loanpreparation, and a max allowable value equal to the number of specimens that remain available - i.e. not gifted, exchangeouted, disposed, or loaned.

Shortcomings: If the return information is edited, and the quantity resolved is changed, the minimum value will not be adjusted until the loan is saved. Also, if a preparation is associated with more than loanpreparation in a loan, edits to a loanpreparation will not be reflected in the max quantity limit of the preparation's other loanpreps until the loan is saved.

**Comment by maxxxxxdlp** [comment]
Still happening with disposal preparations

![Screenshot_2021-08-13_19-19-06](https://user-images.githubusercontent.com/40512816/129389464-ad487d63-fe37-40fc-af9c-726f1488fdc1.png)

**Comment by maxxxxxdlp** [comment]
Loan preparation issue is fixed
Gift preparation was fixed in https://github.com/specify/specify6/issues/1042
