### ISSUE TITLE
Interactions Sidebar settings are shared between all user types

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#1038]
A guest user can overwrite the Interactions Sidebar for all users (including Managers) and permanently remove some tables (like Accession) from the list

This is how manager's Interactions sidebar looked initially:
![Screenshot_2021-08-13_00-29-45](https://user-images.githubusercontent.com/40512816/129273116-2e1ea53a-4e1a-414d-abe8-2785ade1d8bc.png)

1. Create a guest user
2. Log in as a guest user
3. Make any changes to the sidebar
4. Log in as a manager user
5. The interactions sidebar has the changes from step 3 and does not have tables that guest does not have access to (e.x Accession)

Now, the sidebar looks like this:
![Screenshot_2021-08-13_00-32-13](https://user-images.githubusercontent.com/40512816/129273222-b8e693f6-2f91-4b25-949d-acbb8edc64c3.png)

**Comment by maxxxxxdlp** [comment]
If a guest hides all tables from the sidebar, the "Interactions" menu disappears completely for the manager

![Screenshot_2021-08-13_00-40-09](https://user-images.githubusercontent.com/40512816/129273720-b0b4b445-597a-4ad4-8d0f-b5798f5115a0.png)

**Comment by norinespears** [comment]
These are local to the machine so as expected.

**Comment by maxxxxxdlp** [comment]
But is it expected that if a guest user makes any changes to their sidebar, a manager user on that machine would lose access to all tables that are not available for a guest user?

**Comment by tlammer** [comment]
at what point during the process did you turn on security?  It wasn't on in the first screen then seemed to turn on later

**Comment by maxxxxxdlp** [comment]
Hmm, I am unable to replicate this either with security or or off
Would reopen this if it happens again
