### ISSUE TITLE
wb/b.e. invalidates geocoords form system considers valid

### ISSUE THREAD

**Issue by timo11** [specify/specify6#104]
If you choose DegreesMinutesSeconds format in the locality form but don't enter a value for seconds for latitude, when the locality is batch edited the geocoords will be invalidated because the wb thinks lat is in DegreesDecimalMinutes format and longitude is in DegreesMinutesDecimalSeconds format, which is  impermissable.

**Comment by timo11** [comment]
The locality form latlon panel and the wb should agree about lat/lng formats now.

**Comment by yvonneekanim** [comment]
confirmed: lat/long fields are no longer invalidated. locality form and wb agree on lat/long format
