### ISSUE TITLE
Installer does not launch the Wizard

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#107]
I chose to launch the Wizard at the end of my installation and the Wizard did not launch.

**Comment by timo11** [comment]
Using the 'Beta' installers, the wizard and specify launched for me for 64 bit linux, as well as 32 and 64 bit windows (on a 64 bit windows system).

**Comment by garrettgirard** [comment]
I just tried this from the windows 64bit non-Beta installer and, although it seemed to hesitate for like 10 seconds, it eventually launched the wizard.

**Comment by garrettgirard** [comment]
Also works for windows 32bit non-Beta installer, same build.

**Comment by garrettgirard** [comment]
It worked for me on the windows 64bit Beta installer, **BUT NOT the windows 32bit Beta installer.**

**Comment by beach53** [comment]
This did not work for me.

-------------------------------
James H. Beach
705 Mississippi Street
Lawrence, KS 66044
Home: 785-331-0421
Cell: 785-331-8508

**Comment by timo11** [comment]
Specify and the wizard still launch for me for all 4 windows installers on windows 10 64 bit.
