### ISSUE TITLE
Sp won't let you save WBs if data tabs are open

### ISSUE THREAD

**Issue by timo11** [specify/specify6#109]
If you click save in the WB when a data tab is open a popup popsup to inform you that you can't upload while data forms are open so you better close them before you upload, except you're not uploading you're saving, and now you're confused and angry as hell as well, so you kill specify but a dialog comes up asking if you want to save the dataset, and if you choose 'Yes' ...

**Comment by garrettgirard** [comment]
Tested in KU Fish on 10000PisDay. It now saves as it should, even with a data tab open.
