### ISSUE TITLE
Dropping fresh recordsets on a query doesn't execute the query. 

### ISSUE THREAD

**Issue by timo11** [specify/specify6#110]
Recordsets created by the batch editor, and possibly recordsets created by the non-be wb, when dropped on a query, will open the query, but not run it.
However, after restarting specify, these very same wb recordsets will execute queries they are dropped upon.

**Comment by timo11** [comment]
Recordsets should now possess total drop power from the moment of birth.

**Comment by garrettgirard** [comment]
BE recordsets now drop with much success, the best success of any recordsets that have ever been.
