### ISSUE TITLE
Recordsets on recordsets on recordsets

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify6#111]
When drag/dropping recordsets onto other recordsets, the expected outcome is that the recordset onto which the dragged recordset is dropped should then have all of the records from the dragged recordset. This does not work at all for BE recordsets. As for regular recordsets (obtained from queries and the like), the feature does seem to work, but it can be somewhat wonky. Sometimes it works immediately, other times you have to close/reopen tabs or forms and click on the recordset again to see the records added. Otherwise there seems to be some weird delay that happens relatively often. Shouldn't be too difficult to replicate.

**Comment by timo11** [comment]
B.E. rsesses should work same as others w/o sp restart.
I didn't really notice any wonkinesss, but the merging should be faster now.

**Comment by yvonneekanim** [comment]
Dragging and dropping works as expected for both regular and BE recordsets
