### ISSUE TITLE
Already In Logged IN dlg changes

### ISSUE THREAD

**Issue by timo11** [specify/specify6#112]
Change title to:   Already Logged In

Change next line to: Specify thinks you are already logged in.

Then

If you are certain no one is logged-in with your user name, click 'Override".

-------------------------------
James H. Beach

**Comment by yvonneekanim** [comment]
Changes have been applied
![log in](https://user-images.githubusercontent.com/28809154/38153873-8b6ec534-3434-11e8-85ff-a7c79cab7282.png)
