### ISSUE TITLE
Lengthen Container Name field

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#1123]
Requested by Barcelona.  The Name field in Container was too short for them.  They requested at least 200 characters

**Comment by benanhalt** [comment]
Will change name to 1024, and description to a text.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-6-8-02-and-schema-2-10-release-notes/830/1
