### ISSUE TITLE
Lengthen Locality Name field to at least 800 characters

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#1125]
Request by UTAustin
On another topic, we (Botany) have a request/proposal that the locality field on the locality table be expanded from its current 255 characters either to an unlimited varchar/text field or at least expanded to >800 characters. We currently have some records with ~750 characters as are using the remarks field as a sort of overflow which is far from an elegant solution.

I realize that the field was probably intended to be a name rather than a description, but some of our older (and even not so old) specimens have longer descriptions of where a particular collecting event took place.

**Comment by benanhalt** [comment]
Will update localityName to 2048.

**Comment by benanhalt** [comment]
It turns out 2048 is too long for MySQL for fields which are indexed. The field will be adjusted to 1024 instead.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-6-8-02-and-schema-2-10-release-notes/830/1
