### ISSUE TITLE
Picklists are sorted alphabetically with uppercase letters sorted first

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify6#1134]
![image](https://user-images.githubusercontent.com/37256050/160148065-3dd3869a-c9f1-4978-a260-2f3fe5c2a39e.png)

**Reported By**: CSIRO Corrina & Vivek

Bug seems to be here 

```
return title.compareTo(obj.getTitle());
could've been 
return title.compareTocompareToIgnoreCase(obj.getTitle());
```

https://github.com/specify/specify6/blob/24cbca18e126ac0a68d1343eb4ee32326e3b5bf5/src/edu/ku/brc/specify/datamodel/PickListItem.java#L319

**Comment by maxxxxxdlp** [comment]
Fixed on the `develop` branch. Also, confirmed the fix is working

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-6-8-02-and-schema-2-10-release-notes/830/1
