### ISSUE TITLE
ending setting for aggregators displays incorrectly.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#114]
If the count for an aggregator is set, then the ending setting is only supposed to display if there are greater than count related objects. However, it displays if the number of related objects is equal to or greather than the count setting.

**Comment by garrettgirard** [comment]
I have the count set for 2 in the Collector aggregator, with the ending as ", et al."
When I generate a label for a CO record that has 4 collectors, I get the following result:
Coll: g, g; Dirt, Joe; Truman, Harry, et al.
In other words, it is printing 3 of 4 collectors followed by et al, even though I designated the count as "2".

**Comment by garrettgirard** [comment]
Reports This now appears on the report as follows:
Coll: g, g; Dirt, Joe, et al.
Seems to be working well.
