### ISSUE TITLE
GeoLocate button is greyed out. The same collection viewed in Specify 7 works correctly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify6#1142]
When viewing a collections Locality (Collecting event - Locality) in Specify 6, the GeoLocate button (highlighted in Red box in image below) is greyed out. Viewing the same collection in Specify 7 the same button is clickable and opens the GeoLocate plugin correctly. 

![image](https://user-images.githubusercontent.com/37256050/177613561-87551bdd-5973-4baf-91ef-6670bdb9ba43.png)

**Reported By:** Don at CSIRO

**Comment by maxxxxxdlp** [comment]
It looks like the form is opened in read-only mode.

Since GeoLocale is primarily made for editing Locality coordinates, it would make sense that the button would be disabled in that case
