### ISSUE TITLE
the geolocate plugin needs to be adaptable to url changes 

### ISSUE THREAD

**Issue by timo11** [specify/specify6#115]

**Comment by timo11** [comment]
The remote pref GEOLOCATE_BASE_URL can be set to change the url for the geolocate services.
The default value is "http://www.museum.tulane.edu/webservices/" .

Things to test:
1) Verify GeoLocate works 'as is'. Don't set the pref. See if geo locate matches and returns values.
2) Make sure the pref is being read. Set it to  "http://bad.invalid.nonexistent.spud/webdevils/" or some other trashy url. When you use geolocate, you should always get the 'Geolocate returned no matches' msg.
3) Test GeoLocate thoroughly with the pref set to "http://www.museum.tulane.edu/webservices/" to make sure everything is working when the url is read from the pref.

More testing may be necessary when Ben figures out how to mimic the forwarding or redirecting Nelson might do when he leaves Tulane.

**Comment by timo11** [comment]
Now there are four geolocate prefs. But only the first two matter (we think) All are remote prefs.
   GEOLOCATE_SERVICE_URL. DEFAULT = "http://www.museum.tulane.edu/webservices/geolocatesvcv2/geolocatesvc.asmx";
    GEOLOCATE_WEB_URL. DEFAULT = "http://www.museum.tulane.edu/geolocate/web/WebGeoref.aspx?v=1";
GEOLOCATE_NAMESPACE_URL. DEFAULT = "http://www.museum.tulane.edu/webservices/";
GEOLOCATE_SOAP_URL. DEFAULT = "http://www.museum.tulane.edu/webservices/";

The things to test are pretty much the same as the earlier comment, except the pref to test should be the GEOLOCATE_SERVICE_URL with the default above.

**Comment by tlammer** [comment]
how do we change the preference?

**Comment by timo11** [comment]
ctrl-dbl-click wherever on the about form to open remote prefs.

**Comment by tlammer** [comment]
should that pref be in my remote prefs already or am I supposed to add it.  I didn't see it, so if it is supposed to be there, the issue is still open

**Comment by timo11** [comment]
It's not supposed to be there.

**Comment by tlammer** [comment]
I added these preferences and changed the first one to 
GEOLOCATE_SERVICE_URL. DEFAULT = "http://www.museum.ku.edu/webservices/geolocatesvcv2/geolocatesvc.asmx";
Restarted Specify, and I still got results.

**Comment by timo11** [comment]
The pref is GEOLOCATE_SERVICE_URL, the DEFAULT is  http://www.museum.tulane.edu/webservices/geolocatesvcv2/geolocatesvc.asmx ?
