### ISSUE TITLE
Add ORC ID field to Agent form

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#1152]
Requested by several institutions.
Needs to be a text field that is turned into a weblink on the form

**Comment by benanhalt** [comment]
We should add a formatter for validating OCRIDs for that field.

https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier

**Comment by benanhalt** [comment]
Will make a new one-to-many table for agent external identifiers.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-6-8-02-and-schema-2-10-release-notes/830/1
