### ISSUE TITLE
Requested Field additions

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#1154]
Requested by Barcelona:
​- Second storage tree is for «current location of the collection object» (the first storage tree has been used for “permanent locationof the collection object”)

- yes, a 6th text field and a 2nd date field in Preparation. Second date field is for “date degree of physical integrity” (which is used to add the date when the “degree of physical integrity” was determined (we used “sample number” field for the “degree of physical integrity”)).

-the intent of the date field in the Conservator Description is s for “date conservation status” (which is used to add the date when the “conservation status” was determined (we used “shortDesc” field for the “conservation status”)).

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-6-8-02-and-schema-2-10-release-notes/830/1
