### ISSUE TITLE
Increase `PickListItem.value` length

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#1157]
CSIRO:

> is there still time to add a request to the schema changes list for Specify6?! Can we increase the length of the value field in the picklistitem table - it's currently set to 128 characters but we have values up to ~250 characters

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-6-8-02-and-schema-2-10-release-notes/830/1
