### ISSUE TITLE
Need icons for ExchangeInAttachment and ExchangeOutAttachment.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify6#1168]
To go in https://github.com/specify/specify6/tree/master/src/edu/ku/brc/specify/images/datamodel

**Comment by grantfitzsimmons** [comment]
![exchange_in_attachment](https://user-images.githubusercontent.com/37256050/198907897-a5e799f5-c050-4fe5-b10b-28cc1ae9d197.png)
![exchange_out_attachment](https://user-images.githubusercontent.com/37256050/198907899-33ad19d9-4188-470f-9980-fe49253d74ce.png)

**Comment by benanhalt** [comment]
Testing pls check icons for these tables appear in the UI.
