### ISSUE TITLE
Cannot create Exchange Out record in restored databases

### ISSUE THREAD

**Issue by chanulee1** [specify/specify6#1170]
Loads forever when trying to create an Exchange Out record from a record set or by entering catalog numbers/identifiers in restored databases. Seems to work fine in newly created databases.

Restored databases used: `freshfish`, `herb_rbge`, `cornell_birds`
Error messages (when creating from catalog numbers/identifiers):
<img alt="image" width="500px" src="https://user-images.githubusercontent.com/103299204/198747277-48e3efd2-32bd-47ac-9677-8efd602e5f6c.png"/>
<img alt="image" width="600px" src="https://user-images.githubusercontent.com/103299204/198747461-6663a028-bc62-4103-b000-a268768bba5a.png"/>
Seem to get these errors or something similar while loading.

**Comment by benanhalt** [comment]
@chanulee1 I think this might be fixed by the next build on the schema210 branch. Can you give it a try when you have a chance? Thanks

**Comment by chanulee1** [comment]
Sorry for the delay. Works in `cornell_birds`. Dialog for preparation selection now appears. Still loads forever after this step for `freshfish` and `herb_rbge`.

`herbrbge`:
![image](https://user-images.githubusercontent.com/103299204/199895747-ef750473-dabf-442f-a3ca-f2d5707e29a5.png)
![image](https://user-images.githubusercontent.com/103299204/199895859-da67282f-b72d-4922-9600-d96ac13e77d1.png)

`freshfish`:
![image](https://user-images.githubusercontent.com/103299204/199899049-3f2fed7f-9e6f-4e67-a481-5711fcb79e32.png)
![image](https://user-images.githubusercontent.com/103299204/199899104-23899c4f-ec6a-411b-8d4b-c21b666cf1b5.png)

**Comment by benanhalt** [comment]
Looking at the freshfish database, the null pointer exception is arising from there being no element on the form for the division. In the common forms it is included as `<cell type="field" id="divcbx" name="divisionCBX" uitype="combobox" ignore="true"/>` and the NPE doesn't occur.

I have committed a change that will avoid the NPE in this circumstance, and in my testing it does allow the exchange out form in the freshfish database. However, that form is also missing the ExchangeOutNumber field so it is still not possible to save any record from it.

**Comment by chanulee1** [comment]
I see. Seems to work!
