### ISSUE TITLE
Fields now lowercase after update in the schema

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify6#1171]
The number fields in the voucher relationship table are now lowercase in the database. Will this cause problems?

Table | voucherrelationship `2.10` | voucherrelationship `2.9`
-- | -- | --
Columns | Columns | Columns
Column | number1 | N/A
Column | number2 | N/A
Column | N/A | Number1
Column | N/A | Number2

<img width="596" alt="image" src="https://user-images.githubusercontent.com/37256050/199058327-60a5a4bf-d172-423b-b038-b180c7cd73e2.png">

Feel free to close this if there are no negative consequences.

Same situation for `collectionobjectattribute` for the fields
`bottomDistance` and `topDistance`

**Comment by benanhalt** [comment]
Fixed in next build. I don't think it would make a difference, but fixed just to be sure.
