### ISSUE TITLE
Negative numbers marked as errors in Specify 6.8.02

### ISSUE THREAD

**Issue by mc0822** [specify/specify6#1180]
**Describe the bug**
In Specify 6.8.02, user cannot save negative numbers in number fields.  This appears to be a validation issue; negative numbers are marked as errors.

**To Reproduce**
This behavior was encountered in both Locality and Col Obj Attribute tables.

**Expected behavior**
Negative numbers should be able to be validated/saved.

**Desktop:**
 - OS: Windows 10
 
![121322](https://user-images.githubusercontent.com/111374878/207457467-37d35628-e7b1-4e87-8a51-9f361dd7328e.PNG)

**Reported By**
Kesler Randall of SDNMH

**Comment by maxxxxxdlp** [comment]
Happens because of https://github.com/specify/specify6/commit/28a17533de9eb09db1344b4b0e96a4163dbd504f#diff-4a7fddcdf3972ccbdb385e2ffd07c718227b271d9076c94d74eece41d2890f26R333-R336

Seems like there was an assumption in the code that BigDecmial fields are only going to be used for currencies.
