### ISSUE TITLE
geo ref converter tool changes not reported to B.E.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#123]
Lat/Lng cells changed by georef fmt converter tool aren't highlighted in green because b.e. doesn't know they've been edited.

**Comment by yvonneekanim** [comment]
Changes made in the batch editor using the georef converter tool are now highlighted

**Comment by timo11** [comment]
Query results always show decimal degrees. Locality form should now show the format selected with the  tool.

**Comment by yvonneekanim** [comment]
Form view now shows format chosen in BE
