### ISSUE TITLE
The `Accession` table does not have a `deaccessions` field.

### ISSUE THREAD

**Issue by mcruz-umich** [specify/specify6#1232]
https://github.com/specify/specify6/blob/945d28f00288d2d64979848fb2fb63fda34bdd1b/config/common/common.views.xml#L1437C1-L1438C1

This subview will not work because the `Accession` table does not have a `deaccessions` field.

**Comment by grantfitzsimmons** [comment]
Fixed in https://github.com/specify/specify7/pull/5367
