### ISSUE TITLE
If an existing query has series checked and is opened in Batch Editing, the user can't batch edit the results but wouldn't know why

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#128]
Because series is not an option in the batch editing screen, if the series checkbox was checked in the regular query, the user can't see it was checked and doesn't know why they can't batch edit the results

**Comment by garrettgirard** [comment]
If #129 is working, then does that mean this is also working?

**Comment by garrettgirard** [comment]
Also fixed.
