### ISSUE TITLE
Save/Discard unsaved changes dialogs are confusing

### ISSUE THREAD

**Issue by timo11** [specify/specify6#135]
When a form with unsaved changes is closed, either directly as a result of a user action, or not so directly such as when the user closes the application, or the process controlling the form, One of two dialogs appears: If the data in form is valid and can be saved specify displays a dlg with the title "Discard Changes" ,msg "Do you want to discard changes for 'XXX'?; and 'Save Changes', 'Discard Changes', and 'Cancel' buttons. If the data is invalid you get a dlg with  the title "Save Changes" ,msg "Do you want to save changes for 'XXX'?; and 'Discard Changes', and 'Cancel' buttons. Madness!

**Comment by timo11** [comment]
After fix, for valid forms you get title = "Save Changes" ,msg "Do you want to save changes for 'XXX'?; and 'Save Changes', 'Discard Changes', and 'Cancel' buttons. 
For invalid forms you get title = "Discard Changes" ,msg "Do you want to discard changes for 'XXX'?; and 'Discard Changes', and 'Cancel' buttons.

**Comment by yvonneekanim** [comment]
New dialog appears as described
