### ISSUE TITLE
Geolocate urls need to be updated

### ISSUE THREAD

**Issue by timo11** [specify/specify6#136]

**Comment by timo11** [comment]
The new values are:
GEOLOCATE_SOAP_URL_DEFAULT = "http://geo-locate.org/webservices/";

GEOLOCATE_NAMESPACE_URL_DEFAULT = "http://geo-locate.org/webservices/";

GEOLOCATE_SERVICE_URL_DEFAULT = "http://geolocate.org/webservices/legacy/geolocatesvcv2/geolocatesvc.asmx";

**Comment by timo11** [comment]
The remote prefs, which can be set if problems arise, are:

GEOLOCATE_SOAP_URL:  http://geo-locate.org/webservices/
GEOLOCATE_NAMESPACE_URL:  http://geo-locate.org/webservices/
GEOLOCATE_SERVICE_URL: http://geolocate.org/webservices/legacy/geolocatesvcv2/geolocatesvc.asmx
GEOLOCATE_WEB_URL: http://www.geo-locate.org/web/WebGeoref.aspx?v=1

see #115

**Comment by yvonneekanim** [comment]
Geolocate returns data in wb and form view and data can be saved with no errors
