### ISSUE TITLE
Make it possible to give BatchEdit permissions to users who are not Admins or Managers

### ISSUE THREAD

**Issue by timo11** [specify/specify6#137]

**Comment by timo11** [comment]
Fixed.
BatchEdit is available on the "Tools" page of the security configuration tool.

Note: 
WB upload permission and QB permissions need to be granted in addition to BatchEdit permissions or else the BatchEditor won't be available.

**Comment by yvonneekanim** [comment]
Batch edit is available in the tool bar and is only available by default to managers as expected. If write permissions are turned off for a table, the table does not show up in qb and cannot be batch edited. Saved queries containing fields from tables whose write permissions are disabled cannot be edited as well.
