### ISSUE TITLE
Send to Symbiota is broken

### ISSUE THREAD

**Issue by timo11** [specify/specify6#138]
Clicking the 'Send to Symbiota' button results in a stack trace window due to a null pointer exception in DwcMapper.java

**Comment by timo11** [comment]
[Sp6.7exportMappingUSCH.txt](https://github.com/specify/specify6/files/1948601/Sp6.7exportMappingUSCH.txt)

The bug is probably pretty general and will happen for most symbiota connectors, but it definitely happened for the attached mapping.

To test with it, it will have to be imported, saved. Then the cache will need to be built with the Exporter application. Then a Symbiota connector will need to be created. (Enter some random junk for the Symbiota Key property.) Then 'Send to Symbiota'. If there are no exception popups, the fix is good. (The final step will fail due to the phony Key.)

**Comment by timo11** [comment]
This is a regression created by the fix for bugzilla bug 10363.

**Comment by timo11** [comment]
It actually seems pretty certain that this bug is caused a specific 'manually added' mapping in the attached file. It is most likely NOT a general issue with Symbiota mappings.

**Comment by yvonneekanim** [comment]
Harrod Brown confirmed fixed
