### ISSUE TITLE
Series data entry goes awry

### ISSUE THREAD

**Issue by timo11** [specify/specify6#139]
Reported by KU invert paleo.

They are entering 282175-194 for a series, followed by 282155-164.
When specify validates the series entry the catnum control returns
282155 as the start of the series, but by the time it saves the
series, the catnum control says its start number is 282175.

So it thinks it has a valid series beginning with 282175, since it
never reaches the series end of 282164 it just keeps adding new
records from 282195 untill the 500 rec series limit is reached.

I have been able to replicate the bug using the backup in their conversiondatabases dir from 2018/4/20.

**Comment by yvonneekanim** [comment]
New series can be implemented regardless of if older series does not reach max value of 500 records
