### ISSUE TITLE
BE: Partial date fields not editable

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify6#14]
While you can edit full date fields in the BE, you can't edit partial date fields (like the year field, month field, and day field). Users may want to use this feature in case they have to make changes to several records for just one of those fields and it might be easier if they are able to edit a single date part field.

**Comment by tlammer** [comment]
I can edit partial date fields

**Comment by tlammer** [comment]
should say, I can edit it when it is a single field.  When added as separate fields, you can't edit them

**Comment by garrettgirard** [comment]
Sorry, that's what I meant. You can edit partial dates if editing a single field, however you cannot edit them when separated.
