### ISSUE TITLE
Problem with Exporter app cache updates

### ISSUE THREAD

**Issue by timo11** [specify/specify6#140]
When more than 100k records need to be updated, the update process hangs indefinitely.

When this happens the update will proceed through 100k blocks normally, with the status msg saying "Updating rows 100001-200000 of 323000'. But for one block, the count will get confused, and the status msg says "200013 - 300000 of 323000". If for the last chunk of records the status is something like "300013 - 322287 of 323000", after the chunk is finished the display will change to "322288 - 322287 of 323000" forever

**Comment by timo11** [comment]
The file 20181115a.sql is the KU birds directory on specify6 produced the problem for both Andy and me, so it should be a good test case. It will need to be opened first with Specify to update it from 6.6.06. Then login to it with the Exporter app. It should say 123000 or so records need to be updated for both mappings. Update the dwc cache. Wait for it to finish.

**Comment by timo11** [comment]
For the record: The conditions required for this bug are a) More than 100k records need to be updated. b) There are records that have been deleted.

**Comment by yvonneekanim** [comment]
The count is still off but the "cache was updated successfully" pop up window appears at the end. There were 122300 out of date records, the first block showed 1-100000, second block 100013-122288 and the final block 122289-122288 of 122300.

I tested this in the ku birds database using the 2017115a.sql file.

**Comment by timo11** [comment]
final blocks will now be reported as 122288 of 122300, for example.

**Comment by yvonneekanim** [comment]
Count issue if fixed
