### ISSUE TITLE
Workbench Upload Settings window pops up behind the Match existing record window

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#141]
When uploading data through the Workbench if you come across a record that matches multiple records, a window pops up asking you to choose which record to match.  If you click the settings icon, the Upload Settings window pops up behind the match record window and the user can't see it.
Reported by David Werneke at Auburn

**Comment by beach53** [comment]
Windows

**Comment by yvonneekanim** [comment]
Still happening in windows 7
