### ISSUE TITLE
WebLinks are not exported to web portal

### ISSUE THREAD

**Issue by timo11** [specify/specify6#144]
Fields associated with web links are not exported as web links to the web portal (or the export cache, see #145). Only the value of the field is exported. The url is not constructed according to the weblink definition.

**Comment by timo11** [comment]
Fixed in commit 6141dbb in develop branch. But urls are only constructed for weblinks that only use the <this> element. Those that reference other fields are not constructed.
All <this>-only weblinks are converted to urls. Not sure if we should provide option to build url or export as is.

**Comment by yvonneekanim** [comment]
Fields with weblinks are shown as urls in the web portal
