### ISSUE TITLE
Symbiota send issue when Item not included in SchemaMapping has a concept

### ISSUE THREAD

**Issue by timo11** [specify/specify6#147]
If an item in a schema mapping with 'Show' un-checked is mapped to a concept, an exception popup will occur during the Send to Symbiota process.

**Comment by timo11** [comment]
concept list is now disabled and cleared when 'Show' is not checked.

**Comment by yvonneekanim** [comment]
I'm still getting an exception for the unchecked field in the jtester release and the send fails.
