### ISSUE TITLE
Batch Editor allows more than maximum of 7,000 rows

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify6#15]
Andy was right. I tested using a full 20,000 query result to batch edit. It still warned me that the maximum rows that would be used is 7,000 (not sure how it said 2,000 for Andy). But then when I clicked okay it decided to continue using all 20,000 rows. Also somehow it didn't give me the null pointer exception so that may be fixed in the latest build.

**Comment by timo11** [comment]
Still no idea where 2000 came from for Andy.
But it won't load more rows than the MAX_ROWS setting.
