### ISSUE TITLE
Importing Queries with same name under different users adds numbers to query name

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#152]
A user (des.qld) wants to share the same query between users.  When the different users import the query Specify adds numbers to the end of the names.  Ben said it should check for identical names within the same user, not within the database.

**Comment by yvonneekanim** [comment]
In previous versions of Specify, queries shared among users would have numbers added to the end of the query name. 

FIXED: Numbers are only added to a query if the same user imports it multiple times.
