### ISSUE TITLE
Paleo Context query combobox doesn't find Paleo Context name

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#154]
If you search the in the Paleo Context query combobox based on paleo context name, the paleo context is not found.
Tim said the fix is to change the HQL Template to 
SELECT %s1 FROM PaleoContext pc LEFT JOIN pc.chronosStrat cs LEFT JOIN cs.definition csd LEFT JOIN pc.chronosStratEnd cse LEFT JOIN cse.definition csed LEFT JOIN pc.lithoStrat ls LEFT JOIN ls.definition lsd WHERE pc.discipline.disciplineId = DSPLNID AND (pc.chronosStrat IS NULL OR csd.geologicTimePeriodTreeDefId=GTPTREEDEFID) AND (pc.chronosStratEnd IS NULL OR csed.geologicTimePeriodTreeDefId=GTPTREEDEFID) AND (pc.lithoStrat IS NULL OR lsd.lithoStratTreeDefId=LITHOTREEDEFID) AND %s2 ORDER BY pc.paleoContextName,cs.fullName,cse.fullName,ls.fullName

**Comment by timo11** [comment]
same as #149

**Comment by yvonneekanim** [comment]
Paleo context can now be searched in query combobox
