### ISSUE TITLE
Paleo Context Search (magnifying glass in query combobox) does not search on Paleo Context Name

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#155]
Click the magnifying glass in the paleo context query combobox and search for the paleo context name of an existing paleo context record with that name.  Nothing is returned and no indication that a search actually occurred.

Tim said the fix is to change the paleo context name line in search views to this:
 `             
<row>
                    <cell type="label" label="Paleo Context Name"/>
                    <cell type="field" id="pcn" name="pc.paleoContextName" isrequired="false" uitype="text"/>
                </row>
`

**Comment by yvonneekanim** [comment]
Paleo context search display results
