### ISSUE TITLE
Formatted fields in preparation not incrementing in grid view

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#157]
When preparation is in grid view, fields that have been formatted to display numeric values that can be auto-incremented display "###". However, when in form view, the field displays actual numbers upon saving.

**Comment by timo11** [comment]
what dbs do we have that suffer from this malady?

**Comment by tlammer** [comment]
I put a database in the Databases for Programmers directory for you to check. It is the only one from 9/24/18

**Comment by timo11** [comment]
Also, only one preparation can be added in form view. When more than one prep is created, in some cases only one  prep is auto-incremented, in most cases no preps are auto-incremented.

**Comment by yvonneekanim** [comment]
Fields in preparation can be incremented in both form and grid view. Multiple preparations can be added and are incremented in both views as well.
