### ISSUE TITLE
BE: Fill down/up does not activate Apply button

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify6#16]
If you only make changes to fields using the fill down or fill up right-click option, the Apply button will not become active, even though all the fields that are being changed are highlighted green. Making a change to a single cell will fix the issue. But this still may confuse some users and they might not realize they can fix it that way.

**Comment by garrettgirard** [comment]
Same goes for the revert button.

**Comment by timo11** [comment]
I can't duplicate this issue

**Comment by garrettgirard** [comment]
I'm still having this issue, even in the demodatabase. I'm going to try updating my build and see if that fixes the issue.


    On Wednesday, January 10, 2018, 11:45:47 AM CST, timo11 <notifications@github.com> wrote:  
 
 
I can't duplicate this issue

**Comment by garrettgirard** [comment]
I am still having this issue in the latest build. I tried another database as well (kentstatebryo). Tried on multiple fields from multiple tables.
![batcheditorfilldownup](https://user-images.githubusercontent.com/12533028/34793859-642b67f8-f612-11e7-8325-61ddf5bf0e02.png)

**Comment by timo11** [comment]
It only happened for me if I filled from the top row to the bottom row. Also, only if i'd never clicked the revert button.
