### ISSUE TITLE
Locality and Preparation (and possibly other tables) do not have unique constraints for GUID

### ISSUE THREAD

**Issue by timo11** [specify/specify6#17]

**Comment by timo11** [comment]
Preparation has a uniqueness defined in the Preparation class, but the index was not added to pre-existing dbs. Locality has neither definition nor the index.

**Comment by timo11** [comment]
Index is added for preparation.guid, but is still NOT there for locality.

**Comment by timo11** [comment]
if test for #19 passes. this must be good too.

**Comment by tlammer** [comment]
tried carry forward, adding one per CO, and adding via WorkBench.  all unique
