### ISSUE TITLE
Add DNA Sequence to WorkBench

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#175]
DNA Seq and DNA Seq run can be added to CO if there is only one DNA Seq run per sequence.  Tim says this is 'fixed' and ready for testing.  Austria wanted to use CO not MS.

Austria wants multiple Seq Runs for each Sequence and to bring them in through the workbench.  Not working.

Sp7 needs to be tested

No workbench support for uploading DNA Seq or DNA Seq Run through material sample.
Discussed about doing this in 7 only, tool would go to BOLD and pull in data, a tool could pull in DNA data from BOLD or whole record including specimen data.   We need to find out if BOLD is their only source of data.   Needs Research before we can do this in 7.

**Comment by timo11** [comment]
DNA sequence is available but not DNASequencing Run.
