### ISSUE TITLE
Change 'Show Loans' button to 'Show Interactions'

### ISSUE THREAD

**Issue by timo11** [specify/specify6#176]
formerly bugzilla #9695: Andy's idea. Show Interactions would be more helpful than Show Loans because it could show gifts & exchanges as well.

see #171, #174

**Comment by timo11** [comment]
Show Loans button shows loans, gifts, exchangeouts, and deaccessions.

**Comment by yvonneekanim** [comment]
'Show Loans' button shows all interactions. Button is still named 'show loans' instead of 'show interactions'
