### ISSUE TITLE
Schema changes 

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#181]
Barcelona requested the following fields be added to the schema

-Collection Object table:
1 fields linked to Agents table
1 date field

-Preparation table:
4 date fields
1 field linked to Storage tree (in addition to the field already linked to Storage tree)
4 string fields

-Collection Object Attribute table:
2 fields linked to Agents table
1 date field

-Collecting Event table: 
1 field linked to the Permit table

**Comment by tlammer** [comment]
and some more from Barcelona:
​- Fitxa feta (linked to Agents table)
- Data fitxa feta (date field)
- Registre (linked to Agents table)
- Data registre (date field)
- Revisió de la fitxa (linked to Agents table)
- Data revisió de la fitxa (date field)
- Revisió del registre (linked to Agents table)
- Data revisió del registre (date field)
