### ISSUE TITLE
'&' cannot be used as a separator in dataobj formatters.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#185]
This is required to conform with GGBN.
When you use '&', an error occurs when closing the schema configuration tool.

If '&amp;' is used, the format will save, and the formatter will display '&' in the formatted texts, but the next time the schema config tool is used, the same error that occurs if '&' is used will occur when the tool is closed.

**Comment by yvonneekanim** [comment]
Works as expected with no errors
