### ISSUE TITLE
Duplicate DNAPrimer formatter when schemaversion 2.5 dbs updated to 2.6 

### ISSUE THREAD

**Issue by timo11** [specify/specify6#187]
If a database was created in schemaversion 2.5, after it is updated to 2.6, it may have 2 DNAPrimer definitions.

This results in Exception popups.

**Comment by timo11** [comment]
The db in 2018_10_12_11_04_45.sql in ConversionDatabases/Geneva caused this error. After updating the schema, when the query builder search button was clicked, an exception window would pop up with a msg about a duplicate formatter name. So this would be a good database for verifying the fix.

**Comment by yvonneekanim** [comment]
Tested the Geneva db and a test db, no longer getting the duplicate DNA primer exception.
