### ISSUE TITLE
Create a new Collection Object Attribute table with a many to one relationship to Collection Object

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#188]
Requested by Barcelona and Florida

**Comment by timo11** [comment]
Still need icon, see #198

**Comment by tlammer** [comment]
Needs to have Darwin Core fields:
Measurement ID
Measurement Type
Measurement Value
Measurement Accuracy
Measurement Unit
Measurement Determined Date
Measurement Determined By
Measurement Method
Measurement Remarks

**Comment by yvonneekanim** [comment]
CO Attribute has many-to-one relationship with CO
