### ISSUE TITLE
Need to fix preparation guids

### ISSUE THREAD

**Issue by timo11** [specify/specify6#19]
The update guid routine that runs (or used to run) when schema updates happened did not update prep guids. Next release needs to include a fix for empty and duplicated prep guids. (Possibly other tables have the same problem.)

**Comment by timo11** [comment]
Use latest backups in KU herps and KU fish folders on specify6 to test this.
After the schema update, run a queries on preparation with just the GUID field. Check the count option.
With no condition for GUID, run the query with distinct checked and then with distinct checked. Then add a Not Empty condition for GUID and run again with distinct unchecked. You should get same result for all three.

**Comment by yvonneekanim** [comment]
Tested in KU herps, guid counts match for all specified testing parameters mentioned in the above comment.
