### ISSUE TITLE
Selecting Run Wizard on installer does not launch wizard

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#190]
I installed the 20181017 specify_windows.exe release and chose to Launch the wizard on the last screen but the wizard did not launch

**Comment by timo11** [comment]
works for me on linux and windows 10 enterprise

**Comment by tlammer** [comment]
couldn't duplicate

**Comment by yvonneekanim** [comment]
Selecting run wizard after install works on Windows and Mac
