### ISSUE TITLE
Opening a query gets progressively slower when switching between queries

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#191]
Reported by Queensland
"​Steps to reproduce: open Specify, click Query, and then switch between Agent and Collection Object repeatedly (without selecting any fields or running any queries)."

**Comment by tlammer** [comment]
Also:​
    When selecting fields which open a secondary form on the Agent query builder, Specify becomes progressively slower.

a.       Steps to reproduce: open Specify, click Query, select Agent, and then switch between “Addresses” and “Created by”.

**Comment by tlammer** [comment]
​I have looked at the database logs, and Specify appears to be executing the same query multiple times. For example, for issue 1, Specify is executing the following query:

 

SELECT RightSideCollectionID FROM collectionreltype WHERE Name = 'Host Taxon' AND LeftSideCollectionID = 4

                                                                              

The first time I try and open the form, it executes this same query a few hundred times. (Not sure why this would be.) Then each time I switch forms, it executes the same query roughly double the number of times as previously. So after a few switches, it’s executing this query many thousands of times. This appears to be the reason Specify is becoming progressively slower. Something similar is happening for the other 2 issues.

**Comment by yvonneekanim** [comment]
There are no delays when switching between queries or when switching between fields with secondary forms
