### ISSUE TITLE
Make Inventory Date a partial date field

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#196]
SDNHM requested making the field into a partial date field because they don't always know the exact date

**Comment by yvonneekanim** [comment]
Inventory date can be partialized by modifying the form using:

<cell type="label" labelfor="id"/>
<cell type="field" id="id" uitype="plugin" name="this" initialize="name=PartialDateUI;df=inventoryDate;tp=inventoryDatePrecision" uifieldformatter="Date"/>
