### ISSUE TITLE
Add to the Darwin Core schema mapping

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#202]
North Carolina Museum of Natural Sciences requested adding organismQuantity and organismQuantityType  to the available Darwin Core mappings.  The fields are in Darwin Core but are not listed in our options.

**Comment by timo11** [comment]
We have the latest version of the simple darwin core schema from 11/08/2014. Not sure why the two fields NCM wants are not in it. Not sure what other fields might be missing. I added organismQuantity and organismQuantityType.

**Comment by timo11** [comment]
to access the new terms the tdwg_dwcterms.xml file will have to be imported into a new schema

**Comment by yvonneekanim** [comment]
The file is tdwg_dwcterms.xsd and it can't be read by Specify.

**Comment by timo11** [comment]
if you use import schema on the schema mapper side bar and choose the file it should import.

**Comment by yvonneekanim** [comment]
organismQuantity and organismQuantityType are listed in the DWC schema
