### ISSUE TITLE
Permit search can only search by permit number

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#215]
Searches using other fields available in permit search window does nothing

**Comment by timo11** [comment]
see #108. This can be fixed by changing the permit search form in search.views.xml

**Comment by yvonneekanim** [comment]
The caption in the search_config file matches the names in the search.views file for PermitSearch but search still does nothing. Is there something else that should be done?

**Comment by timo11** [comment]
For the permit form the is required setting for PermitNumber causes any search that does not use permitnumber to fail.

**Comment by yvonneekanim** [comment]
Issued To Last Name has been removed from the form but searches still not working

**Comment by timo11** [comment]
fixed. permit number requirement eliminated. again.

**Comment by yvonneekanim** [comment]
For some reason search by dates is no longer returning any results. I modified the viewdef search names for issued date and start date to match what is on the search_config file.

Also renewal date and end date should probably be removed from permit search form since they are not in search_config

**Comment by timo11** [comment]
The problem is that PermitNumber is a required field. I don't know why it stopped working.
WORKAROUND: enter '*' in PermitNumber
I am investigating.

**Comment by timo11** [comment]
Two things needed to be changed:
The case of the name attributes was changed to match the search_config search.
The uiformatter attribute for the dates was changed to "SearchDate"

I also changed the uiformatter for dates in the search views for Appraisal, RepositoryAgreement, and Attachment (viewname = "ImageDateSearch")

EndDate and RenewalDate ARE in the PermitSearch in search_config.xml so I left them on the dialog.
