### ISSUE TITLE
Need to be able to disable the SpecialMsg check at Startup

### ISSUE THREAD

**Issue by timo11** [specify/specify6#226]
User request.

**Comment by timo11** [comment]
Fixed.

The msg check can be disabled by setting remote pref "DisableMessageCheckAtStartUp" to true.

When the check is skipped, the following should appear in the specify log file:
"DisableMessageCheckAtStartUp is true. Skipping nessage check."

**Comment by yvonneekanim** [comment]
14:24:49  INFO af.core.SpecialMsgNotifier:65 - DisableMessageCheckAtStartUp is true. Skipping message check
