### ISSUE TITLE
Labels generated from recordset ignoring "in" parameter set in query.

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#230]
If a label query has "in" as a parameter, when a recordset is dropped on the label the label ignores that parameter and displays all associated specimen. If you click on the label and run it from there, the parameter is obeyed.

**Comment by timo11** [comment]
Did you try checking 'always' for the 'in' condition?

**Comment by yvonneekanim** [comment]
Yes it was checked

**Comment by timo11** [comment]
Unable to duplicate.

**Comment by yvonneekanim** [comment]
Doesn't seem to be happening anymore
