### ISSUE TITLE
Add new fields to DNASequence and MaterialSample

### ISSUE THREAD

**Issue by timo11** [specify/specify6#231]
Add SequenceDate (with partial precision), ExtractionDate (with partial precision), and Extractor (Agent) to DNASequence.
Add Extractor (Agent) to MaterialSample

**Comment by yvonneekanim** [comment]
Above fields have been added to the schema. SequenceDate and ExtractionDate can be partialized.
Fields haven't been added to wbschema_localization and common.views

**Comment by yvonneekanim** [comment]
Fields have been added to workbench except DNA sequence remarks, genbank accession number, texts 1-3 and bold translation matrix are all required by default in the schema, again.

**Comment by timo11** [comment]
When I create a database with the wizard, remarks, genbank accession number, etc are NOT required by default.
The fix for #217 only changed the defaults, not existing dbs, because we couldn't be sure if any of the fields were purposefully set as required.

**Comment by tlammer** [comment]
I was able to upload partial dates to sequence date and extracted date and saw the fields mentioned in Yvonne's comment
