### ISSUE TITLE
Start Date Precision and End Date Precision should be removed from Workbench configuration.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#235]
Date precision fields are system fields that are assigned by business rules based on inputs to Date fields. When dates and precision fields are mapped, precision fields are ignored, however, if only precision fields are mapped, entered values are uploaded, and errors occur when the uploaded records are viewed. 

see #236

**Comment by yvonneekanim** [comment]
Start and end date precision have been removed form workbench datamodel config file
