### ISSUE TITLE
When Specify logs in to a db with a later Application version it does not shut down.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#237]
Specify says "This version of Specify '6.7.02' must be upgraded to version '6.7.03' You should download and install a newer version." Then "The application will now exit." And then the Choose a collection dialog appears. When you choose a collection, several exception windows pop up. Then Specify opens. The welcome page is blank, but otherwise specify seems functional.

I don't know if this happens in 6.7.01. I don't know if it's worse or better for single collection dbs.

**Comment by yvonneekanim** [comment]
When there is a version mismatch the application exists. However, I got a prompt to backup the db before it fully exited on one attempt. Should that happen?

**Comment by timo11** [comment]
Probably not. But hopefully users will be too confused to click 'Backup' before the screen disappears.

**Comment by yvonneekanim** [comment]
Should I mark this as fixed?
