### ISSUE TITLE
Sorting a field that is not displayed in query gives error

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#238]
Reported by SDNHM:

If a field is sorted in a query and the "Show" button is unchecked after it has been sorted, an out of bounds exception occurs when the query is run

**Comment by yvonneekanim** [comment]
Out of bounds error no longer occurs, field is grayed out when the "show" button is unchecked

**Comment by timo11** [comment]
Seems to be fixed. Confirmed Fixed even.
Unless someone feels it's necessary to clear an existing sort when "show" is unchecked in addition to disabling the sort control and ignoring its setting.

**Comment by timo11** [comment]
Looks like this bug was never verified, never reproduced?
No changes have been made to fix it, and no out of bounds exceptions are occurring.
