### ISSUE TITLE
Add SpAuditLogField changes to 6.7.02 schema update

### ISSUE THREAD

**Issue by timo11** [specify/specify6#239]
To possibly avoid having to do a schema update for the next release, we should include the field auditing schema changes in 6.7.02.

**Comment by timo11** [comment]
To test this, after a schema update, check the spauditlogfield table with mysql to verify the types of 3 fields: 'FieldName should be varchar(128), OldValue  should be text, and NewValue should be text.

**Comment by yvonneekanim** [comment]
There's no information in that table when there is a schema update
