### ISSUE TITLE
Status information for query not displayed for q's with date filters that return > 40k records

### ISSUE THREAD

**Issue by timo11** [specify/specify6#240]
If a query returns more records than Specify will display, and the query uses a date filter, when the "displaying first X of Y records" msg is created a hidden exception occurs, with the result that no msg at all is displayed in the status bar. 
This has probably been a bug for years.

**Comment by yvonneekanim** [comment]
I'm testing it in KU's Ento database. When I add a date filter to a collection object query, I don't get any status information. I ran the same query with count checked and there are 98000+ records that should be showing up in the query results.

**Comment by timo11** [comment]
The status msg and the displaying results msg disappear when the results have been displayed. Always have been and always will be. If a formatted field is added to the results, the display will take longer and the msg will be readable.

**Comment by yvonneekanim** [comment]
I've tried this with multiple aggregated fields in the query and well over 90000 records and still can't get the message to display

**Comment by yvonneekanim** [comment]
Message displays after all fields are fully loaded in the query results
