### ISSUE TITLE
Conditions on search dialogs remain in effect after they are removed. 

### ISSUE THREAD

**Issue by timo11** [specify/specify6#251]
Suppose there are 5 permits with IssuedDate = '2014-12-12' and one permit (Permit X) with IssuedDate = '2014-12-12' and StartDate = '2015-12-12'. If you search for  IssuedDate = '2014-12-12' and StartDate = '2015-12-12' you will find Permit X. If you remove the start date condition and search again you will still only get Permit X because the StartDate condition is still in effect.

**Comment by tlammer** [comment]
do the query suggested above, in the order recommended and I got all the records returned
