### ISSUE TITLE
Allow WB Datasets to be transferred to other users

### ISSUE THREAD

**Issue by timo11** [specify/specify6#255]
In the Workbench side bar when a dataset item is right clicked, it is now an option to transfer the dataset to another user. Eligible transferees will have view permission on the Workbench task, and have access to the current collection. A note documenting the transfer is added to the remarks field in the workbench.

**Comment by timo11** [comment]
Transfers currently do not show up in the audit logs.

**Comment by timo11** [comment]
Transferred datasets on the welcome tab, like deleted datasets on the welcome tab, are not opened when they are clicked.

**Comment by timo11** [comment]
see #261

**Comment by yvonneekanim** [comment]
Datasets can be transferred to eligible users. Transferred datasets do not appear on welcome screen
