### ISSUE TITLE
Add a refresh datasets option to the workbench task

### ISSUE THREAD

**Issue by timo11** [specify/specify6#265]
To display transferred datasets for example.

**Comment by timo11** [comment]
Test with multiple datasets open. Also test adding new datasets and deleting datasets. Make sure open datasets are always grayed out in side bar after refresh/delete/add

**Comment by tlammer** [comment]
Can we move it to be at the bottom of the list of Actions?

**Comment by timo11** [comment]
Yes,

**Comment by yvonneekanim** [comment]
Confirmed

**Comment by timo11** [comment]
Latest release is 6.7.02_internal_r and it is under actions.
