### ISSUE TITLE
Adding Container to query creator causes Specify to slow down

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#269]
There's a noticeable delay when switching from container to other tables and vice versa in the query creator.

**Comment by yvonneekanim** [comment]
I should also add that the 'parent' field can be opened multiple times in a container query 
![container](https://user-images.githubusercontent.com/28809154/54227100-33d39700-44cd-11e9-9712-59c934e43ea6.png)

**Comment by timo11** [comment]
Container, Agent, and Taxon queries should be creatable and closeable repeatedly w/o query creation time increasing. 

This fixes #191 and #113 also. HybridParent1 and HybridParent2 have been re-enabled in taxon queries. Parent has been enabled in taxon and geo queries. Parent can be opened up to 7 times in containers, and as many times as desired for taxon and geography.

The query builder should be tested in general in depth most vigorously.

**Comment by yvonneekanim** [comment]
Queries are no longer delayed
