### ISSUE TITLE
Cannot export data sets

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#272]
I dragged a data set onto export data set.  The navigation window appeared, I chose to export to my desktop and clicked Save.  The window disappeared but the file never appears.
I did this in a database created in the u release and one updated from 6.7.01

**Comment by tlammer** [comment]
export ms excel template also does not work

**Comment by timo11** [comment]
this is a side effect of the fix for getting addtoui setting in rstools_registry to keep geolocate off the plugins tab (#184)

**Comment by timo11** [comment]
PS. the ExportToFile tool entry should never be removed from rstools_registry.xml unless you want to disable dataset exports.

**Comment by tlammer** [comment]
I still could not export record sets in a database created in w

**Comment by yvonneekanim** [comment]
Both data set exports work when ExportToFile is in rstools_registry.xml
