### ISSUE TITLE
WorkBench creating records for every Collecting Trip Attribute record, even when it should be matching an existing CT/CTA record

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#277]
I uploaded a data set with CT and CTA data in the WorkBench.  I had records with identical CT and CTA data and records with identical CT data but differing CTA data.  
- CTA records were created for all of the rows with CTA data.
- Where the CT and CTA data was identical to other rows, multiple CTA records were still created.
- Where the CT data was the same as another row but CTA data was different, multiple CTA records were created, but only one CT record and it pointed to the first CTA recrod created.

The spreadsheet I used is named "tre" in Files for Programmers

**Comment by tlammer** [comment]
same thing happens for CEA in a database setup to have shared CO-CE rel

**Comment by timo11** [comment]
doesn't work for CEA in 6.6.00 either, in different way.

**Comment by timo11** [comment]
CE-CEA matching for shared CE broke in 6.7.00

**Comment by yvonneekanim** [comment]
Collecting trip and collecting event records are no longer made for identical entries. CT and CE records are created for entries with same information but different attributes
