### ISSUE TITLE
Removing add/edit/delete permissions on a table kills query combo box selection

### ISSUE THREAD

**Issue by timo11** [specify/specify6#278]
Removing add/edit/delete permissions on a table makes it impossible to even make selections with query combo box control connected to that table.

**Comment by timo11** [comment]
should be tested with different permissions.
I guess if editing permission is not present, there should be no pencil icon, if add permission is denied no + icon nor add... in the drop down list, and so on and so forth. No one cares about add/edit/delete but not view and similar stupid situations.

**Comment by timo11** [comment]
to whom it may concern: 
It seems that the search dlg is only available if add permission is granted, so searches without add permission can only be done via the text box and the drop down list.
Also, when only view permission is granted, the 'i' icon remains displayed and active in edit mode.

**Comment by yvonneekanim** [comment]
Works as it should
