### ISSUE TITLE
Add field level auditing to specify

### ISSUE THREAD

**Issue by timo11** [specify/specify6#283]
When records are updated populate the spauditlogfield table with the old and new values of changed fields.
Make it possible to query the audit logs with the query builder.
Allow disalbling/enabling of field level auditing.

**Comment by timo11** [comment]
Auditing can be customized with two remote prefs. 
auditing.do_audits when false stops auditing completely. To re-enable auditing set it to true or remove.
auditing.audit_field_updates can be set to false to turn off field level auditing.

The audit tables are available for querying for manager level users. It might be necessary to do some un-hiding in the schema config tool.
The Format Data Objects option will format values that are foreign keys in related tables. 
In query results displays, recordids and codes are displayed inside of {}s.

**Comment by yvonneekanim** [comment]
A few issues I've noticed:
- Changes to the 'Collectors' field are not being audited. Other agent fields show up on the auditlogfield
- Changing the prefs to false do not stop auditing

**Comment by yvonneekanim** [comment]
Changes to Collectors is still not being audited. Is this expected behavior?

**Comment by maxxxxxdlp** [comment]
Few more possible auditing improvements:
#524 Log BatchEdit more efficiently
#501 Limit Duration before deleting auditing logs
#484 Log the change to auditing settings

And @timo11  also discussed some here: #249

We should consider all of them before the 6.8 release
