### ISSUE TITLE
Gratuitous spaces in lat/lngs can cause null pointer exceptions while Uploading

### ISSUE THREAD

**Issue by timo11** [specify/specify6#288]
When rows containing lat/lngs with spaces are uploaded, null pointer exceptions may occur.
"77° 9' W" is fine, but "77°  9' W" is not.

**Comment by timo11** [comment]
The database in the file shell_bug_288_test.sql in the Conversion Databases/Shell Museum directory produced this problem. Especially after the lat longs were processed with the geo-ref converter tool.

**Comment by yvonneekanim** [comment]
Lat long values with spaces can be uploaded via the workbench without errors. Converting the format does not hinder the upload.
