### ISSUE TITLE
Preparation Property query displays hidden fields

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#289]
I see two agent table links in the preparation properties table despite only text 1 being unhidden (object type in the image below)

![image](https://user-images.githubusercontent.com/12532430/56160566-1f336480-5f8d-11e9-88d5-699626935f28.png)

**Comment by timo11** [comment]
This is bug #287

**Comment by timo11** [comment]
fix for #287 fixes this

**Comment by tlammer** [comment]
this is not fixed in v6.7.02_internal_stop_the_insanity-2-ga6a2f55.  I am seeing the same thing in the National Shell Museum database

**Comment by timo11** [comment]
Yes. The fix for this problem has not been released.
