### ISSUE TITLE
If catalognumber increments and is required in the schema config, CO BE fails.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#298]
If Is Required is checked for catalognumber in the schema config, and catalog number has an incrementing formatter, collectionobject records can't be batch edited.
When apply is clicked, nothing happens, almost as if apply had never been clicked, except that it is disabled and can never be clicked again, until you close the warped BE WB.

**Comment by yvonneekanim** [comment]
Collection Object records with catalog numbers that increment and are required can be batch edited and saved
