### ISSUE TITLE
BE: Fields that were not edited are highlighted

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify6#3]
Whenever I make a change to a Locality Name field in a row in a batch of CO records, the Lat/Long fields are highlighted even if I don't make a change to them. Lat/long are also highlighted when I make changes to Geography fields or the CE #. This behavior may happen with other tables, but I have not discovered other cases yet.

**Comment by tlammer** [comment]
still happening for me

**Comment by tlammer** [comment]
actually, if i had edited the row previously then cancelled my changes, the lat and long fields were still marked as edited

**Comment by timo11** [comment]
I could only ever get this happen for lat/lng. Now I can't get it to happen anymore, in the demo db. Maybe it's fixed.

**Comment by tlammer** [comment]
lat long highlighting still happening for me in newly created db

**Comment by tlammer** [comment]
and, if I don't put a value in the locality name field of the row where lat and long were highlighted erroneously, I can't apply the changes

**Comment by timo11** [comment]
So, there's no locality data? And you edit what? And the empty lat/lng cells get highlighted?
