### ISSUE TITLE
Remove log entries older than a user specified max age

### ISSUE THREAD

**Issue by timo11** [specify/specify6#303]

**Comment by timo11** [comment]
Audit log items older than the user-specified AUDIT_LIFESPAN_MONTHS remote preference are deleted in a low priority background process when specify starts.

**Comment by timo11** [comment]
Testing hint: In a db known to have lots of log entries (pretty much any specify db that's more than a year old) run this query:

select count(*) from spauditlog where date_sub(curdate(), Interval 1 month) > timestampcreatedset 

Just to make sure there are some log entries > 1 month old.

Then set the maximum age preference to 1 month. Log out of Specify. Log back in. 
Run the query above again. It should return 0.

**Comment by yvonneekanim** [comment]
Spauditlog removes entries older than age specified in the database
