### ISSUE TITLE
BE: If I clear out the Locality information in a CO query, it won't apply changes

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#31]

**Comment by tlammer** [comment]
but if I put a value in the locality name field, it will save.  It is just if I clear it out that it has a problem

**Comment by timo11** [comment]
I don't have any problems clearing locaility info from cos, in embedded or non-embedded ce collections, with or without geo and details fields. 

What query? What db? What collection?

**Comment by tlammer** [comment]
Still getting this error.  May be related to a different error I found.  I'll report it in #34

**Comment by tlammer** [comment]
Still happening for me in Glob release

**Comment by timo11** [comment]
what query, what db? what collection? what fields cleared? what records?

**Comment by tlammer** [comment]
created database in this release.  removed Locality Name, latitude1, longitude1, Continent, Country State, County.

I was just about to check the issue on clearing geography information so that might be the actual issue.

But the same thing happened when there was only data in the locality name field but the same columns (all empty) were present.  When I only had locality name in the query, there was no problem clearing it out.
