### ISSUE TITLE
Geolocate results cannot be viewed.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#310]
The openstreetmaps tile server is rejecting specify's requests for tiles. So the map view in  the geolocate results window is blank.

**Comment by timo11** [comment]
Tile factory base url can now be set via the remote pref GEOLOCATE_TILE_FACTORY_URL.

for example:
https://a.tile.opentopomap.org (the default)
http://c.tile.stamen.com/watercolor/

Specify assumes the tile location is specified in z/x/y order, and that the server supports .png files.

see: https://wiki.openstreetmap.org/wiki/Tile_servers

**Comment by benanhalt** [comment]
e87ac1a adds the User-Agent header to requests which seems to stop openstreetmaps from rejecting the requests.
