### ISSUE TITLE
Cannot do a partial bulk loan return

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#311]
University of Michigan reported they have loans with up to 1000 sp loaned.  They sometimes only get back a couple hundred of the items at one time.  They would like to do a bulk return of the items but currently in specify, you can only do one at at time or all loaned items.  They would like to be able to scan a barcodes, paste the catalog numbers, or enter the catalog numbers to return a group in bulk

**Comment by norinespears** [comment]
Edinburgh would like this feature as well. Tim is working on adding this feature based on the following requirements:

1. Click Return Loan at bottom of the Loan form. 
2. Dialog pops up asking if user wants to enter items, choose items, or return all 
3. If user chooses enter items a dialog allowing themto either scan barcodes or type identifiers is presented
4. user can then enter or scan barcodes to return the loaned specimen/prep
5. If user chose to return all then all loaned items are returned and the prep is closed

Additional Requirements:
1. Specify checks the unique identifier against those on loan. If the ID is not found then a dialog will alert the user that x number of scanned items were not found in the loan. ***it would be great to also return the ones not found, but that may be an upgrade to this capability
2. Update all calculated fields based on the returned items

**Comment by yvonneekanim** [comment]
Is there a form for this? This is what I see when I click on 'return'
![loan return](https://user-images.githubusercontent.com/28809154/116283692-cc7f0c80-a751-11eb-9286-ccaf6cdb30d7.png)

**Comment by norinespears** [comment]
Is that inside the Loan form?

**Comment by timo11** [comment]
The 'return loan' button on the loan form is supposed to open this:
![Options](https://user-images.githubusercontent.com/2915306/116286040-6942a980-a754-11eb-90e0-680326c828bb.png)
Then for example this
![return](https://user-images.githubusercontent.com/2915306/116286180-88d9d200-a754-11eb-996c-2bbeddb9082f.png)
:
![ids](https://user-images.githubusercontent.com/2915306/116286087-72337b00-a754-11eb-9553-c1de4613b1da.png)
Then:

Did you click 'Return Preparation' on the loan prep form? It should like the shot below. Maybe there's something in the log files?

![returnprep](https://user-images.githubusercontent.com/2915306/116286593-03a2ed00-a755-11eb-804a-9a1c424b5aa7.png)

**Comment by yvonneekanim** [comment]
Just to reiterate what I said in the meeting. The loan form doesn't open when I click on it with the default forms that come with [this](https://github.com/specify/specify6/actions/runs/768408225) release. I replaced the common views file in that installation with what Theresa made for deaccessions and this time the Loan form opens as it should but when I click on the loan return prep button I get a blank form as in the screenshot. 
[error_sys.log](https://github.com/specify/specify6/files/6386735/error_sys.log)
[specify.log](https://github.com/specify/specify6/files/6386737/specify.log)

**Comment by timo11** [comment]
Can you send the forms you are using?

**Comment by timo11** [comment]
I guess this blank form thing is now #868.
