### ISSUE TITLE
Annotations for the Storage->AlternateStoragePreparations relationship are wrong.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#323]

**Comment by timo11** [comment]
It is not clear what the consequences of this problem were. 
Ben discovered it while investigating an issue in 7.

**Comment by benanhalt** [comment]
Here are my findings for future reference:

It causes the *specify_datamodel.xml* file to include the incorrect value `"alternateStoragePreparations"` for the `otherSideName` value for the `storage` field in the Preparation table definition. 

https://github.com/specify/specify6/blob/v6.7.02/config/specify_datamodel.xml#L3083

This prevents Specify 7 from constructing the reverse one-to-many relationship `preparations` from Storage to Preparation. The initially reported symptom was a server error triggered by the *Collection Object Storage* express related search which traverses that relationship.

**Comment by yvonneekanim** [comment]
How should this be tested?

**Comment by timo11** [comment]
If alternatestoragePreparation can be set,saved,edited, and queried in 6 it's probably good for 6
.
I am not sure how to see if it fixed the 7 issue.

**Comment by tlammer** [comment]
test doing batch edit on storage data to make sure that is working as well

**Comment by timo11** [comment]
AlternateStorage (like ChronosStratEnd) is not available in the WB. And not should not be editable in the BE - alternateStorage levles can be selected but the columns will be disabled.

**Comment by yvonneekanim** [comment]
Alternate storage can be queried, saved and edited. Fields are disabled for BE

**Comment by benanhalt** [comment]
Hmm. It seems the fix to the `specify_datamodel.xml` file itself didn't make it into the 6.7.04 release (see https://github.com/specify/specify6/blob/v.6.7.04_final/config/specify_datamodel.xml#L3083) but the underlying change to the annotations did.

It does appear to be in the development branch though, so it should go out in 6.8.
