### ISSUE TITLE
Rows with duplicated one-to-many data are removed even when 'Distinct' is not selected. 

### ISSUE THREAD

**Issue by timo11** [specify/specify6#326]
Reported by UMich as a result of a discrepancy between the results returned by Sp6 and 7 for a loan query that selected only the quantity and count of loaned items. Sp6 was automatically grouping records from the same loan with identical counts into a single result row.

This is a result of the fix for bugzilla bug 10227.

**Comment by yvonneekanim** [comment]
Query results now display quantity and count info for each loaned item

**Comment by yvonneekanim** [comment]
Query results now display quantity and count info for each loaned item
