### ISSUE TITLE
BE: If I copy latitude and longitude from one Loc to another, it creates a new locality

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#33]
If I copy the lat and long from one locality to another to make them match, it creates a new locality with all the same (apparent) information

**Comment by timo11** [comment]
Lat/Lngs are hopeless. Copying latitude from one loc to another does not mean the numeric lat/lng values match exactly.

**Comment by timo11** [comment]
but they can be less hopeless...

**Comment by timo11** [comment]
duplication should happen only for rare, mathematically uncooperative cases.
