### ISSUE TITLE
ExportForWebPortal takes forever or crashes for extremely large collections

### ISSUE THREAD

**Issue by timo11** [specify/specify6#332]
For example when exporting 1.4 million records for the KU ento pinned collection, the process gets slower and slower, then more often than not crashes, producing a "Portal could not be exported" error in the Exporter app.
KU ento pinned is the only collection known to cause this problem.

**Comment by yvonneekanim** [comment]
Successfully exported 1.4 million records from the KU Ento pinned collection in less than 15 minutes
