### ISSUE TITLE
QB PrepType field control lacks Prompt, Always, and Show checkboxes

### ISSUE THREAD

**Issue by timo11** [specify/specify6#338]
For "Table" picklists (I'm pretty sure PrepType is the only one) conditions can be entered, but because the field control represents a relationship, Prompt, Always, and Show are unavailable.

It's possible to click through the relationship and use PrepType.name (w/o the picklist control), so there is a workaround.

**Comment by yvonneekanim** [comment]
Show, Prompt and Always are available and work as expected when formatted Prep Type is added to a query.
