### ISSUE TITLE
Test 6704 Updater

### ISSUE THREAD

**Issue by beach53** [specify/specify6#341]

**Comment by timo11** [comment]
latest version still not work due to: 
java.io.FileNotFoundException: http://www.update-test.specifysoftware.org/updates.xml

**Comment by timo11** [comment]
This release should be able to access the test-update site:
https://github.com/specify/specify6/releases/tag/v6.7.04_testing_update_chk_b

**Comment by timo11** [comment]
How to set up specify to check a fake updates site:
1. Change the url for the UPDATE_PATH key in resources_en.properties. This changes the site for the update check in Specify's Help menu.
2. Change the updateDescriptorUrl property in 5-mac-full.install4j, 5-winlin-full.install4j, and 5-winlin-full-64.install4j in the packaging/ directory. This changes the site for the check at startup, for internal/pre-release builds.
