### ISSUE TITLE
Auto incrementing in created formats does not work for Accession Number

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#35]
Rancho Santa Ana and Sarah Schmits both reported (and testing confirmed) accession numbers formatted to auto increment are not doing so.
We created a format of yyyy-#### that is incrementing and set to restart with each year but it is creating the same number with each save (2018-0001).  We tried #### incrementing as well and it does the same thing (0001 over and over again).
Auto- incrementing is on in the databases in question (a copy of RSA and a created database)
tested in the external 6.6.06 and "heap" internal release

**Comment by timo11** [comment]
After the "fix": When you change the accession number format in the schema config, the database tables that control autoincrementing for accession are updated if necessary. Everything should be fine for single discipline dbs. 
However, accession is scoped to division, and if there are multiple disciplines in a division, the schema configuralyzer will allow each discipline to have a different accession format. The autoincrementing setup will match the last-edited discipline, but if other disciplines have different formats, there will be problems.
