### ISSUE TITLE
Update User Creation code

### ISSUE THREAD

**Issue by timo11** [specify/specify6#351]
The statement specify uses to create mysql users is no longer supported. An earlier fix (see #182) uses the new user creation method in case mysql8 is running. The outdated user creation statement seems to work for mysql7, but is not documented, so sp should also use the new method when mysql 7 is running. 
Hopefully this will fix #352

**Comment by timo11** [comment]
Test by running the DB Setup Wizard. The Master user setup is what changed by this fix, but you won't know if the master is user is working properly until the Institution creation succeeds.
Try creating an entirely new master user (with a new name), then run the wizard using the same name. If both of these attempts work, you should run the wiz yet again using a pre-existing master user if there is one.

Please be sure to test with mysql 5.7, and 5.6 or earlier.

**Comment by yvonneekanim** [comment]
Tested with mysql 5.6 & 5.7. I was able to create databases with new and pre-existing master users in both versions.
