### ISSUE TITLE
DB setup Wizard fails on Macs

### ISSUE THREAD

**Issue by timo11** [specify/specify6#352]
Even for non tlammer users.
The wizards either hangs or fails (with "The institution could not be created") when 'Create Institution' is pressed.
Exception logs indicate that specify is unable to log into the just-created db with the Master user created (or modified) in step 2 of the wizard.

**Comment by timo11** [comment]
see #351

**Comment by timo11** [comment]
#351 is fixed so so is this bug.

**Comment by yvonneekanim** [comment]
Tomislav  Urban just reported this issue. He's running windows on MySQl 5.5. He doesn't get any exceptions

**Comment by timo11** [comment]
Ask him to send his log file(s).

**Comment by yvonneekanim** [comment]
Would the log files be in MySQL?

**Comment by timo11** [comment]
No. The specify log files. I don't know where they would be on Windows machines.

**Comment by yvonneekanim** [comment]
@tlammer do you know where Specify log files would be on Windows machines?

**Comment by tlammer** [comment]
C:\Users\tlammer\Specify but with the name you are logged into the computer with instead of tlammer

**Comment by FedorSteeman** [comment]
I'm having this issue right now with the latest stable version of specify. Where are the log files in the Specify folder?

**Comment by FedorSteeman** [comment]
For reference: https://www.sustain.specifysoftware.org/forums/topic/specify-setup-wizard-cant-create-institution/

**Comment by FedorSteeman** [comment]
OK. On Windows, logs are written by MariaDB (and MySQL probably too) in the built-in Event Viewer under "Windows Logs"->"Application". I can see some access denied messages, so that may be the root cause. Will keep on digging and keep you posted.

**Comment by tlammer** [comment]
Fedor, if you have more issues or questions, let me know at support@specifysoftware.org.

**Comment by FedorSteeman** [comment]
Still looking for those logs...
