### ISSUE TITLE
BasicSQLUtils.getCount() methods need to return Long Integers rather than Integers

### ISSUE THREAD

**Issue by timo11** [specify/specify6#356]
Stats sending for the florida iz db is failing for the "total number of preparations" stat because the result is too large to be represented by standard Integers. 
Calls to getCount() are likely failing in other situations for large databases.

**Comment by timo11** [comment]
I'm not sure we need to provide a general fix for this problem. The maximum value for a java integer is over 3,000,000,000. Counts greater than this value are probably very rare. Florida iz is exceeding it because there are 300k preparation records with count = 9999, which may not be actual specimen counts.

**Comment by timo11** [comment]
As of commit 1fa9b8f:
a) the stats sending problem is fixed
b) the getCountAsInt() methods, when a count needs to be truncated to fit in an int, log a warning and send an exception to the sp6 exception server
c) Exceptions will occur when the result of getCount() is assigned to an int or Integer and the result is too large for an integer.

**Comment by beach53** [comment]
Tim to think of the best way to test this.

**Comment by maxxxxxdlp** [comment]
Is there a need to test this or is it fixed for sure?
