### ISSUE TITLE
Sporadic problems deleting 1-many -related items.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#357]
Florida IZ and Fish have run into problems deleting OtherIdentifer records on the CollectionObject form. Saving CollectionObject results in the "The data in the form has been edited by someone else..." msg. And the deletes cannot be saved. Unless the CO is saved after one of the CO's OtherIdentifer records is edited, or perhaps anything on the form is edited.
The problem is sporadic. Some OtherIdentifiers can be deleted some cannot. All attempts to make undeletable  OI's deletable by making them look like deletable OI's by tinkering with system field values have failed.

**Comment by timo11** [comment]
This bug is fixed on the develop (6.8.00) branch.

**Comment by tlammer** [comment]
tested in florida's database.  could replicate in 6.7.04 but could not replicate in 6.8 using the exact same steps.  also did other testing in other databases.
