### ISSUE TITLE
Remove or improve msg dlg when "special message" server is unavailable.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#362]
When specify fails to connect to the "Special Message" an error dialog displays with the msg "Specify was unable to connect to the Internet.\nThe Internet may not be available." We should make a better msg, or better yet since we never use the msg server, log the error silently. Or maybe stop checking for msgs on the server altogether.

**Comment by timo11** [comment]
The dlg no longer appears. The error is logged but not reported to users.

**Comment by yvonneekanim** [comment]
How should this be tested?
