### ISSUE TITLE
Add Ukrainian and Russian resource files to 6.8

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#371]

**Comment by timo11** [comment]
The latest ukrainian translations have been merged from the l10n branch into develop (along with all other l10n changes).

**Comment by maxxxxxdlp** [comment]
> Also, when the user has several Specify installations, or several databases, and changes the language in one of those, all other instances do also have their language changed
> 
> ![Screenshot (69)](https://user-images.githubusercontent.com/40512816/72087488-272af580-32ce-11ea-8a99-44518227b4fe.png)

I referenced a bug with languages [here](https://github.com/specify/specify6/issues/441)

Also, If one Specify installation does support Ukrainian and Russian, those languages are available to chose from even in the version that is not yet supporting it (developer branch)
![Screenshot (70)](https://user-images.githubusercontent.com/40512816/72088682-49257780-32d0-11ea-9838-cdfedb93acea.png)

But here is the way the Developer's branch Specify language menu looks like when not affected by another installation
![Screenshot (32)](https://user-images.githubusercontent.com/40512816/72088681-49257780-32d0-11ea-8426-8ade809f2bae.png)

So **even though the resource files are now in the Developer branch, they are still not visible in the language settings menu**
