### ISSUE TITLE
Exporter App unable to build/update

### ISSUE THREAD

**Issue by timo11** [specify/specify6#373]
The exporter is failing to update caches for the KU ento db.
It freezes up and/or displays a 'the cache could not be updated' error msg.
Seems to be related to memory consumption during the check for duplicate RecIds.

**Comment by timo11** [comment]
A good way to test this fix would be to find a db with existing mappings and, in the schema mapping tool in the Sp6 app, run the preview for existing mappings to see if the duplicate message occurs incorrectly, then changing the mappings by removing the determination.iscurrent condition or adding preptype or some other field from a one-to-many table known to actually have many values for some cos, and see if the duplicate message occurs when it's supposed to.

**Comment by yvonneekanim** [comment]
Tested in Ku ento. Error message indicates that there are duplicate record IDs
