### ISSUE TITLE
Thumbnail Not Found for image attachments

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#380]
"Thumbnail Not Found" for any image attachment in _Attachments Tab > Show All Atachments_.
Tested with _.png_ images
Files are named like this: _Screenshot from 2019-11-06 16-55-47.png_

![Screenshot from 2019-11-04 12-18-14](https://user-images.githubusercontent.com/40512816/68345921-4d5acc00-00b8-11ea-98d3-51e8572161db.png)

**Comment by maxxxxxdlp** [comment]
No issues with **.jpg** images in Specify 6.8.00.
No thumbnails for  **.png**.
**.ppm, .bmp, .pgm** do not have thumbnail either. They are not even shown on the **Show All Images** page.

**Comment by maxxxxxdlp** [comment]
Tested on Ubuntu 18.04.3 LTS

**Comment by maxxxxxdlp** [comment]
On macOS 10.15, **.png** images are shown like this:

<img width="530" alt="Screen Shot 2019-11-15 at 5 31 43 PM" src="https://user-images.githubusercontent.com/40512816/68982741-d74c1880-07cd-11ea-9c73-2fb58d86c630.png">

**Comment by timo11** [comment]
This problem probably only occurs for File Attachment servers.
Pngs and bmps should definitely work. But less common formats may not work on all paltforms. We may need to improve the fix.

**Comment by maxxxxxdlp** [comment]
FIxed on macOS and Linux
**.jpeg**, **.png** and **.gif** files do have thumbnails now
Consider adding support for **.bmp** and **.svg**
