### ISSUE TITLE
File Attachment Form View Redundant Scrollbars

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#381]
If Attacments window is in a form view, after adding an attachment, scroll bars apear that obstruct access to UI controls.

![Screenshot from 2019-11-04 12-29-49](https://user-images.githubusercontent.com/40512816/68346022-96128500-00b8-11ea-897c-534f35d847a0.png)

**Comment by maxxxxxdlp** [comment]
Tested on Ubuntu 18.04.3 LTS

**Comment by maxxxxxdlp** [comment]
Same issue in macOS 10.15 with Specify 6.8
<img width="616" alt="Screen Shot 2019-11-15 at 5 27 40 PM" src="https://user-images.githubusercontent.com/40512816/68982605-4a08c400-07cd-11ea-8275-24cdd022c811.png">

**Comment by beach53** [comment]
See #430

**Comment by maxxxxxdlp** [comment]
![Screenshot from 2019-12-12 16-59-26](https://user-images.githubusercontent.com/40512816/70755913-c4f7c880-1d00-11ea-9191-c288c513ba56.png)
Still happening

**Comment by timo11** [comment]
Window is resized to make room for the Re-order buttons which appear when grid views contain orderable objects. The window may twitch when resized. If it doesn't remove the scroll bars, users will just have to resize the window themselves.

**Comment by timo11** [comment]
Window is resized to make room for the Re-order buttons which appear when grid views contain orderable objects. The window may twitch when resized. If it doesn't remove the scroll bars, users will just have to resize the window themselves.

**Comment by maxxxxxdlp** [comment]
<img width="1440" alt="Screen Shot 2019-12-13 at 4 27 25 PM" src="https://user-images.githubusercontent.com/40512816/70939710-6be4a900-200e-11ea-97d1-ec26272ce75e.png">
Still happening on my macbook. Will try it on mac mini later and report back
