### ISSUE TITLE
Add morphotype table

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#388]
For Wyoming paleobot
Add a new table to document morphotype data.  I'll submit the required fields after we get a list from them.  It should have a many to one relationship with Collection Object

**Comment by tlammer** [comment]
This should be a blocker for 6.8 #388

**Comment by tlammer** [comment]
[Morphotype_Designation.xlsx](https://github.com/specify/specify6/files/4183421/Morphotype_Designation.xlsx)

**Comment by tlammer** [comment]
There are 58 text fields, 1 agent field, 82 yes/no fields

**Comment by timo11** [comment]
I also included a partial precision date field, a remarks field, 18 floats and 2 integers, what with it being an attribute table and all.

**Comment by timo11** [comment]
There are now 20 float fields and 5 Integer fields.
Text1-26 are varchar(128)
Text27-48 are varchar(256)
Text49-58 are text(65535) (not 65536 in accordance with specify6 tradition)
Remarks is text(65535)
