### ISSUE TITLE
If there is an issue with the data in the database already, when changes are applied the screen goes to the WB upload screen

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#39]
If there is an issue with the data in the batch set, such as number of digits in the coords or missing data, there is no warning until you try to apply changes, then it takes you to the Workbench upload screen (split screen like in the image attached), but the bottom panel is off of the screen and there is no scroll bar, so you don't know what is going on unless you Macguyver a way to see it.
I did this in a Rancho Santa Ana database.  I ran the Standard Label Query, added Barcode to the query and got the attached images.  If you want to reduce the wait, you can make barcode contain 0031.  It won't have all of the messages, but it will have the coord length issues.
![be2](https://user-images.githubusercontent.com/12532430/35700051-7ea1191a-0757-11e8-9e1e-f2cb549ca330.png)
![be1](https://user-images.githubusercontent.com/12532430/35700052-7eb7c0a2-0757-11e8-8f12-4f80ba38e38e.png)

**Comment by timo11** [comment]
fixed by this here commit: https://github.com/specify/specify6/commit/0161e1bee759565d1a4628c90a047e1d4ab6a53f#diff-25d902c24283ab8cfbac54dfa101ad31

**Comment by garrettgirard** [comment]
Using the same database, same query, and same dataset, I was not taken to the WB upload screen following application of changes.
