### ISSUE TITLE
No error messages when name taken

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#410]
If user chosen a value for a requireed field, that has already been taken and pressed "OK" to submit the changes, the window closes (expected behaviour) and reopens itself back, with required field being empty and no error messages.

I would assume that this is an expected behaviour in case of name beign taken, if so, there should be at least some kind of alert or error message notifying user of what have just happened

Here is an example with Data Set Properties window

Here is the form (notice on the left, the name is taken)

![Screenshot from 2019-11-20 08-46-16](https://user-images.githubusercontent.com/40512816/69248725-66f91a80-0b72-11ea-9d2a-138b254405a9.png)

After clicking "OK", window is displayed again, without a notification or an error

![Screenshot from 2019-11-20 08-46-28](https://user-images.githubusercontent.com/40512816/69248726-66f91a80-0b72-11ea-963e-4cc14062f042.png)

Same thing happens with some other required fields arround Specify

**Comment by timo11** [comment]
An error dlg pops up in addition to the status bar msg. 
The msg was changed (in resources_en.properties) to 'The name '%s' is assigned to another data set.'.

**Comment by maxxxxxdlp** [comment]
<img width="599" alt="Screen Shot 2019-12-19 at 11 51 31 AM" src="https://user-images.githubusercontent.com/40512816/71196819-eb17ee00-2255-11ea-8627-88fd948674c9.png">
Fixed

**Comment by maxxxxxdlp** [comment]
Even though the error message shows one time if the user goes ahead and fills in the same Data Set name again, Specify allows him to use the same name

![Screenshot from 2020-02-06 10-45-40](https://user-images.githubusercontent.com/40512816/73958649-d65aec80-48cd-11ea-8c9b-5969cb2c4bf4.png)
