### ISSUE TITLE
Can not change attachments permission

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#414]
There is no way to remove user's permission to see and import attachments.

Here is an example of a user that has no permissions at all, yet is still able to see all the attachments

<img width="1440" alt="Screen Shot 2019-11-20 at 10 53 12 AM" src="https://user-images.githubusercontent.com/40512816/69259682-3ae69500-0b84-11ea-89ea-c75f28545df5.png">
<img width="1440" alt="Screen Shot 2019-11-20 at 10 54 32 AM" src="https://user-images.githubusercontent.com/40512816/69259683-3b7f2b80-0b84-11ea-9f59-1a1ddaa69095.png">

**Comment by timo11** [comment]
If security is enabled for a db, when I remove write permissions to the collectionobjectattachment table for a group, users in the group cannot import attachments.

**Comment by timo11** [comment]
The attachments task is now available on the Tools page. When it is disabled, the task is removed from the UI.

HOWEVER, the attachments task does not seem to take table permissions into account. If read permission is denied for collectionobjectattachment, collectionobject attachments are still shown in the attachments task. Maybe another bug should be created for this.

**Comment by timo11** [comment]
Removing write permission on an [ObjectType]Attachment table makes it impossible to attach to [ObjectType] records in the form system, but if the Attachments Tool is enabled it is still possible to import [ObjectType] attachments.

Removing read permission on [ObjectType] attachment tables hides attachments in the form system, but only in View Mode. When Edit mode is activated, attachments are displayed, regardless of Read permissions.

So, as of commit 2a3e13f,  it seems to be possible to prevent users from adding attachments by disabling the attachments tool and removing write permission. However it seems impossible to hide attachments, except, possibly, by removinf attachments subforms from user type forms.

I have not looked attachment permissions in the workbench.
