### ISSUE TITLE
Exporter App's GetSQL for IPT function doesn't handle partial dates

### ISSUE THREAD

**Issue by timo11** [specify/specify6#42]
People who query exporter cache directly when populating IPT may have issues with partial dates.
The 'Show SQL' button should produce SQL that will correctly retrieve partial dates for IPT

**Comment by garrettgirard** [comment]
How exactly should I test this?

**Comment by timo11** [comment]
if you run the exporter and click Show SQL, for an up-to-date mapping that includes collectingevent.startdate, copy the sql and run the statement in mysql, the results should a) not blow up and b) display partial startdates as 1984 and 1984-12.
Andy is going to use test the SQL in IPT.

**Comment by tlammer** [comment]
Should I have to select the database as default?  It will not work unless i select a default schema in mysql

**Comment by timo11** [comment]
yes. db has to be selected.

**Comment by timo11** [comment]
Andy verified the fix in IPT:

After replacing the database connection code that Tim developed below in the IPT instance for my collection it appears as if this has resolved the partial date problem.  See DWCKUI occurrence file downloaded from IPT in Andy directory on Specify 6 (tried attaching but too big).  Look at row 11898 and 11899 (amongst others) and column W, X, Y and Z.
