### ISSUE TITLE
Settings Tab bar is too wide to fit on the screen

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#421]
In Specify 6.8, the taskbar is to wide to fit on the screen entirely. The visual bug happens when the Russian language is selected, but potentially can happen with every language, since each language has words of different lengh. Also there is an ability for user to resize the Settings window to make settings taskbar items be cutted on overflow too

Consider adding scrollbar to Settings menu taskbar in case of content being wider that the screen/window

![Screenshot from 2019-11-22 14-46-04](https://user-images.githubusercontent.com/40512816/69459332-2696c980-0d37-11ea-8593-54527c5b1f6a.png)

**Comment by beach53** [comment]
Tim to try to add arrows to scroll

**Comment by timo11** [comment]
The preferences tool bar is just an extremely customized JPanel extension, and there are no built-in scrolling solutions available, besides adding a standard scroll bar to the toolbar, which was kind of weird.

As of b2aca04 scroll bar will now appear at the bottom of the form when the preference buttons can't fit on the tool bar.
