### ISSUE TITLE
Add a label for "Remarks" field when editing Tree Properties

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#433]
Add a label for "Remarks" field, when editing the properties of any tree in Specify

<img width="796" alt="Screen Shot 2019-11-29 at 2 09 27 PM" src="https://user-images.githubusercontent.com/40512816/69888643-9286ae00-12b2-11ea-8c49-cbe66475d7de.png">
<img width="1440" alt="Screen Shot 2019-11-29 at 2 09 14 PM" src="https://user-images.githubusercontent.com/40512816/69888644-9286ae00-12b2-11ea-897c-d781e1767185.png">
<img width="796" alt="Screen Shot 2019-11-29 at 2 08 45 PM" src="https://user-images.githubusercontent.com/40512816/69888682-bcd86b80-12b2-11ea-887a-ac02fb5d9d09.png">

**Comment by maxxxxxdlp** [comment]
Note that the label is present when changing properties for any of the levels of the tree 

<img width="1440" alt="Screen Shot 2019-11-29 at 2 18 35 PM" src="https://user-images.githubusercontent.com/40512816/69888752-248eb680-12b3-11ea-81f6-9290db9246b9.png">

**Comment by tlammer** [comment]
Code to replace the NewtreeDefDataEntry viewdef in the global.views file starting at line 2658
        <viewdef
            type="form"
            name="NewTreeDefDataEntry"
            class="edu.ku.brc.specify.datamodel.TreeDefIface"
            gettable="edu.ku.brc.af.ui.forms.DataGetterForObj"
            settable="edu.ku.brc.af.ui.forms.DataSetterForObj">
            <desc><![CDATA[New Tree Definition Data Entry Form]]></desc>
            
            <columnDef>p,2px,p:g(2),p</columnDef>
            <rowDef auto="true" cell="p" sep="2px"/>
            
            <rows>
                <row>
                    <cell type="label" labelfor="1" label="Name"/>
                    <cell type="field" id="1" name="name" uitype="text" isrequired="true"/> 
                </row>
                <row>
                    <cell type="label" labelfor="2" label="Full Name Direction"/>
                    <cell type="field" id="2" name="fullNameDirection" uitype="combobox" ignore="true"/>
                </row>
                <row>
                    <cell type="label" labelfor="3" label="Remarks"/>
                    <cell type="field" id="3" name="remarks" uitype="textareabrief" rows="2"/>
                </row>
            </rows>
        </viewdef>
