### ISSUE TITLE
Empty Error Window if user declines to update schema

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#437]
If the user tries to log into the database that is not updated to the newer version, he gets a message asking him whether to update the database. If the user presses "Cancel" he gets an empty error message with a title of "An issue of concern", which will close itself in about a second

![Screenshot from 2019-12-02 09-00-55](https://user-images.githubusercontent.com/40512816/69969700-8a14ba00-14e2-11ea-9ee2-81e5171cb5ed.png)
![Screenshot from 2019-12-02 09-01-08](https://user-images.githubusercontent.com/40512816/69969701-8a14ba00-14e2-11ea-88cf-756e598e64fc.png)
![Screenshot from 2019-12-02 09-01-47](https://user-images.githubusercontent.com/40512816/69969703-8a14ba00-14e2-11ea-9c36-15d47f791d15.png)
![Screenshot from 2019-12-02 09-01-15](https://user-images.githubusercontent.com/40512816/69969702-8a14ba00-14e2-11ea-9fa3-4cc3f9787372.png)
./Specify4GB 
09:01:32 DEBUG brc.specify.Specify$53:3384 - Checking for update....
09:01:32 DEBUG brc.specify.Specify:249 - StartUp...
09:01:32 DEBUG brc.util.FileCache:353 - Loading old cache mapping data from longTerm.Cache
09:01:32  WARN brc.util.FileCache:413 - Unable to locate old cache mapping file.  Building cache... 199 / 0
09:01:32 DEBUG brc.util.FileCache:516 - Cache Size: 199 / 0
09:01:32 DEBUG brc.util.FileCache:353 - Loading old cache mapping data from forms.Cache
09:01:32 DEBUG brc.util.FileCache:516 - Cache Size: 0 / 0
09:01:36 DEBUG ui.db.PropertiesPickListAdapter:292 - Saving PickList
09:01:36 DEBUG ui.db.PropertiesPickListAdapter:296 - [login.databases][specify_6_7_0_4,specify_6_8_00_6]
09:01:36 DEBUG ui.db.PropertiesPickListAdapter:308 - [login.databases_selected][specify_6_7_0_4]
09:01:36 DEBUG ui.db.PropertiesPickListAdapter:292 - Saving PickList
09:01:36 DEBUG ui.db.PropertiesPickListAdapter:296 - [login.servers][localhost]
09:01:36 DEBUG ui.db.PropertiesPickListAdapter:308 - [login.servers_selected][localhost]
09:01:36 DEBUG brc.helpers.Encryption:265 - Error decrypting password.
09:01:41 DEBUG ui.db.PropertiesPickListAdapter:292 - Saving PickList
09:01:41 DEBUG ui.db.PropertiesPickListAdapter:296 - [login.databases][specify_6_7_0_4,specify_6_8_00_6]
09:01:41 DEBUG ui.db.PropertiesPickListAdapter:308 - [login.databases_selected][specify_6_7_0_4]
09:01:41 DEBUG ui.db.PropertiesPickListAdapter:292 - Saving PickList
09:01:41 DEBUG ui.db.PropertiesPickListAdapter:296 - [login.servers][localhost]
09:01:41 DEBUG ui.db.PropertiesPickListAdapter:308 - [login.servers_selected][localhost]
09:01:41 DEBUG brc.ui.UIHelper:1640 - try login
09:01:41 DEBUG specify.module.DbLoginCallbackHandler:89 - handle
09:01:41 ERROR ui.db.DatabaseLoginPanel$17:1352 - com.install4j.api.launcher.SplashScreen$ConnectionException: no splash screen available
09:01:43 DEBUG specify.dbsupport.SpecifySchemaUpdateService:317 - appVerNumArg: [6.8.00] dbVersion from XML[2.7] appVersion[6.7.04] schemaVersion[2.6]  spverId[1]  recVerNum[1] 
09:01:43 DEBUG specify.dbsupport.SpecifySchemaUpdateService:5184 - App - Prev[6.7.04] New[6.8.00]
09:01:43 DEBUG specify.dbsupport.SpecifySchemaUpdateService:5189 - App - Prev[6704] New[6800]
09:01:43 DEBUG specify.dbsupport.SpecifySchemaUpdateService:5184 - App - Prev[2.6] New[2.7]
09:01:43 DEBUG specify.dbsupport.SpecifySchemaUpdateService:5189 - App - Prev[26] New[27]
09:01:45 ERROR brc.specify.Specify:2252 - java.lang.RuntimeException: No context has been set.
09:01:45  INFO brc.dbsupport.HibernateUtil:198 - Using database [jdbc:mysql://localhost:3306/specify_6_7_0_4?characterEncoding=UTF-8&autoReconnect=true]
09:01:47  INFO brc.specify.Specify:2260 - Application shutdown
Warning: Could not get charToByteConverterClass!
09:01:47  INFO brc.specify.Specify:2281 - Successfully saved long term cache mapping
09:01:47  INFO brc.specify.Specify:2289 - Clearing the short term cache
09:01:47  INFO brc.specify.Specify:2296 - Successfully saved forms cache mapping
09:01:47 ERROR brc.ui.UIRegistry:1187 - The application will now exit.

**Comment by beach53** [comment]
Tim to take a look

**Comment by maxxxxxdlp** [comment]
Present in both Specify 6.7.04 and 6.8
Empty error window closes itself automaticly along with the main specify window after few seconds

**Comment by maxxxxxdlp** [comment]
Also happens in #457

**Comment by timo11** [comment]
The empty window should no longer occur as result of schema update declines or errors. 
If handled errors occur during the schema update they are displayed to the user before the app exits, and they are logged.

**Comment by timo11** [comment]
The fail described in #457 should no longer occur because it happened within the schema update module. But there are probably other situations where blank windows occur when Specify shuts itself down.

**Comment by maxxxxxdlp** [comment]
Instead of a blank window, there is a proper error message
![Screenshot from 2019-12-12 15-51-17](https://user-images.githubusercontent.com/40512816/70752563-7f370200-1cf8-11ea-868d-1ca0443a6a9d.png)
