### ISSUE TITLE
No file extension when Exporting in DataExporter

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#445]
If the user clicks on `Export` in DataExporter, the resultiong window does not offer him to save the file with `.zip extension`
<img width="662" alt="Screen Shot 2019-12-04 at 9 31 36 AM" src="https://user-images.githubusercontent.com/40512816/70156017-e0b3fc80-1678-11ea-9221-e463bcc1dcaa.png">

Also, when the user clicks on `Export for Web Portal`, the resulting window has `.zip` files are marked as disabled, even though the output file is in `.zip` format
<img width="662" alt="Screen Shot 2019-12-04 at 9 16 47 AM" src="https://user-images.githubusercontent.com/40512816/70154842-d264e100-1676-11ea-8bee-8e5834eace9e.png">

**Comment by maxxxxxdlp** [comment]
As far as I understood, the file format for regular `Export` is CSV, so the user should get a choise of exporting as `.CSV` and maybe also `.TXT`, `.XLS` and `.XLSX`

**Comment by timo11** [comment]
csv extension is added when necessary. 
Also fixed saving of prefs for remembering directories saved to and other things.
