### ISSUE TITLE
Floating task bar behaves badly

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#449]
Floating task bar works perfectly well, except when there is another window open, behind it, in which case I can move the taskbar, but can not close it, click on the buttons or search field inside or even close it

<img width="1440" alt="Screen Shot 2019-12-05 at 4 31 26 PM" src="https://user-images.githubusercontent.com/40512816/70279861-e98df680-177c-11ea-897d-e01570d36b91.png">

Resumes to work perfectly well, when I close the Window behind it
<img width="1440" alt="Screen Shot 2019-12-05 at 4 33 25 PM" src="https://user-images.githubusercontent.com/40512816/70279893-f7437c00-177c-11ea-9e59-ff4a72ab231c.png">

Reproducable only on macOS

**Comment by maxxxxxdlp** [comment]
On linux task bar is always behind the other windows. Making it be focused/lose focus does not help,
even thought it is interactable

Same issue when those windows are pulled to another screen

![Screenshot from 2019-12-05 16-37-07](https://user-images.githubusercontent.com/40512816/70280284-b5670580-177d-11ea-8a77-c22bdca34b9b.png)

**Comment by maxxxxxdlp** [comment]
Not fixed on macOS
<img width="1440" alt="Screen Shot 2019-12-19 at 11 47 44 AM" src="https://user-images.githubusercontent.com/40512816/71196411-a2f8cb80-2255-11ea-9f00-084be271d87c.png">
Is this it's expected behaviour?

**Comment by maxxxxxdlp** [comment]
Not fixed on Linux
![Screenshot from 2019-12-19 11-49-24](https://user-images.githubusercontent.com/40512816/71196443-b6a43200-2255-11ea-9666-90cf92d35c68.png)

**Comment by timo11** [comment]
this fix is not in v6.8.00_testing_20191219.

**Comment by maxxxxxdlp** [comment]
Fixed by removing task bar's ability to float
