### ISSUE TITLE
Allow uncataloged items in loans and gifts

### ISSUE THREAD

**Issue by timo11** [specify/specify6#45]

**Comment by timo11** [comment]
The dlg for entering catalog numbers now has an 'add uncataloged' btn. 
Kind of awkward but seems to work.
May require modifications to invoices.

**Comment by timo11** [comment]
Maybe should check how seven handles uncataloged transaction items.

**Comment by timo11** [comment]
the return button doesn't work for uncataloged items. They need to be returned one-by-one the hard way.

**Comment by tlammer** [comment]
We should discuss how this works. You can't add an uncataloged item after opening the loan and if you add an uncataloged item at the beginning, you have to add cataloged items one at a time.

**Comment by timo11** [comment]
why can't you add uncataloged items after opening? Click the loan items '+',   choose 'Enter Catalog Numbers' (which should be changed) if there are co recordsets, then choose uncataloged.
To add multiple cataloged items, Click '+' and choose enter catalog numbers and enter catalog numbers?

**Comment by tlammer** [comment]
I was looking for a button on the form.  sorry, but still should discuss how the button works on the pop up.

**Comment by timo11** [comment]
In initial dlg that appears if recordsets or info requests exist:

'... source of Collection Objects' was changed to '... source of Transaction Items'
'Enter Catalog Numbers' was changed to 'Enter Items'

In 'Enter Items' dlg:

'Uncataloged' Btn is disabled when catalog numbers have been entered.

**Comment by yvonneekanim** [comment]
Verified. Uncataloged items allowed in gift and loans
