### ISSUE TITLE
Simple Search doesn't search on Sample Number in Preparation

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#456]
If we are going to make interactions work on sample number in preps, we should make the simple search be able to search on it as well.  Currently, it will display the field (if unhidden) but cannot search on it.

**Comment by beach53** [comment]
This requires that samplenumber be indexed. which requires a schema update. So seems like we should include the change in 6.8.00.

**Comment by yvonneekanim** [comment]
Sample number can be searched on when added to simple search config
