### ISSUE TITLE
problems importing geocoorddetail.maxuncertaintyest

### ISSUE THREAD

**Issue by timo11** [specify/specify6#46]
Field is blank when imported, from xls or csv.

**Comment by timo11** [comment]
maxuncertaintyest field name was changed to uncertaintyEst in specify_workbench_datamodel in an earlier commit.

**Comment by tlammer** [comment]
You have to import a spreadsheet with the max uncertainty est and max uncertainty est unit data in it.  Creating a spreadsheet within the WorkBench worked before.  This is testing importing the data

**Comment by tlammer** [comment]
reappeared

**Comment by timo11** [comment]
spreadsheet that causes the problem?

**Comment by tlammer** [comment]
exported the dataset into the files for programmers directory.  I got the original file from Delaware\Malacology and used the one named something like spreadsheet for Theresa and mapped it by hand

**Comment by tlammer** [comment]
was able to import a spreadsheet and map to max uncertainty est.  Data imported and uploaded correctly.

**Comment by tlammer** [comment]
reopened

**Comment by timo11** [comment]
For the record: 
I was able to reproduce this bug while logged into the mammal collection in the latest demo db.
I then used the workbench schema configurer to change the caption for maxUncertaintyEst from "Max Uncertainty Est" to "error radius". This eliminated the problem.
How can this be happening?

**Comment by tlammer** [comment]
insufficient offerings to the Specify Shaman

**Comment by timo11** [comment]
also need to make sure geolocate updates m.u.e.

**Comment by timo11** [comment]
also needs to be tested in  several dbs with several spreadsheets and several batch-edits by several people several times for several days.

**Comment by tlammer** [comment]
nope

**Comment by tlammer** [comment]
could upload the max uncertainty est from an imported spreadsheet and a data set created in WorkBench
