### ISSUE TITLE
Not able to query Audit Log table

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#461]
I am not able to query `SpAudit Log` table, because no columns are available for query
<img width="1552" alt="Screen Shot 2019-12-11 at 9 58 32 AM" src="https://user-images.githubusercontent.com/40512816/70637441-dce62400-1bfc-11ea-9b9b-4219b889c0f9.png">

No auditing table in Schema Configuration
<img width="975" alt="Screen Shot 2019-12-11 at 9 58 24 AM" src="https://user-images.githubusercontent.com/40512816/70637442-dce62400-1bfc-11ea-80f9-1124d2d5880f.png">

I am using the newest beta of Specify 6.8 and a fresh database created in this version

**Comment by maxxxxxdlp** [comment]
Same issue on linux
![Screenshot from 2019-12-11 09-55-37](https://user-images.githubusercontent.com/40512816/70637613-20d92900-1bfd-11ea-9884-5eb0e245e4d1.png)
I am using the newest beta of Specify 6.8 with a freshly created database

**Comment by maxxxxxdlp** [comment]
Tested in the newest beta release of Specify 6.8 with a freshly created Herpetology database

**Comment by timo11** [comment]
This can be fixed in existing dbs with this sql statement:

update splocalecontaineritem ci inner join splocalecontainer c on c.SpLocaleContainerID = ci.SpLocaleContainerID set ci.ishidden = false where c.name like 'spauditlog%';

**Comment by timo11** [comment]
For this fix to take effect, dbs already at schemaversion 2.7 will need to have spversion.schemaversion set to '2.6' to force a schema update. A schema update can also be forced by adding/setting the local pref UPDATE_SCHEMA to true.

**Comment by maxxxxxdlp** [comment]
<img width="1440" alt="Screen Shot 2019-12-19 at 11 29 13 AM" src="https://user-images.githubusercontent.com/40512816/71195301-42688f00-2253-11ea-9933-78f90eea05f5.png">
Still happening in the Specify 6.8 (12_19_2019) with freshly created database.

Though, this issue can be solved by executing the line you propsed:

    update splocalecontaineritem ci inner join splocalecontainer c on c.SpLocaleContainerID = 
    ci.SpLocaleContainerID set ci.ishidden = false where c.name like 'spauditlog%';

**Comment by maxxxxxdlp** [comment]
I found `"Remote Prefs"`. Where can I find `"Local Prefs"` to force a schema update?
<img width="1076" alt="Screen Shot 2019-12-19 at 11 43 30 AM" src="https://user-images.githubusercontent.com/40512816/71196093-e868c900-2254-11ea-874e-8f476473c6a9.png">

**Comment by timo11** [comment]
ctrl-dblclick the database name. You might have to set the pref to true after each update.

**Comment by maxxxxxdlp** [comment]
The schema update also does solve the issue for a freshly created database
Does it mean that admins/managers will have to do this sort of thing every time? Can there be some kind of a fix that isautomaticly applied for the stable version of Specify 6.8?

**Comment by timo11** [comment]
DBs 6.8.00 and higher dbs created with the wizard should have visible auditlog fields without need for schema update.

**Comment by maxxxxxdlp** [comment]
Issue is fixed
What about making `Sp Audit Log` table-less hidden? Or at least providing managers with instructions on where to search for it
