### ISSUE TITLE
Export RS to Dataset is broken. Exported Datasets can't be viewed.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#47]
Specify hangs when you create a dataset from a recordset, and when you try to open a dataset created from a recordset

**Comment by timo11** [comment]
Export RS to DS is all good now.

**Comment by tlammer** [comment]
works but now there is strange text in the pop up for naming the resulting data set:
![image](https://user-images.githubusercontent.com/12532430/36746505-1bf666e2-1bb8-11e8-8459-e6ad8095137c.png)

**Comment by timo11** [comment]
In the form def for that dialog (globalviews.workbench) the Source File Path field is defined as uitype="dsptextfield" initialize="transparent=true"
What the hell is that? It looks pretty transparent to me, so what's the problem?

**Comment by tlammer** [comment]
I just didn't know if Source File Path was supposed to be there.  I didn't remember it being there before and it seemed strange since it doesn't have a value

**Comment by timo11** [comment]
I think it's supposed to be read-only. I think, maybe, if a dataset is imported, sourcefilepath will be filled in. I'm going to try changing the initialization. (Which was added in may 2011 according to git.)

**Comment by timo11** [comment]
If there is a source file path, in workbenchtemplate, it gets displayed. Seems like it's doing what the form def says it should.
