### ISSUE TITLE
'Show Interactions' button does not work

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#474]
When adding new Preparation for a CO, there is a button 'Show Interactions'. Here is the message that is supposed to be shown, if the preparation is not associated with any interactions:
```
Show Interactions
This preparation is not associated with any interactions.
```

Instead, upon button click on macOS, nothing happens (tho button is active and has a hover effect)
<img width="1198" alt="Screen Shot 2019-12-16 at 3 38 47 PM" src="https://user-images.githubusercontent.com/40512816/70945449-dc91c280-201a-11ea-8fa0-aa209e4dd11a.png">
Happens in an empty Invertebrate Paleontology database on macOS in the newest beta build of Specify 6.8 (2019_12_12)

**Comment by maxxxxxdlp** [comment]
Works well on Linux in the empty Invertebrate Paleontology database of the same version of Specify 6.8
![Screenshot from 2019-12-16 15-38-59](https://user-images.githubusercontent.com/40512816/70945647-44480d80-201b-11ea-93b4-1cbfcbf82351.png)

**Comment by maxxxxxdlp** [comment]
Same issue if the button is located on the parent window

<img width="1552" alt="Screen Shot 2019-12-16 at 3 53 41 PM" src="https://user-images.githubusercontent.com/40512816/70946136-45c60580-201c-11ea-821c-bece55e6fbc0.png">

**Comment by timo11** [comment]
button is now disabled for new, unsaved preparations that haven't been assigned primary keys.

**Comment by maxxxxxdlp** [comment]
The button is now disabled, so the bug can not occur

Also, have noticed that I can not add new Storage nodes to the tree, because Search can not find the `"Site"` root node. Is it a bug, or did I do something wrong during the Database Creation Process? (the database is freshly created)
<img width="1440" alt="Screen Shot 2019-12-19 at 11 23 33 AM" src="https://user-images.githubusercontent.com/40512816/71194704-0aad1780-2252-11ea-919d-b7786ba53461.png">
<img width="1440" alt="Screen Shot 2019-12-19 at 11 25 37 AM" src="https://user-images.githubusercontent.com/40512816/71194866-5bbd0b80-2252-11ea-88b7-b326de91c9c4.png">
<img width="1440" alt="Screen Shot 2019-12-19 at 11 26 03 AM" src="https://user-images.githubusercontent.com/40512816/71194867-5bbd0b80-2252-11ea-8a15-ce655aacd2f6.png">
