### ISSUE TITLE
Batch Editor Icon is available for non-admin users in Query Results

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify6#49]
When logged in as a manager (non-admin), and possibly other lower level users, you can access the Batch Editor through the icon in the Query Results page. You should only have access to the batch editor if you're an admin user, I believe. But, icon is not available at the top in the task bar, which is good.

**Comment by timo11** [comment]
Batch edit is supposed to be available to managers too.
The task and the service (on results displays) should only show up for admin and managers now.
