### ISSUE TITLE
Double-clicking on simple search results from preparation table does nothing

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#492]
Results from other tables show the records in a form view when double-clicked

**Comment by maxxxxxdlp** [comment]
![Screenshot (36)](https://user-images.githubusercontent.com/40512816/71633787-14346900-2bdc-11ea-9375-b0e3c0b661a0.png)

Same issue with:
Shipments
Field Notebook Page
Deaccession
Borrow Material

**Comment by timo11** [comment]
By design, only tables with forms in the side bar of the data or interactions tasks can be opened from search results, query or express. When a form isn't available, the view-in-form button is not shown in the top right of the results header, and dbl-clicking does nothing.
