### ISSUE TITLE
Can not query related tables in Query Builder

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#503]
Even though Specify is set up to audit the values of changed fields, such changes are not present here, since I can not select `Old Value` and `New Value` cols in the query builder 
![Screen Shot 2020-01-02 at 12 44 13 PM](https://user-images.githubusercontent.com/40512816/71691975-98622a00-2d5d-11ea-845f-4977bc2fdb22.png)
![Screen Shot 2020-01-02 at 12 40 06 PM](https://user-images.githubusercontent.com/40512816/71691958-8d0efe80-2d5d-11ea-8473-98839a696c3e.png)

**Comment by maxxxxxdlp** [comment]
This seems to get fixed upon the second launch of Specify

**Comment by timo11** [comment]
Judging from the screen shot old and new and vals can't be selected because the "fields" relationship is hidden, which doesn't have anything to do with what's being logged.
The possible fix was to trigger a RestartRequired msg (that's actually a bit unsure of itself) when audit prefs are changed.

**Comment by maxxxxxdlp** [comment]
I have compiled the latest version of the developer branch
This issue does not seem to be solved
And looking at the commit, it does not seem to fix this issue

Let me clarify then what the issue is:
During the first launch of a newly created database in Specify, there are no `Fields` and other related tables present in Query Builder

![Screenshot from 2020-01-08 13-02-28](https://user-images.githubusercontent.com/40512816/72007431-4286f980-3217-11ea-8bbc-0fce5e7af53d.png)

Here are the default settings (I did not change or save anything):
![Screenshot from 2020-01-08 13-02-40](https://user-images.githubusercontent.com/40512816/72007432-4286f980-3217-11ea-9f53-cecfc2abbf06.png)

This is how the same table looks during the 2nd Specify launch
![Screenshot from 2020-01-08 13-03-04](https://user-images.githubusercontent.com/40512816/72007433-4286f980-3217-11ea-9f00-2f4d3670efa1.png)

There must be some kind of action performed before Specify shutdown, or during 2nd launch, hat changed the Audit Log table

**Comment by timo11** [comment]
This is mostly a problem with the fix for #461.
But the restart (may) be required msg after changing audit log prefs is necessary.
