### ISSUE TITLE
Update Logo in splash screen

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#52]

**Comment by timo11** [comment]
The file that needs to be updated is InstallerFiles/SpecifyBigSplash.png

**Comment by tlammer** [comment]
One icon has not been changed:
![image](https://user-images.githubusercontent.com/12532430/36817603-4f87b69c-1ca7-11e8-87c2-7982eb8a6d0b.png)

**Comment by yvonneekanim** [comment]
I found this one as well
![specify logo](https://user-images.githubusercontent.com/28809154/36870569-2dee9f00-1d65-11e8-87ef-731dd9a2032f.png)

**Comment by timo11** [comment]
All splash screens and icons should be updated to the new look.

**Comment by tlammer** [comment]
These icons did not change
![image](https://user-images.githubusercontent.com/12532430/37003166-bdf75c0c-2091-11e8-866c-9fd4fecfd68e.png)

**Comment by tlammer** [comment]
![image](https://user-images.githubusercontent.com/12532430/37102597-c462b4d0-21ed-11e8-9a31-5734e92b65d6.png)
with certaindeath release

**Comment by garrettgirard** [comment]
This still appears to be wrong. The DataExporter, Specify, and Specify4GB (and probably also the ExpCmdLine) apps all are still using the old logo. This is what I am seeing from the latest version (670beta_03) of the (supposedly external) 64 bit version.
![incorrectlogo](https://user-images.githubusercontent.com/12533028/37365837-a7c29816-26cc-11e8-81ec-5161bf0dee51.png)

**Comment by garrettgirard** [comment]
Fixed in the latest version.
