### ISSUE TITLE
BatchEdit Validation and Upload issue

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#520]
When using `Georeference Format Converter`, the `Apply` (inside the window) button applies the changes, without closing the window.

After the user has applied the Georeference Format changes, he is able to press the `Apply` button for BatchEdit (the button at the bottom of the screen)

At this point, the `Georeference Format Converter` remains open. Usualy, when the user closes that window by pressing the `Close` or `X` button, the windows closes and the `Validating...` process begins. If user closes that window after applying the BatchEdit changes, **the `Validating...` and `Preparing to Apply Changes` processes will run at the same time** and their windows appear independently. The result depends on the action that has finished first and is not an accepted behavior

And while solving that bug, I propose adding the `Ok` button to `Georeference Format Converter` that will apply the changes and start the validation process

![Screenshot from 2020-01-06 16-46-03](https://user-images.githubusercontent.com/40512816/71859578-3d556d80-30a4-11ea-814c-a68dfd6d34c1.png)
![Screenshot from 2020-01-06 16-46-11](https://user-images.githubusercontent.com/40512816/71859579-3d556d80-30a4-11ea-92a6-79e41767c2c5.png)
![Screenshot from 2020-01-06 16-46-15](https://user-images.githubusercontent.com/40512816/71859580-3dee0400-30a4-11ea-921d-8454aacf6344.png)
![Screenshot from 2020-01-06 16-46-34](https://user-images.githubusercontent.com/40512816/71859581-3dee0400-30a4-11ea-9e3c-eeae28914981.png)
![Screenshot from 2020-01-06 16-46-38](https://user-images.githubusercontent.com/40512816/71859582-3dee0400-30a4-11ea-983d-2fd563bcbc24.png)

**Comment by timo11** [comment]
GeoRefConverter Dlg is now modal.
Validation now happens after GeoRefConterter Dlg's Apply is clicked, instead of after GRC dlg is closed.

**Comment by maxxxxxdlp** [comment]
If the GeoRefConverter Dlg is closed and Validating had begun, user can still initialize the upload (click the `Apply` button) by pressing `Tab Tab Tab Enter`

Even though this fix does prevent the user from doing this action in most cases, it still does not check whether the validation is in progress before beginning the `Apply` process

**Comment by maxxxxxdlp** [comment]
This fix results in the validation progress bar appearing behind the `GeoReference Format Editor` window

Is there any better solution, that would not require the user to move the child window to see a progress bar?

![Screenshot from 2020-02-06 11-15-30](https://user-images.githubusercontent.com/40512816/73961366-0a381100-48d2-11ea-80bd-edab0777ee8e.png)

**Comment by maxxxxxdlp** [comment]
Also, clicking on the `Apply` button while the validation is in progress results in one more validation process and makes specify window look like this until the validations are complete:

![Screenshot from 2020-02-06 11-43-12](https://user-images.githubusercontent.com/40512816/73963525-10c88780-48d6-11ea-93de-4c37d858a32f.png)
![Screenshot from 2020-02-06 11-43-23](https://user-images.githubusercontent.com/40512816/73963528-10c88780-48d6-11ea-89e2-f3be301c5c4b.png)

The `Apply` button should be disabled if there are conversion in progress. It should get enabled again only after the validation is finished

**Comment by maxxxxxdlp** [comment]
There is one more problem with this fix
Pressing the `Close` button in the `GeoReference Format Editor` triggers `Validating...` even if not changes made
The validation process should not run unless there were changes made

**Comment by maxxxxxdlp** [comment]
Also, same issue can happen with WorkBench
When Specify is busy `Validating...` (after the user pressed the `Validate` button) and the user presses on the `x` button on the taskbar near the different tab, after validation process is finished, he will be immediately prompted whether to save unsaved changes
Though, unlike with BatchEdit, **so far** it did not lead to specify getting frozen

---

Also, while the `Uploading Row #### of ####` or `Undoing Object #### of ####` processes are going on, the UI is not locked and the user can navigate to a different tab or close it

Fortunately though, the current tab can not be closed:
![Screenshot from 2020-02-07 16-53-55](https://user-images.githubusercontent.com/40512816/74071807-8877de80-49ca-11ea-9088-5a0f652eb23b.png)

---

Also, while changes are being committed in WorkBench or BatchEdit, the user is still able to click on other tabs and try to close them. What happens now is that user will be redirected to those tabs after the current process is finished, but he will not get a prompt asking him whether he wants to close the window

**Comment by maxxxxxdlp** [comment]
Accidentally posted those comments under a wrong issue
