### ISSUE TITLE
Fix "Please contact cutomer suppoer" msg

### ISSUE THREAD

**Issue by timo11** [specify/specify6#521]
Typos in message that is displayed when a top task bar item cannot be loaded.

**Comment by timo11** [comment]
Added TaskMgr.PluginLoadFail key to resources bundle. 
(PT,UK,RU versions are in English.)
One way to verify the fix would be to change the "vector" tag to "root" in wbschema_localiziation.xml to produce an error loading the workbench task.

**Comment by maxxxxxdlp** [comment]
I see that the files were changes and the new fixed error message is supposed to appear
Also, I translated corresponding string in Uk and Ru files

When manually changing `vector` to `root` in `wbschema_localiziation.xml` and building that version of Specify, I get the following error message in `SpWizzard:
![Screenshot (52)](https://user-images.githubusercontent.com/40512816/72014166-fe9af100-3224-11ea-9250-2d2dc0c7de91.png)
And then this:
![Screenshot (53)](https://user-images.githubusercontent.com/40512816/72014163-fd69c400-3224-11ea-8b28-8001bb719ba1.png)

**Comment by maxxxxxdlp** [comment]
Fixed

![Screenshot (61)](https://user-images.githubusercontent.com/40512816/72015104-bed50900-3226-11ea-9ebc-bceace517c80.png)
![Screenshot (62)](https://user-images.githubusercontent.com/40512816/72015105-bf6d9f80-3226-11ea-8ab1-f1d53b705ede.png)
