### ISSUE TITLE
Specify is frozen after BatchEdit

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#522]
After finishing BatchEdit, there is a period of time when Specify does not respond to any user inputs and does not indicate that it is loading. This issue has been outlined in #408

If users tried to close the BatchEdit Query windows by pressing the `X` button in the Task Bar, the result is that after Specify finishes processing BatchEdit and is supposed to allow user to control elements in windows, a window appears, that asks us whether to save changes to the query

Yet, **this window can not be closed and can not be interacted with**. it can not be closed using `X`, `Cancel`, `No`, `Yes`, `ALT+F4`, `CMD+Q` or even from the macOS taskbar. At this point Specify does not respond to user's input and is completely frozen. The only thing that user can interact with at this point, is the hover effect for the `X` button of the prompt window, even though the button itself can not be pressed
![Screen Shot 2020-01-07 at 12 51 41 PM](https://user-images.githubusercontent.com/40512816/71929253-10f62b80-314e-11ea-9358-ad851cefe97c.png)

Also, if the user clicked the `X` button on the task bar multiple times, the prompt window is going to get opened multiple times, with only one of them being focused
![Screen Shot 2020-01-07 at 1 02 37 PM](https://user-images.githubusercontent.com/40512816/71929252-10f62b80-314e-11ea-856e-2f2dd1594026.png)

**Comment by maxxxxxdlp** [comment]
So far this problem has only happened on macOS

**Comment by maxxxxxdlp** [comment]
There is one more problem with this fix
Pressing the `Close` button in the `GeoReference Format Editor` triggers `Validating...` even if not changes made
The validation process should not run unless there were changes made

---

Also, same issue can happen with WorkBench
When Specify is busy `Validating...` (after the user pressed the `Validate` button) and the user presses on the `x` button on the taskbar near the different tab, after validation process is finished, he will be immediately prompted whether to save unsaved changes
Though, unlike with BatchEdit, **so far** it did not lead to specify getting frozen

---

Also, while the `Uploading Row #### of ####` or `Undoing Object #### of ####` processes are going on, the UI is not locked and the user can navigate to a different tab or close it

Fortunately though, the current tab can not be closed:
![Screenshot from 2020-02-07 16-53-55](https://user-images.githubusercontent.com/40512816/74071807-8877de80-49ca-11ea-9088-5a0f652eb23b.png)

---

Also, while changes are being committed in WorkBench or BatchEdit, the user is still able to click on other tabs and try to close them. What happens now is that user will be redirected to those tabs after the current process is finished, but he will not get a prompt asking him whether he wants to close the window

**Comment by timo11** [comment]
Validation only occurs when the georef converter dlg is closed if conversions have been done.
Users are supposed to be able to do other things while the uploader is uploading, etc.

**Comment by maxxxxxdlp** [comment]
Tested it again with the newest build
When closing the `GeoReference Format Editor` with no changes made in WorkBench, `Validating...` is not triggered
Though, **it is** when I do the same things in BatchEdit

---

All else seems to work fine
