### ISSUE TITLE
Schema config tool does not support region/country

### ISSUE THREAD

**Issue by timo11** [specify/specify6#532]
So the new Russian and Ukrainian translations can't be edited or even viewed. Nor the Brazilian Portuguese.
![vanished](https://user-images.githubusercontent.com/2915306/72089600-f8af1980-32d1-11ea-97e0-920157500154.png)

**Comment by timo11** [comment]
This problem could be worked-around by eliminating the country codes for russian and ukrainian. Brasilian Portuguese has been uneditable since 2014 so it would appear there is no urgent need for a fix.

**Comment by timo11** [comment]
see #531

**Comment by maxxxxxdlp** [comment]
When using newest Specify 6.8 beta, without recreating the database from previous version, there was no data present for any fields, for any table, for any language, except of english
After trying to fill in some information by hand and saving changes, no changes were saved
![Screenshot (80)](https://user-images.githubusercontent.com/40512816/72174221-ccad9a00-339e-11ea-96eb-d07d81c9bc22.png)
And also, fields were not localized
![Screenshot (79)](https://user-images.githubusercontent.com/40512816/72174299-01215600-339f-11ea-8720-92571139d92d.png)

---

After recreating the database in the new version, those issues were solved
