### ISSUE TITLE
Collecting Event fields are not offered for bulk attachment import when CE is one to one

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#534]
In databases where the CO-CE relationship is one to one (not shared) Collecting Event fields are not offered in the list of available fields to match on.
![image](https://user-images.githubusercontent.com/12532430/72108071-56565c80-32f8-11ea-8f95-62125793e322.png)

**Comment by yvonneekanim** [comment]
'Collecting Information / Field Number' and 'Collecting information / GUID' are now available options
