### ISSUE TITLE
`Undo All` in BatchEdit returns unexpected results

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#540]
I did a few edits in BatchEdit and the pressed the `Undo All` button. As a result of this, the fields that I have edited had their changes discarded, but one entire column has been marked as `edited`, and some of its values are now invalid. It is worth mentioning that I did not touch that column before and that there were no invalid cells detected before the `Undo All` button press

It may be that the values in that column were invalid, but they were not highlighted as such and while undoing the changes, Specify also validated all the cells and tried to fix some invalid cells

![Screenshot from 2020-01-10 13-21-57](https://user-images.githubusercontent.com/40512816/72187345-439d5f80-33ac-11ea-88ce-5b0286e3fe92.png)

Here is how the data looked like before the `Undo All`:
![Screenshot from 2020-01-10 13-27-37](https://user-images.githubusercontent.com/40512816/72187654-20bf7b00-33ad-11ea-981b-d3a12a97d1c5.png)

Here are the console messages after `Undo All`:
![Screenshot from 2020-01-10 13-28-09](https://user-images.githubusercontent.com/40512816/72187673-2f0d9700-33ad-11ea-95e0-dfe828b814d1.png)

This line is repeated over and over and it likely the reason for this error
```
ERROR wb.wbuploader.UploadField:350 - Invalid value 'collecting' for field 'Type'
```

This bug is reproducible again after reopening the BatchEdit

Specify 6.8 (12/20)
Ubuntu 19.10
Amazon Corretto 8
MySQL 5.7.28

**Comment by timo11** [comment]
Unable to reproduce. What columns are being selected? What db is being used?

**Comment by maxxxxxdlp** [comment]
Database is located here:
`smb://resfs.home.ku.edu/groups/BI/Specify/Specify6/Databases/Conversion Databases/FishDBwLabels.sql`

Video of the bug reproduction:
[Untitled2.mp4.zip](https://github.com/specify/specify6/files/4124946/Untitled2.mp4.zip)

**Comment by maxxxxxdlp** [comment]
Here is the video: https://youtu.be/PI7un9-GQBc

**Comment by timo11** [comment]
Still unable to duplicate. Unless I remove 'collecting', 'collecting' from the accessiontype and change titles for other items. A backup of the current version of the db is probably necessary.

**Comment by maxxxxxdlp** [comment]
Here is the archived backup of the database (backuped, compressed into `.tar.xz` and then zipped cause github does not support `.tar.xz`):
[2020_02_04_13_59_08.tar.xz.zip](https://github.com/specify/specify6/files/4156374/2020_02_04_13_59_08.tar.xz.zip)

**Comment by timo11** [comment]
The AccessionType picklist for the Tissue Collection doesn't contain all the values used by accessions associated with tissues. The accession data forms don't work in the Tissue collection either.
The following sql statements should fix the problem:

insert into picklistitem(TimestampCreated, Version, Ordinal, Title, Value, PickListID) select distinct '2020-2-5', 0, 0, type, type, 50 from accession a inner join collectionobject co on co.accessionid = a.accessionid where co.collectionid = 32768 and type not in('cln', 'field_work','gift');

update picklistitem set value = 'Gift' where picklistid = 50 and value = 'gift';

There will still be different picklist values with the same title, which is probably not good, but the B.E. problem should be eliminated.

**Comment by maxxxxxdlp** [comment]
Fixed after running those two queries
This solved the current problem, but what should the user do in the future to prevent this issue from occurring again?
Any guidelines or documentation for them?

**Comment by timo11** [comment]
Keep their picklists consistent with their data to avoid breaking their data forms, the batch editor, the workbench, and other things.
