### ISSUE TITLE
Non admin users can add new prep types via the WorkBench

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#548]
reported by Martin Stein, confirmed by theresa. 
Non admin users (I used a full access user) are able to add new prep types if the spreadsheet imported has prep types that do not match the existing prep type list.
You cannot add new prep types once the spreadsheet has been imported (you can only choose from the drop down list), but it the spreadsheet had the new values already, they are not marked as invalid and will be added to the prep type list once the data set is uploaded.

**Comment by yvonneekanim** [comment]
New prep types are now highlighted as invalid and users are forced to select from list
