### ISSUE TITLE
Remove forbidden characters from default Record Set name in Quick Search 

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#562]
When performing a Quick Search, there is an option to create a record set out of the results in each table
When the user clicks on that button, he is prompted to specify a name for the Record Set. The default name that Specify proposes often has the characters that are not allowed in the Record Set name (like `_` and `,`; see #438)

Here are few examples and related tables:
![Screenshot from 2020-01-14 09-23-02](https://user-images.githubusercontent.com/40512816/72367129-857e1c80-36b0-11ea-9646-60d34dfaa135.png)
![Screenshot from 2020-01-14 09-22-53](https://user-images.githubusercontent.com/40512816/72367133-857e1c80-36b0-11ea-8566-5b60ae7f106c.png)
![Screenshot from 2020-01-14 09-22-45](https://user-images.githubusercontent.com/40512816/72367134-857e1c80-36b0-11ea-9e0c-3dc601389427.png)
![Screenshot from 2020-01-14 09-22-31](https://user-images.githubusercontent.com/40512816/72367135-857e1c80-36b0-11ea-9fe8-d3c21db2665a.png)

This means that Specify autofill is broken and serves only to confuse the user. The autofill should be made to include only allowed characters, or the requirements on allowed characters should be softened (see #438)

I can imagine that there are even more cases when the proposed autofill text is not suitable for name and all of those cases should be fixed to improve user experience

**Comment by timo11** [comment]
This only happened when the recordset being saved had 1 item, i.e. only one row in the result was selected or the result held only row.
