### ISSUE TITLE
Make 'is resolved' on loan prep form read only 

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#566]

**Comment by tlammer** [comment]
Code to replace the Loan Items ViewDef in the Common.views file starting at line 4315
        
        <viewdef
            type="form"
            name="LoanItems"
            class="edu.ku.brc.specify.datamodel.LoanPreparation"
            gettable="edu.ku.brc.af.ui.forms.DataGetterForObj"
            settable="edu.ku.brc.af.ui.forms.DataSetterForObj">
            <desc><![CDATA[Loan viewing form.]]></desc>
            
            <columnDef>105px,2px,80px,5px,110px,2px,90px,5px,53px,2px,56px,5px,105px,2px,210px,p:g</columnDef>
            <columnDef os="lnx">115px,2px,92px,5px,115px,2px,90px,5px,53px,2px,81px,5px,110px,2px,188px,p:g</columnDef>
            <columnDef os="mac">130px,2px,101px,5px,140px,2px,105px,5px,60px,2px,95px,5px,133px,2px,255px,p:g</columnDef>
            <columnDef os="exp">p,2px,p:g,5px:g,p,2px,p:g,5px:g,p,2px,p:g,5px,p:g,2px,p:g(2)</columnDef>
            <rowDef auto="true" cell="p" sep="2dlu"/>
            
            <rows>
                <row>
                    <cell type="label" labelfor="9"/>
                    <cell type="field" id="9" name="preparation.collectionObject.catalogNumber" uitype="text" readonly="true"/>
                    <cell type="label" labelfor="2" label="Preparation Type"/>
                    <cell type="field" id="2" name="preparation.prepType.name" uitype="dsptextfield" readonly="true"/>
                    <cell type="label" labelfor="5"/>
                    <cell type="field" id="5" name="preparation.countAmt" uitype="dsptextfield"/>
                    <cell type="label" label="Taxon Full Name:" initialize="align=right"/>
					<cell type="field" id="cd6" name="preparation.collectionObject.currentDetermination.preferredTaxon.fullName" readonly="true" uitype="text"/>
                </row>
                <row>
                </row>
                <row>
                    <cell type="label" labelfor="1"/>
                    <cell type="field" id="1" name="quantity" uitype="spinner" initialize="max=5000"/>
                    <cell type="label" labelfor="7"/>
                    <cell type="field" id="7" name="quantityReturned" uitype="dsptextfield"/>
                    <cell type="label" labelfor="10" colspan="3"/>
                    <cell type="field" id="10" name="quantityResolved" uitype="dsptextfield"/>
                   <cell type="subview" id="loanReturnPreparations" viewname="LoanReturnPreparation" name="loanReturnPreparations" initialize="btn=true;icon=LoanReturnPreparation"/>
                </row>
                <row>
                    <cell type="label" labelfor="3"/>
                    <cell type="field" id="3" name="descriptionOfMaterial" uitype="text" colspan="11"/>
                    <cell type="field" id="8" name="isResolved" uitype="checkbox" readonly="true"/>
                </row>
                
            </rows>
        </viewdef>

**Comment by maxxxxxdlp** [comment]
Even though it is read-only, it still has focus effects. @tlammer  Is there a way to remove those?

![Screenshot from 2020-02-25 08-25-09](https://user-images.githubusercontent.com/40512816/75255946-5e833200-57a8-11ea-9dc4-71c36f58ecbe.png)

**Comment by tlammer** [comment]
To my knowledge there is not.
