### ISSUE TITLE
Add default Extractor and PcrPerson forms

### ISSUE THREAD

**Issue by timo11** [specify/specify6#588]
see #315

**Comment by tlammer** [comment]
[common.views.zip](https://github.com/specify/specify6/files/4289078/common.views.zip)

**Comment by maxxxxxdlp** [comment]
@tlammer **Where can I find those tables?**

Not available in Queires
<img width="715" alt="Screen Shot 2020-03-04 at 4 19 54 PM" src="https://user-images.githubusercontent.com/40512816/75928781-bbc85480-5e34-11ea-9419-77e5e1fa4d89.png">

Not available in data insetion
<img width="715" alt="Screen Shot 2020-03-04 at 4 19 06 PM" src="https://user-images.githubusercontent.com/40512816/75928779-ba972780-5e34-11ea-9133-35a80f545aeb.png">

Not available in `Data Set Mapping Editor`
<img width="1087" alt="Screen Shot 2020-03-04 at 4 26 41 PM" src="https://user-images.githubusercontent.com/40512816/75928864-efa37a00-5e34-11ea-8eab-349308b1b92a.png">

Yet the tables are not hidden in the `Schema Configuration`
<img width="975" alt="Screen Shot 2020-03-04 at 4 17 30 PM" src="https://user-images.githubusercontent.com/40512816/75928775-b8cd6400-5e34-11ea-845c-a41cacd72c00.png">
<img width="975" alt="Screen Shot 2020-03-04 at 4 17 22 PM" src="https://user-images.githubusercontent.com/40512816/75928769-b5d27380-5e34-11ea-88a2-fd14298804f6.png">

Tested with the latest Specify build

**Comment by tlammer** [comment]
You shouldn't be able to find the tables to add to the sidebar or queries.  They are not independent tables.  They will have to be added to the forms to check.  This should not be marked fixed yet. It is not fixed.
