### ISSUE TITLE
Changing collections takes a long time.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#59]
Since 6.6.06 changing collections can take a long time due to the stats-sending process. Pre 6.6.06, stats sending for the previous collection took place in the background after the new collection was selected, but that was causing exceptions (mostly not reported to the user) and not really working, because the new collection's data was overwriting the previous collection's data during the send.

So now, there can be an extended period of nothingness between the time the change collection menu is clicked and the appearance of the 'choose collection' dialog.

Martin in Denmark complained about this.

Probably we should display some kind of 'closing collection' progress dialog.

**Comment by timo11** [comment]
While stats are being sent, a Closing [Collection Name Here] Collection display appears.
No progress bar. 
The original pre-fix process can be easily restored if needed.

**Comment by garrettgirard** [comment]
This appears to be working. I changed collections in KU Fish and it said "Closing KU Fish Tissue Collection Collection" (so if collection is in the collection's name, it will say it twice lol).

**Comment by timo11** [comment]
msg changed to "Closing [CollectionName]"
