### ISSUE TITLE
Embedded CE info disappears after saving CO

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#591]
To replicate this, add CE information to CO form using an existing catalog number. Save the form and you should get an error message saying "Specify could not recover from a duplicate key error". Close the error message, use a unique catalog number and save the form. The CE information will disappear but all other information will remain on the form.

**Comment by timo11** [comment]
Also, it is then impossible to add CE information to the record, the CE form is permanently disabled.

**Comment by timo11** [comment]
The same problem existed for embedded paleocontext. There are 4 paleo dbs in specify6/6bug591dbs with paleocontext embedded in co, ce (shared and embedded), or locality. The fix should be tested by entering a duplicate catno in the co embedded db and in the co shared ce embedded pc db. Data entry should be tested in general for ce locality in the other two dbs.

Somebody will have to set up the forms for these dbs.

**Comment by yvonneekanim** [comment]
CE info is stored after using unique cat no. No issues with paleo context in above scenarios.
