### ISSUE TITLE
View doesn't exist view[Locality] for entry in dataentry_task.xml

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#593]
I build Specify6 out of the development branch
When I login into Specify, I receive the following error message

![Screenshot from 2020-02-11 13-16-04](https://user-images.githubusercontent.com/40512816/74270480-e8bf9680-4cd0-11ea-9a11-d8976e0f1015.png)

I am using newly created Botany database

After pressing `OK`, Specify launches

**Comment by timo11** [comment]
Caused by typo in Loan.isResolved field definition.
