### ISSUE TITLE
`Specify Installer.app` can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#616]
Tried to install specify from [here](https://github.com/specify/specify6/releases/tag/untagged-015bd4e83fd1d6090ced)

Got this error:

<img width="622" alt="Screen Shot 2020-02-24 at 4 56 53 PM" src="https://user-images.githubusercontent.com/40512816/75198681-d14bc900-5726-11ea-9b66-c0944c1e71db.png">

Though it can still be fixed by performing right click 'open'

<img width="648" alt="Screen Shot 2020-02-24 at 4 57 16 PM" src="https://user-images.githubusercontent.com/40512816/75198682-d1e45f80-5726-11ea-84c3-a70d5bbab0d3.png">

And then pressing the `open` button

<img width="648" alt="Screen Shot 2020-02-24 at 4 57 18 PM" src="https://user-images.githubusercontent.com/40512816/75198683-d1e45f80-5726-11ea-844a-70edcfc7985d.png">

**Comment by benanhalt** [comment]
That release doesn't have the notarization stuff. Try https://github.com/specify/specify6/releases/tag/v6.8.00_test_notarize1

**Comment by maxxxxxdlp** [comment]
[v6.8.00_testing_rc_20200224](https://github.com/specify/specify6/releases/tag/untagged-015bd4e83fd1d6090ced) **worked without any errors**

This is the message when installing from [Specify 6 CI install4j8](https://github.com/specify/specify6/actions/runs/44554158)
<img width="786" alt="Screen Shot 2020-02-24 at 5 03 04 PM" src="https://user-images.githubusercontent.com/40512816/75198972-87afae00-5727-11ea-9b5e-15dac4229f48.png">

This is the message when installing from [Specify 6 CI develop](https://github.com/specify/specify6/actions/runs/44542441)
<img width="786" alt="Screen Shot 2020-02-24 at 5 06 33 PM" src="https://user-images.githubusercontent.com/40512816/75199214-1ae8e380-5728-11ea-8f21-6afbf47361a2.png">
