### ISSUE TITLE
create icons for the new TaxonAttribute, Extractor, and PcrPerson tables.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#628]

**Comment by maxxxxxdlp** [comment]
Seems to work

Extractor has the same icon as agents. @timo11 is it supposed to?

<img width="565" alt="Screen Shot 2020-03-03 at 2 27 20 PM" src="https://user-images.githubusercontent.com/40512816/75816587-1ab99b00-5d5b-11ea-8d8a-b803adac431a.png">
