### ISSUE TITLE
Update  About Form content 

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#633]
Not sure of all the instances where a copyright is indicated, but it is on the 'about' page for Specify 6. I don't see one in Sp 7 -- should we add it?

**Comment by maxxxxxdlp** [comment]
I thought it would change automatically every year depending on the system date. @timo11  Can we do that?

**Comment by timo11** [comment]
@norinespears  is this still accurate: The Specify Software Project is funded by the Advances in Biological Informatics Program, U.S. National Science Foundation (Grant NSF/BIO: 1565098 and earlier awards).

**Comment by norinespears** [comment]
Excellent question! I took it off of the website, but since it was created with NSF funds we might still need to include it. @beach53 should we remove the reference to NSF from Specify?

**Comment by timo11** [comment]
About text now looks like this

![About](https://user-images.githubusercontent.com/2915306/77119735-0d600a00-6a05-11ea-9b2f-f90c456a9484.png)

**Comment by timo11** [comment]
About text now looks like this

![sp6about](https://user-images.githubusercontent.com/2915306/77185828-063a0a00-6aa0-11ea-85d1-acde36e594e7.png)

**Comment by timo11** [comment]
This should be tested on macs to verify form sizing.

**Comment by maxxxxxdlp** [comment]
Seems normal unless user decreases the window size (could have been a problem with small screens, but macs are mostly used with fullhd+ screens)

<img width="1440" alt="Screen Shot 2020-03-20 at 12 04 55 PM" src="https://user-images.githubusercontent.com/40512816/77187800-05ef3e00-6aa3-11ea-87aa-0f1d4275d61d.png">
<img width="1440" alt="Screen Shot 2020-03-20 at 12 05 06 PM" src="https://user-images.githubusercontent.com/40512816/77187812-0b4c8880-6aa3-11ea-9a4f-0f22d560a1d7.png">
<img width="1440" alt="Screen Shot 2020-03-20 at 12 05 16 PM" src="https://user-images.githubusercontent.com/40512816/77187823-10a9d300-6aa3-11ea-8449-f1d2bb9cb133.png">

**Comment by timo11** [comment]
Should be working again now on linux and windows. Please check that mac still works.

**Comment by maxxxxxdlp** [comment]
About Form acts the same way on macOS as I posted before

> Seems normal unless user decreases the window size (could have been a problem with small screens, but macs are mostly used with fullhd+ screens)
> 
> <img alt="Screen Shot 2020-03-20 at 12 04 55 PM" width="1440" src="https://user-images.githubusercontent.com/40512816/77187800-05ef3e00-6aa3-11ea-87aa-0f1d4275d61d.png">
> 
> <img alt="Screen Shot 2020-03-20 at 12 05 06 PM" width="1440" src="https://user-images.githubusercontent.com/40512816/77187812-0b4c8880-6aa3-11ea-9a4f-0f22d560a1d7.png">
> 
> <img alt="Screen Shot 2020-03-20 at 12 05 16 PM" width="1440" src="https://user-images.githubusercontent.com/40512816/77187823-10a9d300-6aa3-11ea-8449-f1d2bb9cb133.png">

**Comment by maxxxxxdlp** [comment]
Can we add scroll bars on something when the window gets too small?
