### ISSUE TITLE
Add SpAuditLog to list of tables in permissions

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#634]
Currently only admin users can access spauditlog table in query creator. All manager level and admin level users can make changes to auditing preferences

**Comment by maxxxxxdlp** [comment]
Also, `Sp Audit Log` table should not be hidden by default

**Comment by maxxxxxdlp** [comment]
When fixed, test to make sure that saved queries are accessible and should disappear when permissions are removed

**Comment by timo11** [comment]
see #653

**Comment by maxxxxxdlp** [comment]
Saved queries do not disappear when permission is revoked and produce a background exception when clicked

Should this case be fixed or is it uncommon enough? Maybe we can add a message explaining that the user has insufficient permissions?

If the user has no access to SpaAuditLogField but has access to SpAuditLog and has a saved query that uses both of these queries, upon opening the saved query, the user will get a message explaining that those fields are not accessible any longer

see #653 for more info
