### ISSUE TITLE
Manager User has access to Auditing preference but not the Auditing table.

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#637]
The Manager User has access to the Auditing preference but not the Auditing table. 
Here are the steps:

Log in to Specify as a Master user
Choose Edit>Preferences -- you will see Auditing in the dialog
Now click on 'Query' in the toolbar
Auditing is not on the sidebar by default
Right-Click by 'Create Query'
Choose Configure 'Query Creators' in the resulting dialog
Click the '+' button at the bottom of the 'Side Bar List' 
Scroll down to look for the auditing table (Sp Audit Log)
It is not in the menu and must be in the menu to use Sp Audit. 

We should decide whether we want users with Manager privileges to have access to Auditing or not.

**Comment by timo11** [comment]
This is easy to adjust via some xml reconfiguration.

**Comment by timo11** [comment]
By default managers get permission to query audits but not to change the auditing prefs.

see #653
