### ISSUE TITLE
SpAuditlogField fields other than FieldName, OldValue, newValue break QB queries

### ISSUE THREAD

**Issue by timo11** [specify/specify6#640]
If any fields from spauditlog->fields other than FieldName, OldValue, NewValue are selected, when the query is run, with Format Data Objects checked, an "An error occurred while running the query" error occurs, and no results are displayed.

**Comment by maxxxxxdlp** [comment]
**Where do I find the `Format Data Objects` option?**

Here are my options and query results:

<img width="1440" alt="Screen Shot 2020-03-04 at 4 13 33 PM" src="https://user-images.githubusercontent.com/40512816/75928047-32fce900-5e33-11ea-97ab-2c49cd1d254a.png">

<img width="1440" alt="Screen Shot 2020-03-04 at 4 13 37 PM" src="https://user-images.githubusercontent.com/40512816/75928045-32645280-5e33-11ea-84be-cee7b5a3350f.png">

Tested on the latest build. Seems to work fine
