### ISSUE TITLE
GeoLocate not working in Workbench

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#65]
I added a locality name, country, state, and county to a mapping that had columns for lat1 and long1 as well as fields for max uncertainty est and max uncertainty est unit.  I clicked to geolocate in WorkBench and it said it couldn't find any values.  I used the same data in the locality data entry form and got back results.  I did the same thing in Workbench again after removing the max uncertainty fields and still did not get back results.

**Comment by timo11** [comment]
I cannot duplicate this problem.

**Comment by tlammer** [comment]
Yeah I can't anymore either.  Don't know if it is due to update, but working
