### ISSUE TITLE
Set up default Schema configuration for SpAuditlog and SpAuditlogField

### ISSUE THREAD

**Issue by timo11** [specify/specify6#658]

**Comment by timo11** [comment]
Here is the 'final' setup. Blank title means the field name will be used as the title/caption by default.

[AuditLogSchemaDefs.xlsx](https://github.com/specify/specify6/files/4308132/AuditLogSchemaDefs.xlsx)

**Comment by maxxxxxdlp** [comment]
I have the unneeded fields hidden, but for some reason, the labels are now the same as column names in the schema

<img width="339" alt="Screen Shot 2020-03-10 at 7 49 29 AM" src="https://user-images.githubusercontent.com/40512816/76313807-ad9a8e00-62a3-11ea-90f6-6d38d09ba712.png">
<img width="369" alt="Screen Shot 2020-03-10 at 7 49 22 AM" src="https://user-images.githubusercontent.com/40512816/76313814-af645180-62a3-11ea-9927-812a93d4f0ff.png">

**Comment by timo11** [comment]
They're supposed to be the same as the field names.

**Comment by timo11** [comment]
Actually they're not supposed to be exactly the same. Also, it's likely that the config will only be complete for databases that are created with the wizard and databases that have never been updated to 6.8.00. Furthermore, the exact captions would probably be replaced by the normal nearly exact titles (e.g. Field Name) on subsequent runs of Specify.

**Comment by timo11** [comment]
Nearly exact titles appear everywhere in Sp after creation or schema update.

**Comment by maxxxxxdlp** [comment]
Github action failed - https://github.com/specify/specify6/actions/runs/53010843
Can not test it

**Comment by timo11** [comment]
Windows verisign is not working.  Hopefully it will fix itself soon.

If you click on the failed action, you can try re-running the build if you have access to the 'Re-run jobs' button.

**Comment by maxxxxxdlp** [comment]
No, I don't have access to that button
