### ISSUE TITLE
Admin user is unable to change Guest privileges

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#662]
From Michigan by Andy

> Security – admin user is unable to access Full Access User or Guest privileges to make changes
(all greyed out). Independently verified in KU Fish database.

> I am an admin for my database but when I go to the Full Access User or Guest user levels all access is denied for everything (all is greyed out at the level) as evidenced below.  I do however have full access to the Manager and Limited Access levels

![image001](https://user-images.githubusercontent.com/40512816/76244972-15e86180-6209-11ea-96e5-4256726f08c3.png)
![image002](https://user-images.githubusercontent.com/40512816/76244969-154fcb00-6209-11ea-8e62-3aedc5f16d55.png)
![image003](https://user-images.githubusercontent.com/40512816/76244967-14b73480-6209-11ea-8f17-ffebaf47e82d.png)
![image004](https://user-images.githubusercontent.com/40512816/76244963-141e9e00-6209-11ea-9be6-fa257ad5aa22.png)

Andy reported this issue in 6.7.04

I was not able to replicate in 6.7.04 or 6.8, most likely I did something wrong when trying to test it

**Comment by timo11** [comment]
In my copy of KU fish from March 3, Guest and FullAccess table permissions are disabled (and display admin perms) for the teaching and voucher collection. But perms for all levels display correctly for the Tissue collection.
![kufishtissueGuest](https://user-images.githubusercontent.com/2915306/76247048-de7bb400-620c-11ea-9d3c-e24c0c8af0c9.png)
![kufishtissueFullAccess](https://user-images.githubusercontent.com/2915306/76247049-de7bb400-620c-11ea-950e-3da274d858bc.png)

**Comment by timo11** [comment]
When I switch the current collection from Voucher to Tissue, and re-open the security config tool, table perms are enabled for all levels in the Teaching and the Tissue collections. But the Voucher collection problems remain.

**Comment by timo11** [comment]
The problem does not occur for new wizard-created dbs.

**Comment by timo11** [comment]
In a recent copy of the ku ento db, for the pinned collection, table permissions are disabled for the Manager and Guest levels, other levels are enabled. For the other collections all levels are enabled.

**Comment by timo11** [comment]
This issue occurrs whenever the SpprincipalID of a database record representing a security level within a collection is equal to the SpecifyUserID of a db record representing a specify user.

In general, the more users and collections there are in a database, the more likely it will be for this error to occur.

But it's fixed now. On branch post6_8_00.

**Comment by timo11** [comment]
This query will return user groups that would have been disabled before the fix:

select distinct c.collectionname `collection`, p2.name `user group` from spprincipal p inner join specifyuser_spprincipal up on up.spprincipalid = p.spprincipalid inner join specifyuser_spprincipal up2 on up2.specifyuserid = up.specifyuserid inner join spprincipal p2 on p2.spprincipalid = up2.specifyuserid inner join collection c on c.collectionid = p2.usergroupscopeid where p.groupsubclass = 'edu.ku.brc.af.auth.specify.principal.AdminPrincipal' and p2.groupsubclass = 'edu.ku.brc.af.auth.specify.principal.GroupPrincipal';

**Comment by timo11** [comment]
The query above says that the following dbs should produce the bug:

KU fish: 
KU Fish Voucher Collection: Guests and Full Access Users

KU ento:
KUEntoPinned: Guests and Managers

KU mammalls:
Mammalogy: Guests and Limited Access Users

**Comment by timo11** [comment]
The fix for this bug is merged into the develop branch as of now.
