### ISSUE TITLE
Add geography full name to locality search box results

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#669]
Edinburgh said they would like to see the geography information associated with a locality in the search results when clicking on the locality query combobox magnifying glass window results.

**Comment by timo11** [comment]
@tlammer - didn't you say you had done this? I don't see any new files in FilesForProgrammers.

**Comment by tlammer** [comment]
I did a different one but needed the code for this one.  then I was going to send you the file with both changes

**Comment by timo11** [comment]
I sent it friday morning

**Comment by tlammer** [comment]
sorry.  i'll modify the file and get it up soon

**Comment by maxxxxxdlp** [comment]
It is there, but the column is just called `Full Name`
Renaming it to `Geography` or something like that would be less confusing

<img width="503" alt="Screen Shot 2020-03-20 at 2 10 44 PM" src="https://user-images.githubusercontent.com/40512816/77198240-98e4a400-6ab4-11ea-9426-8c04e000a4fd.png">

**Comment by tlammer** [comment]
Changing the name can be a separate bug.  we can try to get it into the next release
