### ISSUE TITLE
fix for maxUncertaintyEst import problems breaks pre-existing datasets using maxUncertaintyEst

### ISSUE THREAD

**Issue by timo11** [specify/specify6#67]
In workbenches defined in 6.6.06 or earlier that use geocoorddetail.maxUncertaintyEst, won't upload maxUncertaintyEst values, and won't accept maxUncertaintyEst values from geolocate.

**Comment by tlammer** [comment]
updated kuherps, which had max uncertaintyest values before.  Seemed to update well and the values appear to all still be there.
