### ISSUE TITLE
Can't submit Feedback.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#674]
There are no buttons on the Send Feedback Form (Help | Submit Feedback). There should be an OK btn and a Cancel btn. (this happens for same reason as #670)

**Comment by timo11** [comment]
I wonder it submit feedback works? Where does it go? Does anybody read it?

**Comment by maxxxxxdlp** [comment]
@timo11  Here is the link to see the feedback submitted by users - http://biwebdbtest.nhm.ku.edu/specify6-prod/feedback.php
(the link is not accessible from outside the local network, so you need to use VPN)
