### ISSUE TITLE
Truncate large values when auditing updates.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#676]
The max length for oldvalue and newvalue is 65K chars. Values should be truncated if necessary when saving audits.

**Comment by timo11** [comment]
Because resource imports are not logged in 6, there's really no way to test this, besides some general use of specify with the audit changes pref on.

**Comment by maxxxxxdlp** [comment]
Can I write 65k into a remarks field to test this?

**Comment by timo11** [comment]
I think the form system will truncate it before it gets to the audit system.

**Comment by maxxxxxdlp** [comment]
4096 char is the limit on the Remarks field

Looking at the schema, I can see that `OldValue` and `NewValue` is of the type `text`, which can have 65536 char max

So why did 16k in Sp7 cause an error anyways?

**Comment by timo11** [comment]
Maybe Ben meant 65k?

**Comment by timo11** [comment]
I think some of the text fields in collectionobjectattribute and other attribute tables are 65k, but I don't think there are any larger than 65k.

**Comment by timo11** [comment]
So this maybe didn't even need to be done in Specify 6.

**Comment by yvonneekanim** [comment]
Should it be marked as confirmed then?

**Comment by maxxxxxdlp** [comment]
@yvonneekanim  I am currently testing auditing in Sp6 after this change to make sure it did not break anything else

**Comment by maxxxxxdlp** [comment]
Works well with 16k
