### ISSUE TITLE
Add generic fields to agent table

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#678]
add text, number, integer, and date fields (two each)

**Comment by timo11** [comment]
Yo @tlammer! Are the date fields to be partial precision date fields?

**Comment by tlammer** [comment]
lets be adventurous and make them partial dates.  Might want two verbatim date fields too, please

**Comment by timo11** [comment]
@tlammer, And why not add a few agent fields for an exciting death-spiral effect?

**Comment by tlammer** [comment]
yay spirals.... maybe not though

**Comment by beach53** [comment]
We don't support the death spiral data model.  We are an object-based
platform.  Life and Death Events require eternal recursion until system
failure.

James H. Beach, Executive Director
Specify Collections Consortium
Biodiversity Institute
University of Kansas
1345 Jayhawk Boulevard
Lawrence, KS 66045, USA

beach@specifysoftware.org
www.specifysoftware.org
Office: +1 785-864-4645
Cell: +1 785-331-8508
Skype: beach53
