### ISSUE TITLE
Users can not edit Fields in Web Link Editor

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#682]
Users can not edit Fields in Web Link Editor

Checkboxes for existing fields are not editable
Also, can not add new fields or remove old ones

<img width="571" alt="Screen Shot 2020-03-20 at 12 44 12 PM" src="https://user-images.githubusercontent.com/40512816/77191207-9714e380-6aa8-11ea-87be-03b9b78b5fe7.png">
<img width="571" alt="Screen Shot 2020-03-20 at 12 44 19 PM" src="https://user-images.githubusercontent.com/40512816/77191209-97ad7a00-6aa8-11ea-8c60-6ecc325f41b6.png">

Tested in Ubuntu Specify 6.8 fresh botany and macOS Specify 6.8 fresh botany

**Comment by timo11** [comment]
I think it's working. Read the help.
