### ISSUE TITLE
MaxUncertaintyEst not mapping for batch edit

### ISSUE THREAD

**Issue by timo11** [specify/specify6#69]
It ends up read only.

**Comment by timo11** [comment]
Be sure the maxuncertaintyest is being populated in the batch edit wb. 
For me, it gets populated, but invisibly. I have to clear the column, then choose 'undo' all to get the values to appear. Maybe it doesn't hate other users.

**Comment by tlammer** [comment]
Max uncertainty est not being populated in batch editing.  There is a value for the field in the record but the value is not appearing in batch editing

**Comment by tlammer** [comment]
Query results show values for max uncertainty est but when batch editing, the fields are empty
![image](https://user-images.githubusercontent.com/12532430/37043660-d3c57e70-2126-11e8-922e-6d44b05f160b.png)
![image](https://user-images.githubusercontent.com/12532430/37043702-f5ce7f94-2126-11e8-87f6-1491f984c43f.png)

**Comment by timo11** [comment]
This bug is for the mapping problem. If the column is enabled. This bug is fixed. 
If the field is unpopulated that means bug #46 lives on.

**Comment by tlammer** [comment]
It is enabled so the bug appears to be fixed
