### ISSUE TITLE
Day/Mon/Year extractors in web portal schema mappings break solr schema

### ISSUE THREAD

**Issue by timo11** [specify/specify6#690]
If a web portal mapping includes Day, Month, or Year extractors, export to web portal creates an invalid  solr schema with duplicate field names.

**Comment by timo11** [comment]
solr fld names are now unique (but captions in web portal are the same for day/mon/yr - the caption of the date field extracted from)

**Comment by maxxxxxdlp** [comment]
Can you explain how to test this?
Do you have a `.zip` file I can use or a database?

**Comment by timo11** [comment]
The dwc mapping (not the portal) in ku fish tissue has mappings for day(startdate), month(startdate), and year(startdate). 
When I ran the curl to import the csv, solr spit out a bunch of errors because there were three fields named ce_startdate.
If you do a webportal export for a mapping that uses date part extractors, and verify there are no duplicate field names in the SolrFieldSchema.xml file in the zip file, it's safe to call it fixed.

**Comment by maxxxxxdlp** [comment]
This is fixed. But can be improved. See #699
