### ISSUE TITLE
Can not Import a mapping

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#695]
When I export a mapping I am not offered the extension .xsd -- not sure if that is possible on a windows machine. So, I add that extension but when I export the mapping and use that extension I can not import it. Not sure if this is an import problem, and export problem, or user error ... 

1) open Schema Mapper
2) create a new mapping (I started with Dwc, made a change and saved the mapping as New Mapping)
3) right-click on sidebar and export the mapping
4) save as xsd_mapping.xsd
5) open different Collection in same database
6) open Schema Mapper
7) Choose Import Mapping from sidebar
8) find exported mapping file in the file manager and choose
9) fill out the dialog
![import_dialog](https://user-images.githubusercontent.com/61208178/77660092-e47ccf00-6f46-11ea-8e64-1776308721c9.png)
10) hit the save button - get an error message:
![import_error](https://user-images.githubusercontent.com/61208178/77660130-efcffa80-6f46-11ea-9b22-874a26deb058.png)
and another:
![uanble_to_import](https://user-images.githubusercontent.com/61208178/77660160-f8283580-6f46-11ea-968e-2f8aeb8a1c48.png)

**Comment by norinespears** [comment]
There was a whole lot of this going on in the log file:
09:40:45 DEBUG specify.config.SpecifyAppContextMgr:2439 - getResourceAsXML: null
09:40:45 ERROR forms.persist.ViewLoader:1348 - Setting Label - Form control with id[1] is not in ViewDef or Panel [Preparation] in ViewSet [Botany Views]
09:40:45 ERROR forms.persist.ViewLoader:1287 - The Field Name [pcrPerson] was not in the Table [DNA Sequence] in ViewSet [Common]
09:40:45 DEBUG specify.config.SpecifyAppContextMgr:2439 - getResourceAsXML: null
09:40:45 ERROR core.db.DBTableIdMgr:527 - Couldn't find tableId[-1]
09:40:45 ERROR forms.persist.ViewLoader:1287 - The Field Name [doSearch] was not in the Table [Collection Object] in ViewSet [Search]
09:40:45 ERROR forms.persist.ViewLoader:475 - Couldn't find the ViewDef for formtable definition name[Collectors]
09:40:45 DEBUG specify.config.SpecifyAppContextMgr:2439 - getResourceAsXML: null
09:40:45 DEBUG specify.config.SpecifyAppContextMgr:2439 - getResourceAsXML: null
09:44:49 DEBUG specify.config.SpecifyAppContextMgr:2439 - getResourceAsXML: null
09:44:49 DEBUG specify.config.SpecifyAppContextMgr:2439 - getResourceAsXML: null
09:44:50 DEBUG brc.specify.Specify:2491 - restartApp
09:44:52 DEBUG ui.forms.ViewSetMgr:373 - C:\Program Files\Specify\config\botany\manager
09:44:52 DEBUG ui.forms.ViewSetMgr:373 - C:\Program Files\Specify\config\botany
09:44:52 DEBUG ui.forms.ViewSetMgr:373 - C:\Program Files\Specify\config\common
09:44:52 DEBUG ui.forms.ViewSetMgr:373 - C:\Program Files\Specify\config\backstop
09:44:52 DEBUG specify.config.SpecifySchemaI18NService:143 - SELECT cn.Name,splocalecontaineritem.Name,splocalecontaineritem.Format, splocalecontaineritem.IsUIFormatter, splocalecontaineritem.PickListName, splocaleitemstr.Text, splocalecontaineritem.IsHidden, splocalecontaineritem.WebLinkName , splocalecontaineritem.IsRequired  FROM splocalecontainer cn INNER JOIN splocalecontaineritem ON cn.SpLocaleContainerID = splocalecontaineritem.SpLocaleContainerID INNER JOIN splocaleitemstr ON splocalecontaineritem.SpLocaleContainerItemID = splocaleitemstr.SpLocaleContainerItemNameID  where splocaleitemstr.Language = 'en' AND cn.SchemaType = 0 AND cn.DisciplineID = 3 order by cn.Name
09:44:52 ERROR brc.ui.CommandDispatcher:87 - Listener has already been registered. ISOASSIGN
09:44:52 ERROR brc.ui.CommandDispatcher:87 - Listener has already been registered. ATTACHMENTS
09:44:52 ERROR brc.ui.CommandDispatcher:87 - Listener has already been registered. Reports
09:44:52 ERROR brc.ui.CommandDispatcher:87 - Listener has already been registered. Reports
09:44:52 ERROR brc.ui.CommandDispatcher:87 - Listener has already been registered. Symbiota
09:44:52 DEBUG specify.config.SpecifyAppContextMgr:2439 - getResourceAsXML: null
09:44:53 ERROR af.core.ContextMgr:280 - Couldn't find service [CollectionObject_Data_Entry_1]
09:44:53 ERROR af.core.ContextMgr:280 - Couldn't find service [CollectingEvent_Data_Entry_10]
09:44:53 ERROR af.core.ContextMgr:280 - Couldn't find service [Taxon_Data_Entry_4]
09:44:53 ERROR af.core.ContextMgr:280 - Couldn't find service [Agent_Data_Entry_5]

**Comment by norinespears** [comment]
Also, I'm getting viewdef errors in the log file - is that normal?
The Field Name [pcrPerson] was not in the Table [DNA Sequence] in ViewSet [Common]
The Field Name [pcrPerson] was not in the Table [DNA Sequence] in ViewSet [Common]The Field Name [pcrPerson] was not in the Table [DNA Sequence] in ViewSet [Common]
The Field Name [doSearch] was not in the Table [Collection Object] in ViewSet [Search]
The Field Name [doSearch] was not in the Table [Collection Object] in ViewSet [Search]The Field Name [doSearch] was not in the Table [Collection Object] in ViewSet [Search]
Couldn't find the ViewDef for formtable definition name[Collectors]


This is a recent build.

**Comment by timo11** [comment]
A specify schema mapping is a mapping of concepts in a schema definition to fields in the Specify data model. It is essentially a specify query. A schema is a set of concepts stored in an xsd file. You are attempting to import a schema mapping into a schema. 

PS. There are always viewdef errors in the log file.

**Comment by norinespears** [comment]
So what are the steps for sharing a schema mapping between collections?

**Comment by timo11** [comment]
right click near mappings, choose export or import.

**Comment by norinespears** [comment]
That is what I was trying to do. I created a mapping in Collection 1 - exported it. Then tried to import that mapping into Collection 2.

**Comment by timo11** [comment]
The dialog in the screen shot is what appears when you click "import schema". A mapping is not a schema.

**Comment by norinespears** [comment]
ahhh - so user error
sorry

**Comment by timo11** [comment]
Also related to "Other Queries" issue.
