### ISSUE TITLE
Remove "Other Queries" button from Schema Mapper

### ISSUE THREAD

**Issue by timo11** [specify/specify6#696]
It is neither supported nor necessary. See #694

**Comment by timo11** [comment]
fixed on post6.8.00 branch.

**Comment by maxxxxxdlp** [comment]
@timo11 Can you push a build of post6_8_00 branch?

I am receiving `Target "package-internal-nonmac" does not exist in the project "Specify 6 Build File"` error whenever I try to build it myself through `ant`

**Comment by benanhalt** [comment]
@maxxxxxdlp That's because we aren't making the internal builds anymore. Try `package-nonmac`

**Comment by maxxxxxdlp** [comment]
@benanhalt Then do we have to update `README.MD`?

**Comment by benanhalt** [comment]
Just did.

**Comment by timo11** [comment]
fixed on develop branch
