### ISSUE TITLE
New Records containing invalid values are not higlighted properly

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#708]
It may be expected behavior, but I want to make sure anyway

If there are any invalid cells present in the row, none of the cells in that row get highlighted when the `highlight new Records` is checked

It may be better to highlight all records, regardless of the presence of invalid cells and highlight invalid cells with red color on top of that

<img width="1440" alt="Screen Shot 2020-03-30 at 1 24 03 PM" src="https://user-images.githubusercontent.com/40512816/77947566-bc180c00-7289-11ea-81ec-36bea9543237.png">

Fixing invalid cells highlights entire row momentarily

Also, the number on the bottom of the screen that is supposed to keep track of new records does not seem to take those not highlighted cells into account and thus the number is not reporting the real amount of new cells

**Comment by timo11** [comment]
Invalid values make it impossible to determine whether a or not a row creates new records.

**Comment by maxxxxxdlp** [comment]
Ok, makes sense

**Comment by maxxxxxdlp** [comment]
> Invalid values make it impossible to determine whether a or not a row creates new records.

@timo11 Why are there only some cells highlighted for this row?

![Screen Shot 2020-04-01 at 12 04 13 PM](https://user-images.githubusercontent.com/40512816/78165440-f19b3180-7410-11ea-8efe-73137af735b5.png)

**Comment by tlammer** [comment]
I remember having a long discussion about what gets highlighted.  I thought we put it into the documentation for the Workbench.  What gets highlighted and why should be there.
