### ISSUE TITLE
Show Associated COs for Storage doesn't show COS associated via AlternateStorage.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#734]

**Comment by timo11** [comment]
Be sure test for nodes that are associated to collection objects through alternateStorage, and to other collection objects through storage.

**Comment by yvonneekanim** [comment]
I'm not getting counts for storage or alt storage

**Comment by timo11** [comment]
Counts work for storage for me. They do not work for alternate storage.

**Comment by yvonneekanim** [comment]
Should it be working now?
