### ISSUE TITLE
Bad lat/lng2 values in cache table when both lat/lng points are mapped.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#746]
Null latitude2 and longitude2 values are stored in the cache as the string "null".  This messes up export to web portal, and perhaps other types of exports.

see https://github.com/specify/webportal-installer/issues/53

**Comment by timo11** [comment]
The cache tables for mappings that use lat/lng2 will need to be rebuilt for the fix to take effect.

**Comment by yvonneekanim** [comment]
I created a new cache with no data in lat2/long2. I created the cache and 'exported for web portal'. When I looked at the csv generated, it says "null" for lat2 and long 2. 
[PortalData.zip](https://github.com/specify/specify6/files/6540923/PortalData.zip)

**Comment by norinespears** [comment]
In the file it should say null without quotes (not "null")

**Comment by maxxxxxdlp** [comment]
Empty cells are just empty in the CSV file, no `"null"` literals are present.
E.x `1,,1` instead of `1,null,1`
