### ISSUE TITLE
Can't batch edit newly added geography tree levels

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#750]
If you modify the geography tree definition by adding a new rank, the rank is not editable and remains grayed out in the batch edit window

**Comment by timo11** [comment]
The geography tree definitions in the *_update_wb_datamodel.xml files and specify_workbench_upload_def.xml need to be updated to account for "custom" tree levels. 
As does specify_workbench_datamodel.xml in order to use custom tree levels in the standard workbench.

**Comment by timo11** [comment]
see #803

**Comment by yvonneekanim** [comment]
Updating *_update_wb_datamodel.xml files with the new tree level resolves this issue. Specify will have to be restarted for the change to take effect
