### ISSUE TITLE
Disable "Save changes?" prompt when closing unaltered data entry form

### ISSUE THREAD

**Issue by FedorSteeman** [specify/specify6#758]
As a Specify IT User (supporter) I do a lot of testing at the moment, which can involve opening a data entry form to see if everything looks the way it's supposed to or not and then moving on. However, even if had not entered any data it still prompts for being sure to not save any changes. It's trivial in normal use, but can become an irritation moment and time consumer, when opening & closing data entry forms many short times successively. 

So I was wondering if the system could register whether any changes were even made, before asking the user to be sure they want to save the non-existing changes. :smile: 

This also goes for specify7 and I will repost there.

**Comment by maxxxxxdlp** [comment]
Duplicate of #429

**Comment by FedorSteeman** [comment]
OK Will bump #429 then. 😄
