### ISSUE TITLE
Error when importing attachment mapping file

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#762]
When I try to import attachment mapping files, regardless of file type, I get this error
![attachment](https://user-images.githubusercontent.com/28809154/82498624-f0ec5680-9ab5-11ea-9266-76a6082d6054.png)
I tried using a csv file with one column, each value separated by a comma like the error mentions but still get the same error

**Comment by timo11** [comment]
Usually when this error is displayed, it is actually because none of the lines in the file matched a record in the db, or an attachment file, depending on the mapping type. If some lines match something, Specify will display of the non-matches, but if there are zero matches, this error gets displayed.

**Comment by yvonneekanim** [comment]
I used existing catalog numbers and accession numbers in the csv files, separated by commas and still got the error

**Comment by timo11** [comment]
It works for me. What db, what files, and what types of mappings aren't working?

**Comment by yvonneekanim** [comment]
I tested it on a copy of vims and in a demodatabase. I've tried mapping accession and collection object. When import it directly by changing the attachment name to the accession number or catalog number, it works fine

**Comment by timo11** [comment]
What ids, what names? 

entries like this work for me in a CO mapping file :

1,att1.png
2,att2.png
3,att3.png
4,att4.png
5,att5.png

**Comment by yvonneekanim** [comment]
I was doing the same thing and it doesn't work for me. @maxxxxxdlp can you take a look at this too?

**Comment by maxxxxxdlp** [comment]
@yvonneekanim ok,
It worked for me a few months ago, tho I will test it again to make sure

**Comment by maxxxxxdlp** [comment]
<img width="321" alt="Screen Shot 2020-05-21 at 1 00 20 PM" src="https://user-images.githubusercontent.com/40512816/82590368-3450ce80-9b63-11ea-9e1f-485e77d88eca.png">
<img width="1440" alt="Screen Shot 2020-05-21 at 1 00 06 PM" src="https://user-images.githubusercontent.com/40512816/82590371-34e96500-9b63-11ea-8852-b5297959f50f.png">

Works well
Tested in an empty database on macOS with the latest Specify 6.8.00 build

**Comment by maxxxxxdlp** [comment]
Works well in Windows 10 with a clean database

**Comment by yvonneekanim** [comment]
By clean database you mean a database with catalog numbers that match what is in the csv file right?

**Comment by maxxxxxdlp** [comment]
Yes

I created a new database
Added 5 COs
Imported a mapping file
Success

**Comment by yvonneekanim** [comment]
Great, thanks. Still doesn't work for me for whatever reason

**Comment by timo11** [comment]
FYI the incorrect display of "...must be separated by..." msg only occurs when none of the files are found - the catnums or whatever don't matter. If that helps?

**Comment by timo11** [comment]
Also, maybe your windows account or specify does not have permission to access the image files?

**Comment by yvonneekanim** [comment]
That doesn't seem to be the problem. Will the log files help?

**Comment by timo11** [comment]
They might. They're our last hope.

**Comment by yvonneekanim** [comment]
I've attached the log file. Also my attachment file path isn't the default path. I don't know if that has anything to do with why it doesn't work but I can add attachments, just not through the import mapping tool
[Log files 5_22_20.docx](https://github.com/specify/specify6/files/4669129/Log.files.5_22_20.docx)

**Comment by timo11** [comment]
Nothing in the log. Can you attach a csv mapping file that isn't working please?

**Comment by yvonneekanim** [comment]
Github won't let me attach a csv. I'll put it in your folder on the shared drive
