### ISSUE TITLE
CatalogNumber autofill can get turned on for B.E. and cause invalid invalid value msgs.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#77]
Autofill preferences in localprefs that match query names and wb ids, can cause the autofill setting to be turned on, which causes 'autofill is on and field must be blank' msgs for catalog numbers and prevents 'Apply'.

**Comment by timo11** [comment]
This bug was reported for the Vascular Plant collection of the latest DemoDatabase. It ONLY happened for me in that collection. Batch Editing a collectionobject query containing catalognumber caused a 'catnum must be blank' error after editing any other cells.

**Comment by tlammer** [comment]
Can't replicate it, so.... fixed?

**Comment by timo11** [comment]
Fixed. If not, and if the weird alignment between outdated local prefs and the batchedit wb ever occurs again, we can save the unlucky victim by removing "WB.AutoFillPref" lines from their local prefs file.
