### ISSUE TITLE
SpWizard fails when building a database

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify6#770]
This error was caused by commit 8de3c297ff3fc4d9418cd91dde7a69cdd441a9af to the master branch because everything works fine as of previous commit (3dfd17c113c8f4ca3ae2a37d473e35415707c3c9)

This is the log at the moment it crashes. It does not show any error messages. Crashes shortly after the user begins the database build process after all of the parameters have been specified
<img width="1150" alt="Screen Shot 2020-05-27 at 6 08 36 PM" src="https://user-images.githubusercontent.com/40512816/83082391-f82cda80-a048-11ea-8dbc-e4861d905c3c.png">

I modified the `schema_localization.xml` file

Even though I made a lot of changes, all of them were like these:

1. Removes the blank lines inside the `<aggregator>` tag
<img width="753" alt="Screen Shot 2020-05-27 at 6 32 39 PM" src="https://user-images.githubusercontent.com/40512816/83082352-cfa4e080-a048-11ea-8b6e-7fe58ab5f569.png">

2. Adds `pt` and `pt_BR` strings
<img width="753" alt="Screen Shot 2020-05-27 at 6 32 43 PM" src="https://user-images.githubusercontent.com/40512816/83082355-cfa4e080-a048-11ea-97e8-063b1c983195.png">

3. Replaces `'` with `&apos;`
<img width="759" alt="Screen Shot 2020-05-27 at 6 32 20 PM" src="https://user-images.githubusercontent.com/40512816/83082356-d03d7700-a048-11ea-993d-4b52709bde8e.png">

**Comment by maxxxxxdlp** [comment]
@timo11 do you think the removal of the blank lines from the  `<aggregator>` tag caused this issue?

**Comment by timo11** [comment]
@maxxxxxdlp  This for some reason un-logged exception occurs for me:
com.thoughtworks.xstream.converters.ConversionException: Cannot convert type edu.ku.brc.specify.tools.schemalocale.DisciplineBasedContainer to type edu.ku.brc.specify.datamodel.SpLocaleContainerItem

So it is the xml file apparently. Did the header for a container get changed? I think that happened once before. The xml file is produced by that thoughtworks lib, and it seems to be expecting to read something it wrote.

I'm going to add logging for the exception, and look at it some more, also will see if my fix for importing schemas has anything to do with it.

**Comment by timo11** [comment]
The wizard does not actually crash for me. The error occurs, schema localization fails, and the "... completed with no errors." msg appears.

**Comment by timo11** [comment]
@maxxxxxdlp are you running the wizard from an installed build or from an ide? If you're using an ide you might need to run edu.ku.brc.specify.tools.datamodelgenerator.DatamodelGenerator to update specify_datamodel.xml. The wizard works for me. At this point the error I found looks to me like an intentionally ignored glitch.

**Comment by maxxxxxdlp** [comment]
I used the action
This one failed: https://github.com/specify/specify6/actions/runs/116041228
This one worked: https://github.com/specify/specify6/actions/runs/115262713

I can try again today with the newest one: https://github.com/specify/specify6/actions/runs/117358558

**Comment by maxxxxxdlp** [comment]
```
:07:14 DEBUG specify.utilapps.BuildSampleDatabase:1075 - Out createEmptyDiscipline - createStep: 8
12:07:14 DEBUG specify.utilapps.BuildSampleDatabase:1234 - SELECT COUNT(*) FROM autonumberingscheme ans INNER JOIN autonumsch_div ad ON ans.AutoNumberingSchemeID = ad.AutoNumberingSchemeID INNER JOIN division d ON ad.DivisionID = d.UserGroupScopeId WHERE d.UserGroupScopeId = 2
12:07:14 DEBUG core.db.DBTableIdMgr:141 - Reading in datamodel file: /Applications/Specify/config/specify_datamodel.xml to create and populate DBTableMgr
12:07:14 DEBUG core.db.DBTableIdMgr:311 - Done Reading in datamodel file: /Applications/Specify/config/specify_datamodel.xml
12:07:14 ERROR brc.ui.UIRegistry:1187 - There was a problem reading the XML in the file.
12:07:51 DEBUG core.db.DBTableIdMgr:141 - Reading in datamodel file: /Applications/Specify/config/specify_workbench_datamodel.xml to create and populate DBTableMgr
12:07:51 DEBUG core.db.DBTableIdMgr:311 - Done Reading in datamodel file: /Applications/Specify/config/specify_workbench_datamodel.xml
```

**Comment by maxxxxxdlp** [comment]
Nope, does not work with EN
I get this error when logging in
This is the latest version of Specify from the `master` branch

<img width="1095" alt="Screen Shot 2020-05-28 at 12 14 34 PM" src="https://user-images.githubusercontent.com/40512816/83172158-cc5b3480-a0dc-11ea-8104-4dbea7fd35bf.png">

**Comment by maxxxxxdlp** [comment]
Same error messages in `SpWizard` and `Specify` when using RU language

**Comment by maxxxxxdlp** [comment]
Commit reverted from the `master` branch and applied to the `develop` branch
I will test both branches on macOS when the `actions` are ready

**Comment by maxxxxxdlp** [comment]
Still the same problem after I have reversed adding pt and pt_BR but did not reverse other changes
<img width="1440" alt="Screen Shot 2020-05-31 at 4 40 35 PM" src="https://user-images.githubusercontent.com/40512816/83363246-75b05d80-a35d-11ea-87c2-81de650b1171.png">

**Comment by maxxxxxdlp** [comment]
I played around making commits of different sizes.

This commit works fine: b06ce54186aced1b6bf917fe4a7521ec620a9a01
Yet the next one causes problems: 5e5731b295002c31beab7731532574ae4f7a8e5a

@timo11  Can it be that the `.xml` file gets too big and that causes the error?
Or can the problem be connected to special characters used in the Portuguese language?
