### ISSUE TITLE
Include DNASequence parent record info in audit log 

### ISSUE THREAD

**Issue by timo11** [specify/specify6#773]
Since the GGBN datamodel changes, the parent info for DNASequence is only logged if the parent is a materialsample record.

**Comment by timo11** [comment]
Parent info should be logged correctly for materialsample and collectionobject parents.

**Comment by maxxxxxdlp** [comment]
Not sure how to create a material sample record, but creating a DNA Sequence with Collection Object relationship populated correct values in the "Parent Table Num" and "Parent Record Id" columns of the audit log

**Comment by tlammer** [comment]
I tested adding and editing DNA sequence records (and material sample) records when DNA is related through Material Sample (CO->Prep->MS->DNASample).  looks good
![image](https://user-images.githubusercontent.com/12532430/128940176-cc6ff561-d0ca-402b-a5d8-035325505e04.png)
