### ISSUE TITLE
Use new taxonomy download descriptor file. 

### ISSUE THREAD

**Issue by timo11** [specify/specify6#788]
see #787 

Create a new .xml descriptor file so older versions of Specify don't choke on the new taxonomies.

**Comment by timo11** [comment]
The wizard now uses taxonfiles_2.xml to determine what taxon files are available for download. 

I believe we could remove taxonfiles.xml without breaking the wizard if we wanted to prevent older versions being able to download the outdated taxonomies.

**Comment by maxxxxxdlp** [comment]
![Screen Shot 2020-07-23 at 9 34 18 AM](https://user-images.githubusercontent.com/40512816/88258052-e32a9b80-ccc7-11ea-9172-1d1a49e30ffc.png)
I have uploaded `taxonfiles_2.xml` to the server and everything works alright after that
