### ISSUE TITLE
Restore lost field and table descriptions in schema_localization.xml

### ISSUE THREAD

**Issue by timo11** [specify/specify6#791]

**Comment by timo11** [comment]
Here are the descriptions that were replaced:
[fixes.txt](https://github.com/specify/specify6/files/4967016/fixes.txt)

**Comment by timo11** [comment]
commit cbd6dfc5. which introduced strange errors, was whacked by this fix. The descriptions were added to the current master version of schema_localization from commit f25bc870f987

**Comment by yvonneekanim** [comment]
There are no descriptions in [this](https://github.com/specify/specify6/actions/runs/832564390) version

**Comment by tlammer** [comment]
the files.txt that was attached earlier is not clear which tables those fields go to and how it works.
For testing, if I find text1 (or whatever number) fields with russian descriptions in an english database, can I mark this as not fixed?

**Comment by timo11** [comment]
Russian descriptions in an english db would be a different bug. If there are descriptions for the accession table and its fields in any language then this bug is probably fixed.

The fixes.txt file lists the descriptions (mostly just field and table names  that were replaced by actual descriptions. Some of them, e.g. 'deaccession <=' might be worth checking.

**Comment by norinespears** [comment]
I went through this as well. There were SOOO many so I just looked at all Table definitions and randomly chose from among the fields. There were Russian definitions sprinkled throughout still -- from the original bug? I'm moving this over so we can discuss.
