### ISSUE TITLE
Exceptions that break B.E. Apply result in immediate timeout and/or cancel 

### ISSUE THREAD

**Issue by timo11** [specify/specify6#80]
If an exception blows up an 'Apply', The status dlg displays a msg saying that time ran out and the process was cancelled, or "cancelling..." is displayed.
The exception is not printed. 
Sometimes specify hangs when this happens.

**Comment by timo11** [comment]
Now a msg like:
Unexpected error: (followed by the exception's name and error msg).
Then the Apply is cancelled.
Then this msg is displayed:
An unexpected error occurred and edits were not applied. Click 'OK' to resume data editing.
And the user is free to try again.

**Comment by yvonneekanim** [comment]
I'm still getting the 'time ran out' dialog message in the latest release. I have tested in KU Herps & KU Fish. 
![tro](https://user-images.githubusercontent.com/28809154/37175921-87d0c860-22e0-11e8-8deb-e8a21514abca.png)

**Comment by yvonneekanim** [comment]
Unable to reproduce this bug in new releases.
