### ISSUE TITLE
Add more text fields to Loan and Loan Preparation tables

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#808]

**Comment by beach53** [comment]
For bishop museum Jim Boone Ento

**Comment by benanhalt** [comment]
Will add extra fields to giftPreparation and loanPrepation and loan.

**Comment by grantfitzsimmons** [comment]
@benanhalt Are there new fields in the giftPreparation table? There are at least 3 new text fields

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-6-8-02-and-schema-2-10-release-notes/830/1

**Comment by benanhalt** [comment]
There were five text fields added to giftPreparation https://github.com/specify/specify6/pull/1155/files#diff-2ade2e4faba84bc8f7791dc44f1c00993f7a4fc8225043d65be8c7529c67520a

**Comment by grantfitzsimmons** [comment]
I see- thank you! I did not copy all of the field changes into forum post yet. I am glad I double checked.
