### ISSUE TITLE
B.E. Undo Edits can fail if original value contains parenthesis

### ISSUE THREAD

**Issue by timo11** [specify/specify6#81]
For example, if you edit this value:

VISTA HERMOSA, 31.6 KM (BY ROAD) S OF; N SLOPE OF CERRO PELO

'Undo edits' results in a value that does not match the original, and the cell is still highlighted as edited.

**Comment by yvonneekanim** [comment]
Undo edits returns original value for cells with parenthesis and cells are no longer highlighted as edited
