### ISSUE TITLE
QB error due to match limitations on tree level searches.

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#810]
Something about Chinese Harvard Code
 Issue reported by UMich that they got an error message when they did a query on their herbarium database of species = indet.

**Comment by tlammer** [comment]
![image004](https://user-images.githubusercontent.com/12532430/92791917-b5caa780-f372-11ea-923f-29ad4e3bf079.png)
[Anton Giusca.docx](https://github.com/specify/specify6/files/5204258/Anton.Giusca.docx)

**Comment by timo11** [comment]
The maximum number of matches allowed for a tree rank condition has been increased from 523 to as much as 6000 depending on how efficiently the matches can be optimized.

**Comment by norinespears** [comment]
To test create a query that will return 1000's of records. UMich Botany would be a good database.

**Comment by timo11** [comment]
To test, the query must use a condition on a tree rank that matches more than 1000 or so items in the tree.

**Comment by maxxxxxdlp** [comment]
The following query in a blank Botany database returned 14k records without any errors:
![Screenshot_2021-07-27_14-34-13](https://user-images.githubusercontent.com/40512816/127150001-6e2b930e-9c7b-4ed2-9528-8fbb69a9994e.png)
![Screenshot_2021-07-27_14-34-03](https://user-images.githubusercontent.com/40512816/127150002-14c82f1d-35a5-47d8-9c1d-66940b38c64c.png)

I tried using UMich's database, but I got this error during schema update:
![Screenshot_2021-07-27_15-00-02](https://user-images.githubusercontent.com/40512816/127150050-6498467f-9dcc-4f8f-bfdc-c1d47d5f4a30.png)

**Comment by maxxxxxdlp** [comment]
Works in UMich's database by deleting the records from the deaccession table as per @tlammer's suggestion. Query returned ~30k results.

![Screenshot_2021-07-27_20-52-13](https://user-images.githubusercontent.com/40512816/127203490-a160bde3-b513-4aee-afca-cb860a5b7054.png)
![Screenshot_2021-07-27_20-52-02](https://user-images.githubusercontent.com/40512816/127203495-5b0b35ad-aa25-484d-8b9f-5e1eefac9abc.png)
