### ISSUE TITLE
Schema config Import options are labelled differently but behave nearly identically 

### ISSUE THREAD

**Issue by timo11** [specify/specify6#822]
When you import a schema you are provided with two options 'ALL - picklists, weblinks, ...' and 'Localizations only', but the first option doesn't import picklists etc. The only difference between the two options is that the second will refuse to import a file that contains more than one language. Also, there are unverified reports of the first option having no effect on the schema. No errors occur, but it appears that no localizations are imported.

**Comment by timo11** [comment]
Fixed so there only one option. If an import file contains more than one language, a dialog requires the user to choose one and only one. Or none.

**Comment by maxxxxxdlp** [comment]
The language selection dialog was present when importing this file - https://github.com/specify/specify6/blob/develop/config/schema_localization.xml

**But**, both English and Russian have been added without a prompt when importing this file:
[a.zip](https://github.com/specify/specify6/files/6888068/a.zip)

**Comment by maxxxxxdlp** [comment]
Latest version of Specify 6.
Reproduced the same behavior as in the previous comment: https://github.com/specify/specify6/issues/822#issuecomment-887765102

**Comment by tlammer** [comment]
the dialog pops up but when I chose English, it still wouldn't import it because it said there was more than one locale
![image](https://user-images.githubusercontent.com/12532430/128087303-583c581c-5c7c-4884-98f8-b70d147d0f2d.png)

**Comment by tlammer** [comment]
no longer gives me the option to choose a language just says I can't import the schema.
