### ISSUE TITLE
Creating loan from information request doesn't work

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#840]
When I select an information request record when creating a new loan, nothing happens. Should you be able to create a loan record from IR @timo11 

![Screenshot (156)](https://user-images.githubusercontent.com/28809154/102271240-c3994700-3ee4-11eb-9480-17bc0fa395d1.png)
![Screenshot (157)](https://user-images.githubusercontent.com/28809154/102271290-d3189000-3ee4-11eb-83b9-19855f14141c.png)

**Comment by timo11** [comment]
Dropping InfoRequests works, but when you click loan, if loan requests exist, the first dialog's left button will say 'choose recordsets or information requests', if you select an information request in the next dialog, nothing happens.

**Comment by timo11** [comment]
Will need to be tested for when interactions are set up to be created from preps, as well as  from cos.

**Comment by yvonneekanim** [comment]
- I created an information request record from CO. 
- It created am information request recordset
- I clicked on loan and got 'recordsets and information request' as an option on the source of transaction items pop up
- I clicked on the information request recordset and nothing happened
I'm able to create a loan if I drop the IR recordset on loan

**Comment by norinespears** [comment]
I love this functionality!  BUT - I believe it still has issues. 
I created an Information Request with only one CO (1 prep count of 10):
<img width="1016" alt="Screen Shot 2021-06-24 at 2 42 34 PM" src="https://user-images.githubusercontent.com/61208178/123323021-987a5a80-d4fa-11eb-8c51-f8d965f92a54.png">
When I Click on Loan and choose the Information Request I am presented with incorrect Preparations:
<img width="472" alt="Screen Shot 2021-06-24 at 2 42 17 PM" src="https://user-images.githubusercontent.com/61208178/123323088-aaf49400-d4fa-11eb-89f0-d6ae38710b27.png">

**Comment by timo11** [comment]
Works for me. Database?

**Comment by norinespears** [comment]
STILL can not make a backup. So frustrating! BUT, I think I have narrowed this one down. I have build #310 and I'm on Mac Catalina

If I am creating a Loan from an Information Request and have both Info. Requests and Record Sets to choose from (one button returns all to look like this:)
<img width="295" alt="Screen Shot 2021-07-02 at 2 00 50 PM" src="https://user-images.githubusercontent.com/61208178/124322642-6d6cb800-db45-11eb-8d25-32be1362bbb7.png">

then the CO's I am presented with come from one of the record sets rather than from the Info. That behavior SEEMS to be consistent:
<img width="295" alt="Screen Shot 2021-07-02 at 2 00 50 PM" src="https://user-images.githubusercontent.com/61208178/124322194-a48e9980-db44-11eb-8df7-4c97ad6ea5d6.png">

**Comment by norinespears** [comment]
Log file:
14:53:26 DEBUG core.db.DBTableIdMgr:581 - from preparation IN CLASS Preparation WHERE preparation.preparationId in (1,2,3,4,5) AND (collectionMemberId = 4)
14:53:26 DEBUG specify.tasks.InteractionsProcessor$PrepLoaderSQL:638 - -------------- SELECT o.PreparationID, o.barcode, tx.FullName FROM preparation o left join determination dt ON dt.CollectionObjectID = o.CollectionObjectID left JOIN taxon tx ON dt.TaxonID = tx.TaxonID WHERE (isCurrent is null or isCurrent <> 0) AND o.PreparationID in (1,2,3,4,5)
14:53:26 DEBUG specify.tasks.InteractionsProcessor$PrepLoaderSQL:667 - -------------- STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
14:53:26 DEBUG specify.tasks.InteractionsProcessor$PrepLoaderSQL:674 - -------------- STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
14:53:26 DEBUG specify.tasks.InteractionsProcessor$PrepLoaderSQL:697 - -------------- select p.preparationid, p.preparationid, coalesce(p.CountAmt,0), pt.Name, pt.PrepTypeID, avail.available from preparation p inner join (select p.preparationid, coalesce(p.countamt, 0) - (coalesce(sum(lp.unavailable), 0)+coalesce(sum(gp.unavailable), 0)+coalesce(sum(ep.unavailable), 0)+coalesce(sum(dp.unavailable), 0)) available from preparation p  left join (select preparationid, sum(coalesce(quantity, 0) - coalesce(quantityresolved, 0)) unavailable from loanpreparation group by 1) lp on lp.preparationid = p.preparationid left join (select preparationid, sum(coalesce(quantity, 0)) unavailable from giftpreparation group by 1) gp on gp.preparationid = p.preparationid left join (select preparationid, sum(coalesce(quantity, 0)) unavailable from exchangeoutprep group by 1) ep on ep.preparationid = p.preparationid left join (select preparationid, sum(coalesce(quantity, 0)) unavailable from disposalpreparation group by 1) dp on dp.preparationid = p.preparationid where p.preparationid in(1, 2, 3, 4, 5) group by 1) avail on avail.preparationid = p.preparationid inner join preptype pt on pt.preptypeid = p.preptypeid where pt.isloanable
14:53:26 DEBUG specify.tasks.InteractionsProcessor$PrepLoaderSQL:704 - --------------rows: 5
14:53:27 DEBUG specify.tasks.InteractionsProcessor$1:401 - STARTED
14:53:29 DEBUG specify.tasks.InteractionsProcessor$1:401 - DONE

**Comment by norinespears** [comment]
Also, I originally had Interactions pref set to 'ask'. I also set it to 'Catalog Number' and 'Preparations' but got the same result.

**Comment by norinespears** [comment]
Working!!
