### ISSUE TITLE
Biostrat checkbox checked automatically when chronostrat record viewed from Paleo context

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#842]
If a user selects a chronostrat record from the chronostrat query combobox in paleo context and selects to view the record, the biostrat checkbox gets checked automatically.  
This does not happen when viewing a record through the chronostrat trees

**Comment by tlammer** [comment]
discovered by Bruce Lauer

**Comment by timo11** [comment]
This was happening due to a bad Chronostrat view def in global.views.xml. It appears to been wrong since 2008. People who have an imported or customized ChronosStrat view will probably still see the problem.
