### ISSUE TITLE
Symbiota Concept Mapper missing some concepts

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#85]
the concept mapper is missing Occurrence ID (CO GUID), location security, minimum depth in meters, maximum depth in meters, and verbatim depth.

Reported by Rancho Santa Ana

**Comment by timo11** [comment]
The guid is automatically included as the id of the occurrences.
None of those other fields are in the darwin core archive definition symbiota sent us.

**Comment by timo11** [comment]
locationsecurity does not appear to be a darwin core term. http://rs.tdwg.org/dwc/terms/
