### ISSUE TITLE
Make Bar code in Preparation only allow unique values

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#852]
We need a field that can only have unique values in the Preparation table.
Requested by Edinburgh

**Comment by tlammer** [comment]
also add a unique field in collecting event and locality, please

**Comment by tlammer** [comment]
Jim also agreed that a secondary one for collection object should be added

**Comment by tlammer** [comment]
the last two comments are now a separate bug:
https://github.com/specify/specify6/issues/979

**Comment by norinespears** [comment]
This is not working for me although I was stopped from doing this in a previous version.

**Comment by norinespears** [comment]
This works for me. Do we need to test it with existing databases that have data in the Barcode field?
