### ISSUE TITLE
Preferred taxon field does not use table format

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#853]
Geneva noticed Preferred taxon does not use the taxon table format.
They added author to their taxon table format.  the Taxon field displays the formatted data (Taxon, author) but the Preferred taxon field does not (just displays taxon).

**Comment by tlammer** [comment]
Tested in a freshly created database using build 'fatal: No names found, cannot describe anything' from 4/28.
We edited the taxon table format to add author after full name.  The preferred taxon still only showed the full name

**Comment by timo11** [comment]
That build is from the dispossessed branch, the fix for this bug is on the develop branch.
