### ISSUE TITLE
Workbench Data import won't validate nor import stationFieldNumber and StartDate of CE

### ISSUE THREAD

**Issue by sylviefiat** [specify/specify6#855]
Hi,
I am working to import our data (macroalgae - botany) in Specify6 using the workbench. I have made all the mapping and everything seems to be fine: data validation and then import is ok. But when I check, the data is missing in two fields of CE table: stationFieldNumber and startDate... I have checked all the configuration and all seems to be fine, format is ok too.
When trying to upload dataset, validation is fine, upload goes well but in "view" checkout the fields are not here
![bug_import_specify](https://user-images.githubusercontent.com/10070120/112381537-cbb41e80-8d3e-11eb-9e99-c01e3ffa5b06.png)

I have checked schemas configurations (both workbench and app), database entries for workbench mapping, config files... I don't know where to look anymore, if I could get some help on where to check...
Many thanks
ps: I have checked specify user and developer forum and tried to register there to post my question but without success (for registration, no confirmation email ever came)

**Comment by tlammer** [comment]
Can you send an image of the mapping you are using?

**Comment by sylviefiat** [comment]
Here is the mapping from workbenchtemplatemappingitem, I just copied CE table and added examples of data that is uploaded in those fields, I can show more if you need - all field are uploaded ok except for startDate and stationFieldNumber (date format is dd/mm/yyyy but is working ok for  catalogued Date)
![specify_mapping](https://user-images.githubusercontent.com/10070120/112557022-89aed980-8e1f-11eb-9fdb-f97a08d6cd16.png)

**Comment by sylviefiat** [comment]
Hi there, any help on this ? Many tanks...

**Comment by timo11** [comment]
Hi, If you drop the dataset on the 'Export MS Excel Template' Specify will create an spreadsheet that contains all the mappings, but no data. If you attached that file here we should be able to figure out what's going on. If you don't mind sending the data, it would be even better if you used 'Export Data Set and attached that.

**Comment by sylviefiat** [comment]
Hi, here is the spreadsheet, with one line of our data, I added a sreenshot of import mapping, and our datamodel_automappings.xml file (as txt because github doesn't support xml in here)...

- [NOU201768.xlsx](https://github.com/specify/specify6/files/6267326/NOU201768.xlsx)
- [datamodel_automappings.txt](https://github.com/specify/specify6/files/6267346/datamodel_automappings.txt)
![mapping_specify](https://user-images.githubusercontent.com/10070120/113772838-f6f03200-9770-11eb-9773-72fb50b6cf2a.png)

thanks again

**Comment by timo11** [comment]
Could you please use 'Export MS Excel Template' and send the resulting .xls file? Thanks.

**Comment by sylviefiat** [comment]
[export_mapping.xlsx](https://github.com/specify/specify6/files/6267865/export_mapping.xlsx)

**Comment by timo11** [comment]
![tomsexceltemplate](https://user-images.githubusercontent.com/2915306/113788918-b73f3100-9703-11eb-8d3d-66f7662dc69a.png)

**Comment by sylviefiat** [comment]
yes that's what I've done...

**Comment by timo11** [comment]
Why did you send an .xlsx file? Specify exports .xls files. Xlsx files are not supported in the current official external release of Specify.

**Comment by sylviefiat** [comment]
Because github issues doesn’t accept .xls files only .xlsx so I just converted the file I got from Specify.

**Comment by timo11** [comment]
Ah. Try compressing into a zip file please. Thanks.

**Comment by sylviefiat** [comment]
Here it, just so I know what is the difference ?
[mapping.zip](https://github.com/specify/specify6/files/6274198/mapping.zip)

**Comment by timo11** [comment]
Thanks! 
The mappings are hidden in the xls and all columns are automatically mapped when the file is imported into Specify. The .xlsx file did not contain the mappings.

**Comment by sylviefiat** [comment]
I am using a configuration made for a French collection "Herbier de Nouvelle-calédonie (NOU)" and yes it seems that the workbench configuration files have been modified, I sent you earlier the "datamodel_automappings.txt" but I can send you others if you think my troubles might be in there ? I have searched in those config files but it seems ok but I am not sure though...
Cheers

**Comment by norinespears** [comment]
Hi Sylvie, it is hard to say what the issue is with your upload as we do not know what has been modified in your system or within your mapping. If you can send us an email and let us know what member institution you are with we would be happy to help through our support channel.

**Comment by sylviefiat** [comment]
Hi both of you, thanks a lot for the investigation even though it wasn't on your side to help... I finally managed to find out what my problem was, it was in specify_workbench_upload_def.xml configuration file which was redefining the fields... removing the lines fixed the bug... so I can upload my data fine now !
