### ISSUE TITLE
WB validation breaks with certain inconsistent determination taxon level mappings

### ISSUE THREAD

**Issue by timo11** [specify/specify6#856]
If taxonomic levels are mapped for one or more determinations, and no tax levels are mapped for one or more determinations, (eg. Genus1, Species1, TypeStatus1, TypeStatus2) WB automatic validation fails to work. There are no error msgs, but invalid cells are not highlighted.

**Comment by timo11** [comment]
This dataset contains mappings that generate the issue:
[random specimens Viktoria had.zip](https://github.com/specify/specify6/files/6213468/random.specimens.Viktoria.had.zip)

**Comment by asommerville20** [comment]
Tried replicating this: the dataset provided gave me an inconsistent determination 1 mapping error msg, and doesn't let me highlight new records/highlight invalid cells due to inconsistent mapping. Unsure of whether this is the desired solution or not, will hold off on confirming for now.

**Comment by timo11** [comment]
Yes, the fix was to detect the inconsistent mappings.
