### ISSUE TITLE
Export Query Results to xls doesn't work for large result sets.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#86]
When I export a query with 45k results the resulting file is empty. When I alter the search criteria so that query returns 1000 records, export to xls works.

**Comment by timo11** [comment]
The query below produced the problem using the ku fish db.
(it can be imported to Specify. You might have to change the extension to .xml)
[xlsexpbug.txt](https://github.com/specify/specify6/files/1803886/xlsexpbug.txt)

**Comment by timo11** [comment]
You need to use specify4G so the 'results_threshold' for queries is 50k.

**Comment by yvonneekanim** [comment]
Large query results can now be exported to excel with no issues
