### ISSUE TITLE
Can't open deaccession and disposal record sets

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#862]
I created record sets from deaccession and disposal query results. When I click on those record sets, I get an error message saying 'Specify could not find a form to display Deaccession (or Disposal) objects'. I'm able to open the deaccession and disposal forms and save data using those forms

**Comment by timo11** [comment]
This also happens for rec sets of all other transactions types except for Loan. I think in the current release (and previous releases) nothing happens when non-loan interaction rec sets are clicked.

**Comment by timo11** [comment]
It should be possible to click Loan, Gift, Borrow, RepoAgreement, Disposal, Deaccession, and ExchangeIn/Out RecSets and open them in Form view, as long as form names match table names.

**Comment by yvonneekanim** [comment]
I can now open recordsets from all interactions. However if I have a recordset from an interaction open for example gift, I can't open another recordset from the gift table. I tried this with recordsets that have overlapping records and with recordsets that have completely different records.
