### ISSUE TITLE
Display sample input pattern for fields with regular expression formatters

### ISSUE THREAD

**Issue by timo11** [specify/specify6#864]

**Comment by timo11** [comment]
a pattern attribute can be added to the format definition that is displayed during data entry. For example:

`  <format system="false" name="reg_num" class="edu.ku.brc.specify.datamodel.CollectionObject" fieldname="catalogNumber" default="false">
    <field type="regex" size="15" minsize="11" value="MZB (\d{2}|\d{4})\-\d{4}(-[A-Z])?" pattern="MZB ####-####-A"/>
  </format>
`
produces this:

![864shot](https://user-images.githubusercontent.com/2915306/115047712-64e9d700-9e9e-11eb-8ba4-b0845b46d08e.png)

**Comment by norinespears** [comment]
Just so I'm clear, it also enforces the pattern i.e. MZB has to be MZB?

**Comment by timo11** [comment]
The regular expression is enforced. The pattern/mask whatever is just an example. MZB-81-1234, MZB 1981-1234,  are allowed by the reg ex but don't match the pattern.

**Comment by timo11** [comment]
Note --- The pattern probably can't have more characters than the size specified in the format definition.

**Comment by norinespears** [comment]
Use the database that Tim converted for Barcelona to test.

**Comment by tlammer** [comment]
looks pretty

**Comment by maxxxxxdlp** [comment]
Works in a fresh database

**Comment by maxxxxxdlp** [comment]
Ups, didn't notice @tlammer has already tested this
