### ISSUE TITLE
Error when updating 6.8.00 dbs to version with deaccessions

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#869]
This is what I get when updating to [this](https://github.com/specify/specify6/actions/runs/768408225) version:
![loan return](https://user-images.githubusercontent.com/28809154/116295129-5fbe3f00-a75e-11eb-8c13-f32fd3671c69.png)

**Comment by timo11** [comment]
what version of mysql are you using?

**Comment by norinespears** [comment]
probably a dumb question - but are there loaned items in the loan?
