### ISSUE TITLE
Specify.exe not getting removed from the bin

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#87]
I believe we aren't supporting it anymore.  So, it should get removed from the list of options

**Comment by timo11** [comment]
Too late now.

**Comment by timo11** [comment]
But there still is a Specify for windows 32 bit.
I think, for the mac, there is no longer a Specify1G.

**Comment by timo11** [comment]
Also for 64 bit linux and windows, no more Specify1G.

**Comment by garrettgirard** [comment]
What did we end up deciding on after our meeting? I think it was we would be getting rid of the Specify.exe for 32 bit and renaming Specify1G.exe to Specify.exe
What about for 64 bit? Did we decide to keep both Specify.exe (1G) and Specify4G.exe?
