### ISSUE TITLE
If the default source table is set to 'ask' loan return doesn't work

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#870]
I changed the default source table in prefs from collection object to 'ask'. When I open a loan and click on 'return loan' I do not get any prompt to choose from record set or to enter items

**Comment by timo11** [comment]
If 'ask' and 'enter ids' is selected, dlg pops up asking which table to search. If 'from recordset' is selected, co AND Prep Recordsets are listed in following dlg. 
Only the preferred table's RSs are displayed otherwise.
Message is fixed on dlg for selecting tbl to search.
