### ISSUE TITLE
Display a better message when items that are not a part of loan are selected

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify6#871]
Currently if I enter a catalog number to be returned that isn't a part of the loan, I get the message in the image below. A message such as '[catalog number] not found in loan' or something similar would look better imo.
![nonreturn](https://user-images.githubusercontent.com/28809154/116449461-cfe0c980-a81f-11eb-9290-e90406ec0f83.png)

**Comment by timo11** [comment]
Now says. "Your selection included items that are already returned or are not associated with this loan.".
Just so you know.
