### ISSUE TITLE
If I change the Station Field Number, it deletes the original CE record

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#88]
In a fish database, I created a CO query that had CE fields and locality fields.
I changed the station field number to a new value.  The CE didn't have data in other fields other than a link to locality (which was included in the query).  It deleted the original CE record

**Comment by timo11** [comment]
How do you know it deleted it? If the ce wasn't used by any other co's it will just replace the stationfieldnumber of the existing ce.

**Comment by tlammer** [comment]
I bet that is exactly what happened because I'm an idiot.  Of course that is what would have happened

**Comment by timo11** [comment]
ummm. except that maybe one might reasonably argue that stationfield is some kind of sacred identifier that must be preserved just in case some day some other collection object might need it.
