### ISSUE TITLE
Lat/Long Type Invalid message is incorrect

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify6#89]
In the B.E., if you select Line, Point, or Rectangle as the value for Lat/Long Type without filling in Lat/Long coordinates, it will be highlighted red and say "Value must be one of: ; Edited (Original value: empty)".

This changes depending on if you have Lat1/Long1 filled in, in which case it says that the value must be Point (which makes more sense). But I think that the Lat1/Long1 and Lat2/Long2 should be highlighted red if empty, depending on which value is selected for Lat/Long Type. For example, if you select Point, Lat1 and Long1 should be highlighted red until they are filled in. If you select Line or Rectangle, then Lat1/Long1 and Lat2/Long2 should be highlighted red until filled in. Also, the invalid message for Lat/Long Type should probably say something explaining that Lat/Long must be not be empty.

This isn't that big of a deal, but kind of confusing if you're using the wrong Lat/Long Type or something.

**Comment by timo11** [comment]
That means the the value must be one of nothing. In other words blank. Obviously.

**Comment by garrettgirard** [comment]
It's still kind of confusing, you might not be sure why it should be blank or something. Also considering issue #90 , this is still a problem. There's no way to make it blank again.

**Comment by yvonneekanim** [comment]
Lat/long values are highlighted red if they are incomplete based on the chosen lat/long type. If lat/long type is chosen first before values are entered, only the lat/long type is highlighted.
