### ISSUE TITLE
Received By not required on Return Preparation Form

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#892]
If I use the Return Loan button on the bottom of the Loan Form the Received By and Date are required. 
If I click on the Loan Preparation and then the Return Preparation button to open that form I am able to add a Loan Preparation return and leave the Received By unfilled I am able to save.

Also, if I use the Return Loan button and return preparations and fill in the information - then open the Return Preparation form the field is blank.

**Comment by norinespears** [comment]
We made the decision to make the nested dialog for this one editable only (take away the ability to add a return) which invalidates this ticket. Although - one could possibly delete the agent's name.

**Comment by tlammer** [comment]
can no longer return using Return Preparation button
