### ISSUE TITLE
It is possible to resolve more items than were loaned.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#893]
When there are multiple loan return preparations associated with a loan preparation, the quantity resolved can be greater than the quantity. To reproduce, create a loan return preparation for a loan preparation, enter quantity returned and/or resolved, add another  loan return prep and enter quantities, return to the first preparation and you will probably be allowed to resolve more items than were loaned. 

![ResolvedGTLoaned](https://user-images.githubusercontent.com/2915306/116755103-88993b00-a9cf-11eb-97d1-9544481496b0.png)

When you close the Loan Preparation form you may see an error msg about more items being returned (should be resolved) than loaned. If you cancel the loan preparation, eventually, the grid view may update with the invalid quantites:

![After_LP_Cancel](https://user-images.githubusercontent.com/2915306/116755551-33a9f480-a9d0-11eb-958e-a3b28453c4b7.png)

Even if the grid display does not update, saving the loan results in more items resolved than loaned for the preparation.

**Comment by norinespears** [comment]
checked on 5/18. Behavior still a bit wonky.

**Comment by timo11** [comment]
Define wonky. Please.

**Comment by timo11** [comment]
This should be better as of 6/8. HOWEVER, cancelling the loan prep form is still possible for now and that may be less dangerous but can still most likely cause problems, AND there have never been limits on changing the Loan Prep Quantity, and if it is editied problems can occur because the loan return prep business rules are based on the saved un-edited loan prep quantity.
