### ISSUE TITLE
new user not associated with default collection

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#899]
Logged into the WB demo Specify database: 
api.test.speifycloud.org
created a new user
filled out all criteria except for the collection
when I tried to login I got this message:
![Screen Shot 2021-05-03 at 1 08 45 PM](https://user-images.githubusercontent.com/61208178/116915483-b077e100-ac11-11eb-88c0-1ab5a0c40f27.png)

**Comment by timo11** [comment]
This is Specify 7?
