### ISSUE TITLE
B.E.: Lat/Long Type Picklist cannot be null once a value is selected

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify6#90]
If you select a value for the Lat/Long Type picklist, then there is no way to make the value null again. This can be an issue if there is not lat/long data for the record.

**Comment by timo11** [comment]
latLongType, AgentType, ReferenceWorkType and maybe other types of Type lists, now have an empty element for clearing cells in the WB.

**Comment by garrettgirard** [comment]
It exists. Tested in Kent State bryo, 10000PisDay build.
