### ISSUE TITLE
Add indication that collection has been chosen in the dialog

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#900]
in the api.test.specifycloud database
Manage User
Choose a user 
select the collection button
in the next dialog a list of collections is available and I can click on one I have actually chosen it and it is associated but there is no indication that anything has happened. Can we change the dialog?
![Screen Shot 2021-05-03 at 1 11 10 PM](https://user-images.githubusercontent.com/61208178/116915994-5a576d80-ac12-11eb-91e0-1ca9adffe8a4.png)

**Comment by timo11** [comment]
Sp 7? Not 6.

**Comment by norinespears** [comment]
Yes- sorry - I have too many windows open.
