### ISSUE TITLE
Loan Return says items in return are not in loan when they are

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#906]
I created a loan with two preps from a single co record.  I closed the loan.  Then reopened the loan, switched to edit mode and clicked the Return Loan button on the Loan form.  I selected to enter record IDs then entered the catalog number for the co record.  The next window that pops up says I entered values that are not in the loan, but the value I entered was in the loan.
This happened both when ask and collection object were selected in preferences.

**Comment by tlammer** [comment]
[2021_05_05_16_02_43.zip](https://github.com/specify/specify6/files/6430263/2021_05_05_16_02_43.zip)

**Comment by timo11** [comment]
This is happening because there are 3 preparations associated with the specimen and one of them is not in the loan.

**Comment by timo11** [comment]
There is code to suppresse that message in this situation, but it is obviously not working.

**Comment by timo11** [comment]
The message will not appear when selected preps that are not in the loan belong to collectionobjects that have other preps that are associated with the loan. 
Also, the message was changed from "Your selection included records that are not associated \nwith this loan, or have already been returned." to "Some of records included in your selection are not associated \nwith this loan, or have already been returned."
