### ISSUE TITLE
Add 'Count of Items' to Disposal, Gift, ExchangeOut, and DeAccessions

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#909]
These are calculated fields not in the schema.

**Comment by timo11** [comment]
Working for disposal, gift, and exchangeout, but not yet for Deaccession

**Comment by timo11** [comment]
Works for deaccession. Be sure to test these fields in the query builder. I think there is another bug for that... somewhere.

**Comment by tlammer** [comment]
not appearing on the disposal form
