### ISSUE TITLE
Schema Changes for additional fields and for longer fields requested by SCC members

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#910]
This is a running list of new fields and extensions based on requests from SCC SAC and TAC Committees, and other members.

**Additional fields:**

Agent - We would like at least one additional text field in the Agents table.
CollectionObject - additional text field, we have data that we are unable to accommodate in remaining available fields. Currently using fieldNumber and this is too short. (RBGE)
CollectionObject - additional text field, to store remarks that we want to be made publicly available. These are currently all held in Remarks.(RBGE)
CollectingEvent - additional text field (text 65,535) as we have some data we are currently able to accommodate. We are considering storing description in collectingevent instead and we are using all the currently available fields(RBGE)
Determination - additional text field as we would like to be able to record the Institution or herbarium that the determiner was at when the determination was made.(RBGE)
Preparation - additional text field as we would like to be able to record label status, and we are using all of the currently available fields.(RBGE)
Preparation- additional text field, to store remarks that we want to be made publicly available. These are currently all held in Remarks.(RBGE)
Preparation - additional string type field. An additional field, to be used as a picklist to store additional defined terms about the type of material this preparation is. This would be more detailed than the level of data stored in PrepType(RBGE)
Gift - additional date field as we are unable to accommodate some of the data we have(RBGE)
Gift - additional field of type string (250 characters). This is going to be used for a regularly queried picklist and I believe the string data type will help with the optimisation (and speed) of this.(RBGE)
GiftAgent - is it possible to have a date field? We are planning on using the Gift table to record destrctive sampling being sent out. As part of this process the request can have various statuses, linked to a person making a choice and it would be good to be able to record the date this decision was made.(RBGE)
Loan - we would like a Status field (the same as the one in Accessions, (string, 32)(RBGE)
Borrow - we would like a Status field (the same as the one in Accessions, (string, 32)(RBGE)
Gift - we would like a Status field (the same as the one in Accessions, (string, 32)(RBGE)
Gift - 2 additional text fields, we have used all available fields and are aware of some data we would currently be unable to store(RBGE)
five textfields (type string length 128) to the table Determination - In order to use geological collections more appropriately it is necessary to have additional text fields in the table Determinations. (NHM Geneva)

**Increased Length**
“Title” field could be longer in the Reference Work table, but it’s not critical – For papers with really long titles that don’t fit there isn’t really a risk of mistaking it for a different manuscript.(FFW)
BorrowMaterial - Description (string, 50) too short to include the data we have. Using InComments instead. (RBGE)
CollectingTrip - CollectingTripName (string, 250) too short for some of our expedition names (RBGE)
CollectionObject - Description (string, 255) too short to use for the description of a plant (these can be mini essays!), We are currently using text1 (text 65,535) (RBGE)
Address - Address3, Address4, Address5 (string, 64) too short for some of our addresses - data is currenly being truncated (RBGE)

**Comment by norinespears** [comment]
From Ian: May I request a few extra custom fields on the determinations table please? I just one need one extra text field (there are currently two), but it might be good to add some extra number and yesno fields at the same time. I'd say a total of five custom fields per data type should cover any eventuality.

**Comment by norinespears** [comment]
From alexi: In order to use geological collections more appropriately it is necessary to have additional text fields in the table Determinations.
Please add about five textfields (type string length 128) to the table Determination.

**Comment by norinespears** [comment]
From Rob Robbins UFL: increase the Feature or Basis' field by at least 25 characters (it is currently 50). He often runs out of room for his comments even though he is already abbreviating.

**Comment by timo11** [comment]
CollectionObject 
added Text4-8. 65k lobs like Text1.
increased length of Description to 1000.

**Comment by tlammer** [comment]
BorrowMaterial - Description (string, 50) too short to include the data we have. Using InComments instead. (RBGE)
only one that was not done.

**Comment by norinespears** [comment]
Reason for Embargo
Embargo Start Date
Embargo Release Date
Embargo Authority (link to the agent table)
