### ISSUE TITLE
Highlight new cells doesn't work if there are Locality or geography fields in a mapping but no Collecting Event fields mapped or filled in

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#913]
Discovered by Canada

They had a dataset and I created a new CO dataset with locality and geography fields but no CE fields (I also created a mapping with station field number mapped but empty with the same results).
When there are CE fields with values in the mapping, highlight new cells finds x number of new taxa.  When I remove the values out of the ce field or remove the field from the mapping, highlight new cells finds fewer new taxa.
In one instance it found no new taxa, in another it found some new taxa

**Comment by timo11** [comment]
caused by 2016 fix to prevent blank tree levels from highlighting as new. bugzilla #10257
