### ISSUE TITLE
Enter Catalog Number List Dialog needs slider

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#917]
I am returning loans and entering the numbers based on the catalog numbers. I'm scanning in barcodes so going quickly and I have filled the dialog but the numbers are not wrapping and the dialog is not expanding.
Here is the dialog:
<img width="552" alt="Screen Shot 2021-05-17 at 1 02 04 PM" src="https://user-images.githubusercontent.com/61208178/118535984-c35ddb80-b710-11eb-9993-f724235951e1.png">

**Comment by timo11** [comment]
Can you add those numbers? I think the only way to add lists of IDs is to separate them with a comma, or comma-newline. A vertical scroll bar does appear for multiple lines.

**Comment by timo11** [comment]
Also what are the buttons in the bottom half of the screen supposed to accomplish?
![bottombuttons](https://user-images.githubusercontent.com/2915306/118538289-9a8b1580-b713-11eb-82c3-d3097f30ee23.png)

**Comment by norinespears** [comment]
I have to go in and manually add the comma - then I can add this. It would be great if we could automatically add the comma for people using a barcode scanner. Any ingenious ideas for that? Also, I was hoping for a horizontal scrollbar for my long, long line of identifiers.

**Comment by timo11** [comment]
input area now line-wraps and scrolls vertically.
