### ISSUE TITLE
Display Accessions in Deaccession form

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#924]
What information would be useful? Here's a strawman:
![deaccessions form_mockup](https://user-images.githubusercontent.com/61208178/118994747-330bda80-b94c-11eb-862f-274c7808268a.jpg)

**Comment by norinespears** [comment]
I think I moved this ticket into the wrong column. Did we want to display the Accession numbers in each of the different preps? I.e. 
<img width="1043" alt="Screen Shot 2021-06-28 at 4 31 48 PM" src="https://user-images.githubusercontent.com/61208178/123706880-79e3ce80-d82e-11eb-9e03-d461e648ad1c.png">
Right now each Interaction prep displays differently on the Deaccession form:
<img width="1044" alt="Screen Shot 2021-06-28 at 4 31 59 PM" src="https://user-images.githubusercontent.com/61208178/123706916-8a944480-d82e-11eb-8b51-f1af42722823.png">

**Comment by tlammer** [comment]
make the subforms reflect each other better, similar information in each subform.
If you can get to the accession record from the subforms, then the accession subform doesn't have to be there.

**Comment by norinespears** [comment]
These forms look awesome! However, the accession numbers are not coming through from the Disposal to the Deaccession form - can we explore this?

**Comment by norinespears** [comment]
YES! Accession numbers totally coming through - you just have to ensure that you save everything first. There are however some glitches with counts and type of interaction.
