### ISSUE TITLE
Add incomingLoanNumber field to Loan 

### ISSUE THREAD

**Issue by totallynotleo** [specify/specify6#927]
Add the incoming Loan number (as provided by the lending institution) field to Loan. 
It currently exists on Borrow but not Loan.

**Comment by beach53** [comment]
Perhaps he means that an outgoing loan needs a field for the number the receiving institution assigns to it?

**Comment by beach53** [comment]
@tlammer Theresa did you see this?

**Comment by tlammer** [comment]
@beach53 I did.  I was going to wait and see if he commented that your suggestion was the case.  It would definitely be a new workflow.

**Comment by beach53** [comment]
@tlammer  I don't understand completely.  Why would putting another field on the form for the recipient's Loan ID represent a new work flow?   When he says it currently exists on Borrow but not on Loan is he talking about the Borrow and Loan forms?  Sounds like it to me.  So adding a text field to the form to record a number ...???

**Comment by tlammer** [comment]
@beach53 It sounds like he is confusing what we call borrows with what we call loans.  A lot of our institutions call borrows "incoming loans" as opposed to outgoing loans (what we refer to as loans).  Borrows are treated very differently than loans in that the items coming in are _not_ a part of the collection legally.  They are just borrowing them for a determined time.  As opposed to loans, which continue to be a part of your collection and you are just sending them out and allowing another institution to borrow them for a period.
And actually, thinking about it, it wouldn't make sense for a receiving institution to reassign a catalog number to the items they are borrowing.  Legally, they aren't a part of their collection, they are just borrowing the items, so the original catalog number from the institution to which they belong should still pertain to the item.

**Comment by beach53** [comment]
@tlammer I don't think he is talking about catalog numbers, just loan numbers.  

But you are probably right about the first point, he refers to the lending institution's loan number, which would belong on a Borrow form and transaction from the receivers perspective. It is already on the Borrow form as he points out, so it does sound like there might be some conflation of the two types of transactions.

**Comment by tlammer** [comment]
@beach53 ahhh.  I see what you mean.  Thank you for clarifying.

**Comment by benanhalt** [comment]
Adding `incomingNumber` varchar field.

**Comment by benanhalt** [comment]
When the group last discussed this, it looks like we decided to do it. But reading over the comments it looks like maybe it wasn't one that makes sense. @tlammer can you give me any guidance here?

**Comment by benanhalt** [comment]
We are going to recommend users that want this to use text field instead.
