### ISSUE TITLE
New tables may be assigned incorrect collation

### ISSUE THREAD

**Issue by timo11** [specify/specify6#931]
When a schema update adds new tables, the tables often don't get the correct utf8_general_ci collation.

**Comment by timo11** [comment]
see #932 for confirmation info.

**Comment by timo11** [comment]
Schema updates should no longer produce tables with collations other than utf8_general_ci, except for certain tables intentionally collated otherwise. Updates will also fix any pre-existing incorrect collations.

**Comment by timo11** [comment]
To see what incorrect collations are in a db run "select table_name, table_collation from information_schema.tables where table_schema = '[TheDBName]' and table_collation != 'utf8_general_ci' and table_name not like 'ios_%'; " before a schema update.

 Results might look like this:
+-----------------------+-------------------+
| table_name            | table_collation   |
+-----------------------+-------------------+
| deaccession           | latin1_swedish_ci |
| deaccessionagent      | latin1_swedish_ci |
| deaccessionattachment | latin1_swedish_ci |
| disposalagent         | latin1_swedish_ci |
| disposalattachment    | latin1_swedish_ci |
| disposalpreparation   | latin1_swedish_ci |

After a schema update the same query should return and empty set of records.

**Comment by tlammer** [comment]
updated andy's database and willem's database, both returned results before the update but not after (Andy's was different than Tim's example, but willem's was similar)
