### ISSUE TITLE
Add collation-repair step to schema update - test before #931

### ISSUE THREAD

**Issue by timo11** [specify/specify6#932]
Previously created tables with collations other than utf8_general_ci should altered to use the utf8_general_ci collation.

**Comment by timo11** [comment]
see #931

**Comment by tlammer** [comment]
Can I confirm this by just being able to update an existing database with no errors?

**Comment by timo11** [comment]
see #931 for confirmation clues.

**Comment by tlammer** [comment]
updated andy's database and willem's database, both returned results before the update but not after (Andy's was different than Tim's example, but willem's was similar)
