### ISSUE TITLE
Create and assign Deaccession Type and Status pick lists

### ISSUE THREAD

**Issue by asommerville20** [specify/specify6#936]
when accessing deaccession from the disposal form, no options appear under the Type and Status picklist when the dropdown arrow is pressed

**Comment by timo11** [comment]
`    <picklist name="DeaccessionType" issystem="true" type="0" readonly="true" sizelimit="4">
        <items>
            <picklistitem title="Gift" value="Gift"/>
            <picklistitem title="Destructive Sampling" value="Destructive Sampling"/>
            <picklistitem title="Exchange" value="Exchange"/>
            <picklistitem title="Lost" value="Lost"/>
        </items>
    </picklist>
    <picklist name="DeaccessionStatus" issystem="true" type="0" readonly="true" sizelimit="3">
        <items>
            <picklistitem title="No Data" value="No Data"/>
            <picklistitem title="In Process" value="In Process"/>
            <picklistitem title="Complete" value="Complete"/>
        </items>
    </picklist>
    <picklist name="DisposalAgentRole" issystem="true" type="0" readonly="true" sizelimit="12">
        <items>
            <picklistitem title="Approver" value="Approver"/>
            <picklistitem title="Other" value="Other"/>
            <picklistitem title="Preparer" value="Preparer"/>
            <picklistitem title="Receiver" value="Receiver"/>
            <picklistitem title="Sponsor" value="Sponsor"/>
            <picklistitem title="Staff" value="Staff"/>
            <picklistitem title="Student" value="Student"/>
        </items>
    </picklist>
    <picklist name="DisposalType" issystem="true" type="0" readonly="true" sizelimit="3">
            <items>
                <picklistitem title="Destroyed" value="Destroyed"/>
                <picklistitem title="Destructive Sampling" value="Destructive Sampling"/>
                <picklistitem title="Lost" value="lost"/>
            </items>
    </picklist>`

**Comment by timo11** [comment]
This needs to be tested in the wizard and for schema updates. The contents of the picklists after schema updates or wizard builds for #923 #935 #936 are in the comment above.

**Comment by timo11** [comment]
This is not ready for testing in schema updates - the picklists will not be assigned to the fields. But it can be tested in the wizard.

**Comment by tlammer** [comment]
pick lists created but not assigned

**Comment by tlammer** [comment]
No pick lists assigned in build 791ef85
