### ISSUE TITLE
Replace the geography authority files used by the wizard

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#948]
the current authority files are a bit clunky and dont' match what most people call countries.

**Comment by maxxxxxdlp** [comment]
I think this is the authority we are using right now - http://www.geonames.org/export/
They have updated data (and the country names seem fixed too)

Also, I like this one a lot - https://github.com/hiiamrohit/Countries-States-Cities-database (it even has GUIDs that are resolvable in WikiData)

**Comment by timo11** [comment]
We updated the authority file from  https://www.geonames.org/export/ 2020/8/20.

**Comment by maxxxxxdlp** [comment]
Seems like the updated geonames (August 2020) still have very long country names.

Though, the other geoname source (https://github.com/hiiamrohit/Countries-States-Cities-database) has normal country names, so we can use it. Though it is currently not in the format that specify can imediatly work with. So either this data set or Specify have to be adapted to work with each other.

Or, we can use the same geoname authority, but manually replace the country names.

**Comment by timo11** [comment]
The Aug 2020 version of geonames.sql.zip will now work with the wizard. (The file countryInfo.infile needed to be renamed to countryinfo.infile.)

**Comment by norinespears** [comment]
Can you please let me know where these came from so that I can update the documentation?

**Comment by timo11** [comment]
Edited contientcodes table definition to increase length of name field. Eliminated duplication of the code 'AF' and the name "North Pacific Ocean - Ulithi Atoll" in continentcodes.infile.

Resulting tree looks OK, BUT "North Pacific Ocean - Ulithi Atoll" apparently needs to be removed from geoname.infile also because it is duplicated in the tree.

Also the Oceans don't have children, and we probably don't need them anyway.

**Comment by timo11** [comment]
I don't know. Max sent me this link this morning http://download.geonames.org/export/dump/
GeoNames<http://download.geonames.org/export/dump/>
Readme for GeoNames Gazetteer extract files ===== This work is licensed under a Creative Commons Attribution 4.0 License, see https://creativecommons.org/licenses/by ...
download.geonames.org

________________________________

**Comment by maxxxxxdlp** [comment]
Replaced long country names with short variants in cada728b5dbb4c985e3136876074a5ffbf020535

For future reference, this is the MySQL query used to archive that:

```sql
START TRANSACTION;

UPDATE geoname gg
JOIN
       (
              SELECT g.geonameid,
                     g.asciiname,
                     c.NAME
              FROM   geoname g
              JOIN   countryinfo c
              ON     c.iso_alpha2 = g.country
              WHERE  g.fcode = 'PCLI'
              AND    c.NAME != g.asciiname ) g
ON     gg.geonameid = g.geonameid
SET    gg.asciiname = g.NAME
WHERE  gg.fcode = 'PCLI';

UPDATE geoname
SET    asciiname = 'Congo'
WHERE  geonameid = 2260494;

SELECT g.geonameid,
       g.asciiname,
       c.NAME
FROM   geoname g
JOIN   countryinfo c
ON     c.iso_alpha2 = g.country
WHERE  g.fcode = 'PCLI';

COMMIT;
```

**Comment by norinespears** [comment]
This is not working in the Wizard itself. When I run the Wizard I am not given the option of pre-loading Geography and when I open my new database the info is not there.

**Comment by maxxxxxdlp** [comment]
Do you have the latest build installed?
https://github.com/specify/specify6/actions/runs/991484180

**Comment by norinespears** [comment]
apologies! 
I am on a Mac and using build #305. Since I have had issues with my setup I asked Theresa to verify that she was seeing the same thing and she is. She is also using #305 but on a PC.

**Comment by maxxxxxdlp** [comment]
Unable to replicate
I used this build and the tree was created with short names without issues - https://github.com/specify/specify6/actions/runs/991484180
I also tried building specify on my own from cada728b5dbb4c985e3136876074a5ffbf020535 and building it from HEAD with that commit cherry-picked - all worked without any problems

(tested on Ubuntu)

**Comment by asommerville20** [comment]
Was there further discussion on this that I missed?
I'm using the build Max referenced and there still isn't a geography tree being created (when created using the Wizard).

**Comment by timo11** [comment]
Use the latest build.

**Comment by asommerville20** [comment]
Geography tree loads with the latest build. Does this look right? Names aren't the shortest they could be but I'm not sure what we decided on.
![image](https://user-images.githubusercontent.com/76126408/124644191-9946b100-de57-11eb-8849-cadcd2992f75.png)

**Comment by maxxxxxdlp** [comment]
I don't know why, but it is working fine for me with the built I referenced earlier

![Screenshot_2021-07-04_16-31-03](https://user-images.githubusercontent.com/40512816/124644717-3d9e1700-de9b-11eb-8000-a7afe3b8e5be.png)

I will try to update that file again, though this time by hand, which hopefully would fix the issue

**Comment by timo11** [comment]
As far as I know no version based on the updates from last fall works on windows, and maybe mac also.
We are reverting to the 6.8.00 geonames.

**Comment by maxxxxxdlp** [comment]
@asommerville20 can you please test it again with this build? https://github.com/specify/specify6/actions/runs/1005898566

**Comment by asommerville20** [comment]
Looks good on my end, short names are working.
