### ISSUE TITLE
Create Deaccession Attachment icon

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#955]

**Comment by norinespears** [comment]
![deaccession_attachment](https://user-images.githubusercontent.com/61208178/125358410-783a0080-e32e-11eb-918b-838136d000a5.png)

**Comment by norinespears** [comment]
![deaccession_attachment](https://user-images.githubusercontent.com/61208178/126002124-11d91b00-d76c-466c-a023-3691c14b7e70.png)
sorry - the first attempt was the wrong size!

**Comment by norinespears** [comment]
should this be in the latest build?

**Comment by norinespears** [comment]
This is still too large. Could Norine have sent the icon with a different name so that it is not replacing the first one?
