### ISSUE TITLE
Create Disposal Attachment icon

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#956]

**Comment by norinespears** [comment]
![disposal_attachment](https://user-images.githubusercontent.com/61208178/125358441-812ad200-e32e-11eb-915a-a36f73dc8e99.png)

**Comment by norinespears** [comment]
![disposal_attachment](https://user-images.githubusercontent.com/61208178/125363096-a0792d80-e335-11eb-92d2-733b7dd00f1f.png)

**Comment by tlammer** [comment]
it is not the same size as other attachment icons

**Comment by norinespears** [comment]
can you take a screenshot?

**Comment by tlammer** [comment]
![image](https://user-images.githubusercontent.com/12532430/125971696-1da5a907-11f8-4065-bd8a-e0ab4fe71219.png)

**Comment by tlammer** [comment]
![image](https://user-images.githubusercontent.com/12532430/125971749-79fa16c6-fc62-4616-be30-b9313c790c81.png)

**Comment by norinespears** [comment]
![disposal_attachment](https://user-images.githubusercontent.com/61208178/126002070-f09449ee-3dff-46f1-9286-aa3ddd6b2824.png)
