### ISSUE TITLE
Add SpiceDig btn to Data Entry Forms.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#957]
Add a button to view the "spice dig" for Occurrences (Collection Object form) and Names (CollectionObject and Taxon form)

**Comment by timo11** [comment]
This is working with ugly icons and a problem with a truncated separator line.

On CollectionObject data forms 2 buttons appear, one for Occurrence dig, the other for the Name dig for the current determination. (with the same ugly icon currently, the tooltip reveals which is which). The buttons should be enabled all the time except for newly-created unsaved records.

On taxon forms there is one button for the taxon name dig, with the same enablement behavior. Sadly, the button currently does not appear on popped up taxon dlgs, such as from the tree viewer.

**Comment by tlammer** [comment]
cannot see it on the taxon subform, which is what you see when viewing a taxon record from the taxon tree

**Comment by timo11** [comment]
Does not show up dialogs. As previously explained.

**Comment by timo11** [comment]
A shiny web page displays when the Spice Dig Occurrence btn (the left one) on CO forms is clicked. The Tx occurrence buttons on CO and Taxon (main forms only) forms still show JSON.
