### ISSUE TITLE
Create icons for Spice Dig Occurrence and Name buttons.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#958]

**Comment by norinespears** [comment]
![SpNLocality](https://user-images.githubusercontent.com/61208178/125339441-e8d52300-e316-11eb-9fa3-a34f9ae1df33.png)
![SpNTaxon](https://user-images.githubusercontent.com/61208178/125339442-e96db980-e316-11eb-838c-d0523cfc5526.png)

**Comment by maxxxxxdlp** [comment]
Specify network badges:

Inactive:
![SpNetwork_inactive](https://user-images.githubusercontent.com/40512816/125968827-5b9797ff-8420-40ea-89fb-b0b0110f8705.png)

Hover:
![SpNetwork_hover](https://user-images.githubusercontent.com/40512816/125968831-756716f8-4798-409e-ab13-f2c1d9cba9db.png)

Active:
![SpNetwork_active](https://user-images.githubusercontent.com/40512816/125968836-6527b79e-d756-4841-98be-2de5d30e2548.png)

**Comment by tlammer** [comment]
tim said we should only see the active icon on the form and that's what I see
