### ISSUE TITLE
New fields not on the form by default should be hidden

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#962]

**Comment by tlammer** [comment]
Fields to be hidden:
Agent: text3, text4, text5
Accession: Text4, text5, fields showing up as "accession.actualtotalcountamt", "accession.collectionobjectcount", "accession.preparationcount", and "accession.totalcountamt"
Determination: number3, number4, number5
Collecting Trip: text1
Permit: copyright, permit text, reserved integer 1, reserved integer 2, reserved text 3, reserved text 4, status, status qualifier
Reference work: doi, uri
disposal: text1, text2, number1, number2, yesno1, yesno2
gift: date1, date1 (Day), date1 (month), date1 (year), date1 precision,
deaccession: number3
treatment event: number1, number2, number3, number4, number5, text1, text2, text3, text4, text5, yesno1, yesno2

**Comment by timo11** [comment]
These fields will still be visible in dbs that already contain them.

**Comment by tlammer** [comment]
Disposal fields still visible
