### ISSUE TITLE
Remove GBIF Registration sidebar menu item from Configuration

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#975]
![image](https://user-images.githubusercontent.com/12532430/125496528-82cc8d78-4a56-43e9-b498-9095e786ac58.png)
It doesn't do anything currently and is not in this release

**Comment by maxxxxxdlp** [comment]
Duplicate of https://github.com/specify/specify6/issues/973

**Comment by tlammer** [comment]
different from #973
