### ISSUE TITLE
Edit Spice dig menu item in Taxon menu

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#976]
The way spicedig appears in the taxon menu needs to be modified
![image](https://user-images.githubusercontent.com/12532430/125505761-1a5c1f51-29a4-469d-9f07-b5980a126fab.png)

**Comment by timo11** [comment]
Some one needs to decide what it should be. Is "Spice Dig" official?

**Comment by tlammer** [comment]
now appears like this
![image](https://user-images.githubusercontent.com/12532430/126191292-68236610-8aca-4ffd-bf90-3b0896999075.png)
