### ISSUE TITLE
Add fields with unique constraints to approved tables

### ISSUE THREAD

**Issue by tlammer** [specify/specify6#979]
As discussed a few months ago, fields add fields with unique identifiers to Collection Object, Collecting Event, and Locality

**Comment by norinespears** [comment]
Also - extend the length of Feature or Basis from 50 to 100 characters.

**Comment by norinespears** [comment]
what are the unique fields?

**Comment by tlammer** [comment]
It does appear to only allow unique identifiers in the fields.  However, the CO unique identifier frequently empties out when I click save.  Usually if I put a value in project number then save the record first, then enter a unique identifier.
the CE unique identifier in these instances (which I also filled out) will appear to save, but when I do a query on the fields, it will say, for example:
![image](https://user-images.githubusercontent.com/12532430/127224168-f6c4262d-acb3-44ce-83be-1a5a29534121.png)
when the same database, in another open tab, I also see this:
![image](https://user-images.githubusercontent.com/12532430/127224274-0b27b7d1-2aa9-4b17-a39a-d977cc4a6e8f.png)

**Comment by timo11** [comment]
Should be fixed. Fix won't take effect unless a schemaupdate is done. And the fix won't work on dbs that have already the field added.

**Comment by tlammer** [comment]
brand new database.  CO.uniqueidentifier still disappears in f139321

**Comment by tlammer** [comment]
brand new database, number still disappears
