### ISSUE TITLE
Interactions Prefs are ignored when there no CO Recordsets, no Prep Recordsets, and no Information Requests.

### ISSUE THREAD

**Issue by timo11** [specify/specify6#983]
When there no CO Recordsets, no Prep Recordsets, and no Information Requests, when "loan" (and probably Gift, etc) on the side bar is clicked a collectionobject-based catalog number entry dialog appears, regardless of the table and field preferences for interactions.

**Comment by norinespears** [comment]
This is fixed but I think an enhancement to either NOT give Record Set as an option when there are none or give a pop-up message that there are none would be helpful.
