### ISSUE TITLE
Display message when no data is available for Specify Network/Make Taxon Sp Network compatible with CO Sp Network button

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#994]
When a user clicks on the Sp Network button on the CO form but there is not sufficient data in the record for results this message is displayed: 

<img width="522" alt="Screen Shot 2021-07-22 at 4 45 27 PM" src="https://user-images.githubusercontent.com/61208178/126714117-61d3fd28-940b-4665-89be-5df88041189c.png">

When a user clicks on the Sp Network button on the Taxon form but there is not sufficient data in the record for results no similar message is displayed.

**Comment by timo11** [comment]
The "lacks identifying data" msg is displayed when a taxon has no fullname, i.e. for newly created, unsaved taxa.
