### ISSUE TITLE
Calculated fields (counts) not working in Deaccessions table

### ISSUE THREAD

**Issue by norinespears** [specify/specify6#999]
On a Mac
Build #352
As I understand it if I create a Deaccession from a Disposal, Exchange Out, or Gift the counts in the Deaccession should total all items in the other tables combined. When I create a Deaccession from a Disposal the counts do not update either in the form or in the query. 
<img width="1146" alt="Screen Shot 2021-07-26 at 4 46 45 PM" src="https://user-images.githubusercontent.com/61208178/127064873-61794d03-30b1-4a9c-8b6a-fd9de754c62e.png">
<img width="866" alt="Screen Shot 2021-07-26 at 4 46 34 PM" src="https://user-images.githubusercontent.com/61208178/127064880-dcb75cf9-62dc-4492-abbb-8248904b4d12.png">

**Comment by norinespears** [comment]
Norine and Andy seeing this on iOS and Theresa tested this on PC and she is not seeing numbers either.

**Comment by timo11** [comment]
maybe it will work now.l

**Comment by tlammer** [comment]
my deaccession counts still blank in a newly created database using the commit made for this bug

**Comment by norinespears** [comment]
This is still not working for me on a Mac build #365

**Comment by tlammer** [comment]
added multiple disposals from multiple preps in different co's (some with only one prep from the co, some with more than one prep from the same co) and a gift.  The numbers were right
